### ISSUE TITLE
IMF XML file parsing broken when relative path used

### ISSUE THREAD

**Issue by pchapmanvc** [MediaArea/MediaInfoLib#100]
Currently if you pass an IMF XML file (ASSETMAP, CPL, PKL) to MediaInfoCLI as a relative path, then MediaInfo will not pick up the related XML files nor see the referenced sources.

e.g.
`mediainfo ASSETMAP.xml`
will not display any useful info about referenced files, but
`mediainfo /home/pete/ASSETMAP.xml`
will.

**Comment by JeromeMartinez** [comment]
Thanks!
(I don't use relative paths enough, so I missed this issue)
