### ISSUE TITLE
ProRes RAW

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#1008]
It seem that for now it show the codecID as format: `aprh`
Shouldn't "ProRes RAW" be more meaningful?

Samples:
https://filmplusgear.com/prores-raw-testfiles-for-download-nab-2018/

**Comment by JeromeMartinez** [comment]
I can map aprh to ProRes RAW
Do you have a sample file?

**Comment by JeromeMartinez** [comment]
argh, "for download" :)

**Comment by JeromeMartinez** [comment]
Quick implementation, result:

```
Video
ID                                       : 2
Format                                   : ProRes
Format version                           : Version 0
Format profile                           : RAW
Codec ID                                 : aprh
Duration                                 : 10 s 480 ms
Bit rate mode                            : Variable
Bit rate                                 : 1 154 Mb/s
Width                                    : 4 112 pixels
Height                                   : 2 176 pixels
Display aspect ratio                     : 1.890
Frame rate mode                          : Constant
Frame rate                               : 25.000 FPS
Color space                              : RGB
Scan type                                : Progressive
Original scan type                       : Interlaced
Original scan order                      : Bottom Field First
Bits/(Pixel*Frame)                       : 5.160
Stream size                              : 1.41 GiB (100%)
Writing library                          : appl
Language                                 : English
Encoded date                             : UTC 2018-04-12 02:50:52
Tagged date                              : UTC 2018-04-12 02:50:52
Color primaries                          : Generic film
Transfer characteristics                 : Linear
Matrix coefficients                      : Identity
```
looks like there are [2 flavors or RAW (RAW and RAW HQ)](https://www.premiumbeat.com/blog/prores-raw-change-your-work/), any idea if aprh is for RAW or RAW HQ?

**Comment by Sami32** [comment]
I only know that it apply to RAW HQ.
I suspect that the file #6 will give us the answer but it will take time to download such file on my Internet connection.

Hehe, very quick ;)
Look good to me :+1:

**Comment by JeromeMartinez** [comment]
> I only know that it apply to RAW HQ.

How? name below videos from the link are "Filmplusgear ProRes RAW" so no "HQ".

**Comment by Sami32** [comment]
Because it is what i deducted when i read that and see that my sample was 4K:
>Nerd info: 1080 or 4K DCI 25P from a Sony FS5, Fujinon MK 18-55 and an Atomos Shogun Inferno.

Anyway we get the confirmation there:
https://forum.blackmagicdesign.com/viewtopic.php?f=2&t=71762&start=50#p402542

**Comment by JeromeMartinez** [comment]
hum... Makes sense, aprh for HQ and aprn for "normal".
Wondering what are the others 4CC in the list.

**Comment by Sami32** [comment]
He said they they are for future use, but i have no idea of what are the Apple plan ;)
Maybe "aprs" for simple, "aprx" for expanded or extra and no idea for "apro", original? Lol

**Comment by Sami32** [comment]
Oh, i just saw that i had tested it with FFmpeg on the downloaded sample and that it displayed ProRes RAW HQ, sp that maybe why i knew it.
Damn red fish memory ;)

**Comment by Sami32** [comment]
It seem FFmpeg get this information from the encoder metadata.

**Comment by Sami32** [comment]
Wait!
We have forgot the Matroska case: `V_PRORES`

**Comment by Sami32** [comment]
forget

**Comment by JeromeMartinez** [comment]
> We have forgot the Matroska case

This is another issue, we currently don't provide ProRes profile for any ProRes stream, maybe something to add, right.
