### ISSUE TITLE
VC-1 video level?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#1039]
Shouldn't the level also be displayed?

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/51e93f23-ac3b-464a-98b2-cca03b4c9984/a-question-about-wmv-videos-format-profile?forum=encoder

**Comment by Sami32** [comment]
It seem that it is not anymore displayed by default on recent MI version.

Sorry for the noise.

**Comment by JeromeMartinez** [comment]
I have the profile and level on my side, e.g.

```
Video
Format                                   : VC-1
Format profile                           : Advanced@L3
```
