### ISSUE TITLE
EAC3 incorrect detection?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#1048]
I admit that this find was weirdly encoded. EAC3 with 2 channels and a bitrate of 128k...
I'm wondering if such format shouldn't have been detected as AC-3 also if it seem that EAC-3 header have been left?

Sample:
https://anonfile.com/k3uc0bl0b6/ffmpegvideo_64_1542472662390_ac3

**Comment by JeromeMartinez** [comment]
Why weird? E-AC-3 does not limit the count of channels, 128 Kbps stereo E-AC-3 is valid as far as I know.
this file looks like a perfectly valid E-AC-3 stream (bsid is 16), and is not AC-3 (bsid would be 8).

**Comment by Sami32** [comment]
Ok.
What is weird to me is to have downgraded EAC3 to such low specification for compatibility instead of using AC-3.

**Comment by JeromeMartinez** [comment]
Nothing weird, quality is better with E-AC-3 compared to AC-3 for same channel count / bitrate, so E-AC-3 is to be preferred if compatibility with legacy decoders is not important.

**Comment by Sami32** [comment]
To avoid open an issue if it is not necessary i prefer ask here first.

@JeromeMartinez Do the same format TrueHD+Atmos should differer in the display when set into a container or set into a .thd file?
AC-3 MLP FBA 16-ch     (from a .m2ts file)
MLP FBA 16-ch             (from the audio stream copied to .thd file)
