### ISSUE TITLE
AC3 stream not detected?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#1051]
FFmpeg detect 3 audio streams while MI detect only 2.
https://www89.zippyshare.com/v/CYIdmZum/file.html

So one should be mistaken ;)

**Comment by Sami32** [comment]
It seem to be a substream.
The problem athat i see is to apply the MI audio parsing to FFmpeg command line, as the audio stream refered to 0:2 by FFmpeg is "unlistenable" by itself.

**Comment by Sami32** [comment]
Hum...i don't think MI is the faulty one ;)

**Comment by JeromeMartinez** [comment]
We actually merge Bluray substreams in a single track, this is on purpose (single content).

**Comment by Sami32** [comment]
Yes, that sound fine to me as the substream isn't playble by itself AFAIK.
