### ISSUE TITLE
Duration is missing for MP3 file

### ISSUE THREAD

**Issue by HairyDan** [MediaArea/MediaInfoLib#1066]
[bigbuck_audio.mp3.zip](https://github.com/MediaArea/MediaInfoLib/files/2691271/bigbuck_audio.mp3.zip)

When running mediaInfo on this file, there is no Duration field present.
The duration is visible in macOS's "Get Info" feature as well as in ffprobe.

I have not been able to replicate the issue with any other audio files.
I am using the most recent version of MediaInfo (MediaInfo Command line, MediaInfoLib - v18.12)

**Comment by JeromeMartinez** [comment]
Some issue in the informational metadata parsing, I confirm that duration metadata is there.

**Comment by HairyDan** [comment]
Thanks for the quick response!

Do you have a best-guess as to how commonly this bug will occur? Is this a very irregular sample file or should we prepare to encounter this more often?

**Comment by robUx4** [comment]
I have the issue on 315 MP3 files out of 1858 files. I generated the Xing frame myself (missing in the original).

It seems the parser is missing bits after the ID3v2 tags:
```
...
00738E  COMM - Comments (114 bytes)
00738E   Header (10 bytes)
00738E    Frame ID:                            COMM
007392    Size:                                104 (0x00000068)
007396    Flags:                               0 (0x0000)
007398    Tag alter preservation:              0 (0x0000000000000000)
007398    File alter preservation:             0 (0x0000000000000000)
007398    Read only:                           0 (0x0000000000000000)
007398    Compression:                         0 (0x0000000000000000)
007398    Encryption:                          0 (0x0000000000000000)
007398    Grouping identity:                   0 (0x0000000000000000)
007398   Text_encoding:                        0 (0x00)
007399   Language:                             eng
00739C   Short_content_descrip:                iTunNORM
0073A4   Null:                                 0 (0x00)
0073A5   The_actual_text:                       00000A59 00000A74 00003D70 0000467C 0001119E 0001119E 00008000 00008000 00013897 000186E5
007400  Padding (1524 bytes)
007400   Data:                                 (1524 bytes)
0079F4  --------------------------
0079F4  ---   Id3v2, filling   ---
0079F4  --------------------------
0079F4  ---------------------------
0079F4  ---   Id3v2, finished   ---
0079F4  ---------------------------
007C83 frame - Frame 0 - 0 (0x0) (626 bytes)
007C83  Header (4 bytes)
007C83   syncword:                             2047 (0x7FF) - (11 bits)
007C84   ID:                                   3 (0x3) - (2 bits) - MPA1
007C84   layer:                                1 (0x1) - (2 bits) - L3
```

The first syncword is actually at `0079F4`  (verified in an hex editor). There is however some garbage between the end of that Xing frame and the syncword correctly detected at `007C83` (present in the original source, after the same garbage). Maybe the Xing frame is detected by going backward when finding a frame? 

BTW VLC does find the frame and uses the duration accordingly.

**Comment by JeromeMartinez** [comment]
> I have the issue on 315 MP3 files out of 1858 files

Please share 1 (or more) of theses files.

**Comment by robUx4** [comment]
[Remember The Eighties Volume 6.zip](https://github.com/MediaArea/MediaInfoLib/files/7526046/Remember.The.Eighties.Volume.6.zip)

the .fixed version is the one with the Xing header

**Comment by JeromeMartinez** [comment]
> There is however some garbage between the end of that Xing frame and the syncword correctly detected

This is the issue, as I synchronize on several frames in order to avoid false positive sync.
I added an exception on Info and Xing headers (it was already made for VBRI headers).
https://github.com/MediaArea/MediaInfoLib/pull/1454

Note that this is not linked to this issue ticket, it would have deserved its own ticket. By the way, I notice that the file in the original issue is well detected now so the original issue seems fixed, I close the ticket.
