### ISSUE TITLE
list Matroska attachments

### ISSUE THREAD

**Issue by darealshinji** [MediaArea/MediaInfoLib#1067]
Is there a way to get a list of attachments from a Matroska file using `MediaInfoLib::Get()`?

**Comment by JeromeMartinez** [comment]
File names: `MI.Get(Stream_General, 0, "Attachments")`
Cover content: `MI.Option("Cover_Data", "base64"); MI.Open(); MI.Get(Stream_General, 0, "Cover_Data");` (content part was a quick and dirty patch for specific need i.e.E cover data, there is a need to work this part is one is interested in such kind content)

**Comment by darealshinji** [comment]
Thanks.
I used `MI.Option(__T("Info_Parameters"))`, `MI.Option(__T("Info_Capacities"))` and `MI.Option(__T("Info_Codecs"))` but couldn't find anything about attachments in the output.

**Comment by alexmercerind** [comment]
> File names: `MI.Get(Stream_General, 0, "Attachments")`
> Cover content: `MI.Option("Cover_Data", "base64"); MI.Open(); MI.Get(Stream_General, 0, "Cover_Data");` (content part was a quick and dirty patch for specific need i.e.E cover data, there is a need to work this part is one is interested in such kind content)

I was just confused why I was unable to get `"Cover_Data"` and then I simply added the line you mentioned and it worked.
```cpp
this->retriever->Option(L"Cover_Data", L"base64");
```
Thanks for this comment.
