### ISSUE TITLE
Ignore METADATA_BLOCK_PICTURE on Inform()

### ISSUE THREAD

**Issue by linux-man** [MediaArea/MediaInfoLib#1096]
Issue discussed on https://github.com/linux-man/nemo-mediainfo-tab/issues/8

[Sample.zip](https://github.com/MediaArea/MediaInfoLib/files/2936093/Sample.zip)

**Comment by JeromeMartinez** [comment]
Thanks.
Will be in [snapshots](https://mediaarea.net/download/snapshots/binary/) tomorrow and in next release.
