### ISSUE TITLE
ITT File Format

### ISSUE THREAD

**Issue by juice** [MediaArea/MediaInfoLib#1119]
Since the Version 17.10 the MediaInfoLib is not showing any informations from ITT Files.

We use the macOS/Linux CLI.

With the newest Version 19.04 the lib only shows an empty line as output. Am i missing something? Was the ITT support removed or is it an issue in the lib?

**Comment by JeromeMartinez** [comment]
Nothing specific was done about ITT files, before or after 17.10.
We have no ITT file, please provide one for debugging purpose (send a mail at info@mediaarea.net if not possible to put it publicly).

**Comment by JeromeMartinez** [comment]
Thanks for the file.

> the lib only shows an empty line as output

oh, also not showing the file name & size, so definitely an ugly regression and misbehavior.
It is some TTML, expected to be supported, we'll fix that.

**Comment by JeromeMartinez** [comment]
Fixed version will be in [snapshots](https://mediaarea.net/download/snapshots/binary/) tomorrow.
