### ISSUE TITLE
Add a function to reset all options to their default values

### ISSUE THREAD

**Issue by sbraz** [MediaArea/MediaInfoLib#1128]
This would help us implement https://github.com/sbraz/pymediainfo/pull/71. At the moment, we cannot really let users set options themselves because those options would remain even when they are not specified any more.

**Comment by sbraz** [comment]
Hi Jérôme, do you have an ETA on this issue?

**Comment by JeromeMartinez** [comment]
`MediaInfo::Option("Reset", "");`
Will be in the next release (soon).
