### ISSUE TITLE
Odd semicolon ';' after 'if' operator

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#1178]
V529 [CWE-670] Odd semicolon ';' after 'if' operator. File_Mpeg_Descriptors.cpp 2873

![изображение](https://user-images.githubusercontent.com/920705/67161111-fc30a580-f35f-11e9-848d-970ae9642a5d.png)

**Comment by JeromeMartinez** [comment]
Definitely a typo.
