### ISSUE TITLE
possible issue in DPX info mapping

### ISSUE THREAD

**Issue by vectronic** [MediaArea/MediaInfoLib#1190]
Hello,

This code looks like it is incorrectly mapping colorspace to transfer characteristics and vice-versa:

https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Image/File_Dpx.cpp#L814-L815

**Comment by JeromeMartinez** [comment]
Ooooooooops. Wondering how it was possible for the author of such code (me) to do this mistake...
I guess it was not caught because most values are same.

**Comment by kieranjol** [comment]
Great catch!
