### ISSUE TITLE
Debian package repository for libmediainfo-dev does not contain the actual .so file, just a link

### ISSUE THREAD

**Issue by NickDrouin** [MediaArea/MediaInfoLib#1202]
The download packages here:
https://packages.debian.org/buster/libmediainfo-dev
https://packages.debian.org/stretch/libmediainfo-dev

Are missing the lib file, only symbolic links were packaged.

Repro steps:
```
curl -o ./libmediainfo-dev_18.12-2_amd64.deb http://http.us.debian.org/debian/pool/main/libm/libmediainfo/libmediainfo-dev_18.12-2_amd64.deb
dpkg -x ./libmediainfo-dev_18.12-2_amd64.deb ./unpacked_libmediainfodev
ls -la ./unpacked_libmediainfodev/usr/lib/x86_64-linux-gnu
echo 'Note that libmediainfo.so -> libmediainfo.so.0.0.0  and there is no libmediainfo.so.0.0.0 '
```
I checked with both the link above, and a couple other FTP mirrors, none have the actual lib.

**Comment by NickDrouin** [comment]
Work-around, the lib is properly packaged within: 
https://packages.debian.org/buster/libmediainfo0v5

**Comment by JeromeMartinez** [comment]
> https://packages.debian.org [...]

We are not the maintainers of Debian package, the maintainer name and contact method is on the linked webpages you provided.
That said, 

> echo 'Note that libmediainfo.so -> libmediainfo.so.0.0.0  and there is no libmediainfo.so.0.0.0 '

"-dev" packages are not intended to have libmediainfo.so.0.0.0, and "only symbolic links were packaged" is the behavior I expect from Debian maintainers, as the lib file is in the non "-dev" package and "-dev package depends on non "-dev" package. "-dev" package is for extra (compared to non "-dev" package) files needed for development
so by unpacking manually this "-dev" package, you are supposed to have unpacked the non "-dev" package (and all dependencies) at the same place.
As you force dpkg to discard dependencies with " -x", check dependencies listed on the linked webpages and download/unpack them also manually.

> Work-around, 

Not a workaround, it is the expected location of the lib.
