### ISSUE TITLE
MediaInfo CLI giving incomplete language audio and text info compared to Mediainfo GUI

### ISSUE THREAD

**Issue by cwaynedavis1946** [MediaArea/MediaInfoLib#1214]
Attached is output from MediaInfo GUI and CLI showing differences.  Am not posting the video file but can supply it if needed.  Ran GUI and CLI with no options but earlier used --Inform option with CLI giving same results.  I may have noticed other differences but not sure and can't reproduce at this time.

Note GUI Audio Track #1 Language shows English.  CLI Audio Track #1 does not list language.
GUI Text Tracks #1 and #2 list English.  CLI no language.
CLI also does not list Audio and Text Default and Forced.

I was asked to post this but it no longer matters to me.  I'm now using pymediainfo,  If I had been aware of pymediainfo earlier I wouldn't have used CLI.  Not sure how important CLI is now.

This is not criticism.  I greatly appreciate mediainfo.  If I had to write my own software to parse video metadata I'd probably be dead of old age without getting anything working.

[BWGUI.txt](https://github.com/MediaArea/MediaInfoLib/files/4196159/BWGUI.txt)
[BWCLI.txt](https://github.com/MediaArea/MediaInfoLib/files/4196160/BWCLI.txt)

**Comment by kieranjol** [comment]
Is the gui and the cli using the same version?

**Comment by JeromeMartinez** [comment]
@cwaynedavis1946 please send the file (my email is on my GitHub profile).

**Comment by cwaynedavis1946** [comment]
My apologies to all.  I don't remember where I got the version of the CLI I had, MediaInfoLib - v0.7.31, but it's obviously obsolete.  Jerome contacted me and I downloaded version 19.09 and tried it.  Line for line same results as the GUI.  I thought that I had downloaded the GUI and CLI at the same time but obviously not.  Sorry for wasting Jerome's time.

Wayne
