### ISSUE TITLE
“Codec configuration box” cannot be translated in MediaInfo GUI

### ISSUE THREAD

**Issue by stevenlele** [MediaArea/MediaInfoLib#1217]
In MediaInfo GUI, the string “Codec configuration box” cannot be translated. It’s displayed in English even if I added the translation.

https://github.com/MediaArea/MediaInfoLib/blob/393d76993575aa8837fafac28d5821d1fa01210e/Source/Resource/Text/Language/DefaultLanguage.csv#L251

I guess it’s because the string is hardcoded. You probably need to change the English string into the key `CodecConfigurationBox`.

https://github.com/MediaArea/MediaInfoLib/blob/393d76993575aa8837fafac28d5821d1fa01210e/Source/MediaInfo/Multiple/File_Mpeg4.cpp#L1313

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/f6bea1d89a1ce54708df435dcf68578640a19359#diff-0a88091faa3606da180ea6178eb631a9).
