### ISSUE TITLE
SIGFPE, Divide by zero

### ISSUE THREAD

**Issue by Rawa** [MediaArea/MediaInfoLib#122]
The file provided bellow causes mediainfolib to crash and send a SIGFPE. Cause is a divide by zero at MediaInfoLib/Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp:1703
caused by variable Stream_Temp.mdhd_TimeScale is set to zero.

File can be found here: http://upload.davidgoransson.com/Faulty.mp4

**Comment by JeromeMartinez** [comment]
I forgot to update the ticket.
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/474683583c80614ea04ac0e6513ac15918678fba)
