### ISSUE TITLE
RuntimeError opening a signed url on AWS

### ISSUE THREAD

**Issue by nico00** [MediaArea/MediaInfoLib#1269]
With libmediainfo.so v20.03 for AWS Lambda, if I generate a signed url on S3 and parse certain type of videos, I get the following error message:
`RuntimeError: An eror occured while opening https://<signed url> with libmediainfo
`
Please note that:
- this happens only with signed urls, but not if I download the video and run it locally
- this happens only with certain videos. Two videos that raise such error are the following:
http://download4.dvdloc8.com/trailers/divxdigest/simpsons_movie_1080p_hddvd_trailer.zip
http://download4.dvdloc8.com/trailers/divxdigest/i_am_legend-1080p_blu-ray_trailer.zip
- I tested my code with other videos with success
- I tested the above problematic videos using the libmediainfo.so distributed with Ubuntu 18.04 (not sure which is the version but for sure older than 20.03), with success.

Thanks

**Comment by JeromeMartinez** [comment]
Please test [the latest snapshot](https://mediaarea.net/download/snapshots/binary/libmediainfo0/), there may be already a fix.
There is also a [pending issue about signed URLs](https://github.com/MediaArea/MediaInfo/issues/454), I am working on it, but it seems that this is not the same kind.
Please send me a private email with a signed URL having such issue, so I can test directly.

**Comment by JeromeMartinez** [comment]
> With libmediainfo.so v20.03 for AWS Lambda, 

Is there a problem with mediainfo 20.04 on Ubuntu 18.04?

**Comment by nico00** [comment]
I did further tests and it seems that actually the problem was not caused by a specific video file but by the fact that the bucket was private. The latest snapshot seems to solve the problem and works also with private buckets. 
Let me know if you still need a signed URL.

**Comment by JeromeMartinez** [comment]
If all is OK with the snapshot, no need to go further.
