### ISSUE TITLE
JSON output missing additional /string fields

### ISSUE THREAD

**Issue by eugenesvk** [MediaArea/MediaInfoLib#1277]
While using this [Python MI wrapper](https://github.com/sbraz/pymediainfo/) I've noticed that one of the useful fields (nicely formatted display aspect ratio **16:9** instead of **1.778**) was missing when requesting `JSON` output from your library.
As far as I understand, [this line](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/MediaInfo_Config_Automatic.cpp#L4681) `"DisplayAspectRatio/String;;;Y NT;;;Display Aspect ratio\n"` is responsible since `Y NT` without one last `Y` flag ( `Y NTY`) means that the `show in XML` option is not activated and the field is not shown in the JSON output. (I've also noticed that this seems to be true for all Parameter**/String** variants.)

Given this, I have a few questions:
- Why is **JSON** output "less rich" and missing the values that are present in the "regular" output?
- Is there a toggle option somewhere that would allow to match the level of details in the **JSON** output by including all the fields there?
- And if not, would you be willing to add such a "All JSON" option?
Thanks!

P.S.
I understand that the Python MI wrapper allows to extract all the fields, but then it creates new tag names in the process, which is a bummer since I'm already using MI internal ones

**Comment by JeromeMartinez** [comment]
> Why is JSON output "less rich" and missing the values that are present in the "regular" output?

The content is same, only "human readable" data is not in the JSON / XML / etc, because the formatting can be done elsewhere based on the JSON content. We try to limit the size of the JSON output so we put only 1 instance of the representation of the data, not all of them.

> Is there a toggle option somewhere that would allow to match the level of details in the JSON output by including all the fields there?

Not yet.

> And if not, would you be willing to add such a "All JSON" option

There is already a "Complete" option for that, but it was not enabled for JSON (and XML).
[quick and dirty fix](https://github.com/MediaArea/MediaInfoLib/pull/1278).

> I understand that the Python MI wrapper allows to extract all the fields, but then it creates new tag names in the process, which is a bummer since I'm already using MI internal ones

I didn't get the issue, which "new tag names"? JSON output is based on MI API.

**Comment by eugenesvk** [comment]
> because the formatting can be done elsewhere based on the JSON content.

Yeah, that's what I ended up doing via a copy&paste (with a minor conversion to Py) of this:
```cpp
         if (DAR>=(float)1.23 && DAR<(float)1.27)   DARS=__T("5:4");
    else if (DAR>=(float)1.30 && DAR<(float)1.37)   DARS=__T("4:3");
    else if (DAR>=(float)1.45 && DAR<(float)1.55)   DARS=__T("3:2");
    else if (DAR>=(float)1.55 && DAR<(float)1.65)   DARS=__T("16:10");
    else if (DAR>=(float)1.65 && DAR<(float)1.70)   DARS=__T("5:3");
    else if (DAR>=(float)1.74 && DAR<(float)1.82)   DARS=__T("16:9");
    else if (DAR>=(float)1.82 && DAR<(float)1.88)   DARS=__T("1.85:1");
    else if (DAR>=(float)2.15 && DAR<(float)2.22)   DARS=__T("2.2:1");
    else if (DAR>=(float)2.23 && DAR<(float)2.30)   DARS=__T("2.25:1");
    else if (DAR>=(float)2.30 && DAR<(float)2.37)   DARS=__T("2.35:1");
    else if (DAR>=(float)2.37 && DAR<(float)2.45)   DARS=__T("2.40:1");
```
but I'd like not to do that since your awesome library already has all those conversions! :)

> There is already a "Complete" option for that, but it was not enabled for JSON (and XML).
> [quick and dirty fix](https://github.com/MediaArea/MediaInfoLib/pull/1278).

Nice, will check it out ("Complete" is already enabled by default in the pymediainfo library), so I'd only need to wait till it's incorporated into the next version of the dll!

> I didn't get the issue, which "new tag names"? JSON output is based on MI API.

What I meant is this:
`DisplayAspectRatio/String` MI internal tag
`Display Aspect ratio` Human readable output (when not in JSON format)
`other_display_aspect_ratio` pymediainfo converted tag (added `other_`)

I'd like to retain the MI internal tags without any of the reformatting, but just get all of them, including the `/String` variants!
Hopefully your fix will alllow that

**Comment by eugenesvk** [comment]
> There is already a "Complete" option for that, but it was not enabled for JSON (and XML).
> [quick and dirty fix](https://github.com/MediaArea/MediaInfoLib/pull/1278).

I've built a dll with this fix on Windows and it's working, I do indeed get a `DisplayAspectRatio_String` field back when opening a file with the `JSON` option!
Pity the build is failing for some reason in other CI tests...
