### ISSUE TITLE
creatingLibrary field missing in JSON output

### ISSUE THREAD

**Issue by paxter** [MediaArea/MediaInfoLib#1398]
Is there a reason why this value is only in XML output and missing in JSON? This information is very helpful especially if any new codecs are detected in new versions.

**Comment by JeromeMartinez** [comment]
> Is there a reason why this value is only in XML output and missing in JSON?

No :-p.

**Comment by paxter** [comment]
:D
As usual, thanks for your fast reply and the enhancement label of course. :)
