### ISSUE TITLE
Id3v2 -- should recognize "Blues" as a valid genre

### ISSUE THREAD

**Issue by mitchblank** [MediaArea/MediaInfoLib#1414]
I was writing some small scripts to analyze the mp3s I have in my OS/X Music library, looking for metadata inconsistencies.  To do that I have some python code that makes calls out to `mediainfo --Output=JSON -f` on each file and then turning them into python objects.  All of that is working great.

The only odd bug that I couldn't figure out is that I had a couple ripped CDs with "Genre" == "Blues" and that field was not showing up correctly.  Indeed, Music.app (f/k/a iTunes) showed the genre just fine but `mediainfo`'s CLI reported that the file had not been tagged with a genre!

That led me down a bit of a rabbit hole, but I think I understand the problem.  As you probably remember, ID3 can tag genres either as free-form text or as numeric codes.  Apple Music will support either, but if you use a genre that has a well-known ID3v1 numeric code it will use that (likely for maximum compatibly with ancient mp3-reading software)

The numeric code for "Blues" happens to be zero (see https://en.wikipedia.org/wiki/List_of_ID3v1_Genres )  MediaInfoLib knows this as well (see `Genre_000` in Source/Resource/Text/Language/DefaultLanguage.csv )

However, the code that interprets the numeric genre codes treats both `"0"` and `"255"` as unset values.  In Source/MediaInfo/Tag/File_Id3v2.cpp :
```
        case Elements::TCON :
[...]
                                if (Element_Value==__T("0") || Element_Value==__T("255"))
                                    Element_Value.clear();
                                Fill(Stream_General, 0, General_Genre, Element_Value);
[...]
        case Elements::TCO  :
[...]
                                if (Element_Value==__T("0") || Element_Value==__T("255"))
                                    Element_Value.clear();
                                if (!Element_Value.empty())
                                    Fill(Stream_General, 0, General_Genre, Element_Value);
```
So both in the code to handle `TCO` and `TCON` tags ("Content type") will treat a string with the value `"0"` as if it were unset.  This means any file that Music.app sets to have genre "Blues" is considered genre-less by MediaInfoLib.

I assume that this may have been done as a workaround for buggy mp3 generators that may have left 0 or 255 as incorrect ways of indicating a missing genre.  However, I can't find any documentation about that.  I checked in the git history and the logic seems unchanged since the code was first imported into a VCS, and there isn't anything related to "blues" in the changelog.

It seems possible to me that the code is being overly paranoid, or possibly working around an encoder bug that has long since become irrelevant.  Possibly can `0` be accepted as a valid genre per the id3v1 spec?

**Comment by mitchblank** [comment]
Just another datapoint -- `ffprobe` shows the genre on these mp3s correctly.  Checking the source code, it accepts genre strings that are numeric (or numeric surrounded by parens) as synonyms for ID3v1 numeric genres, but it doesn't treat "0" as special: https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/id3v2.c#L337
```
    unsigned genre;
[...]
    if (!(strcmp(key, "TCON") && strcmp(key, "TCO"))                         &&
        (sscanf(dst, "(%d)", &genre) == 1 || sscanf(dst, "%d", &genre) == 1) &&
        genre <= ID3v1_GENRE_MAX) {
        av_freep(&dst);
        dst = av_strdup(ff_id3v1_genre_str[genre]);
```
So any integer string from `"0"` to `"191"` is accepted as a genre to map

**Comment by mitchblank** [comment]
Same problem in the 22.12 release

**Comment by JeromeMartinez** [comment]
Fixed by https://github.com/MediaArea/MediaInfoLib/pull/1708#issuecomment-1458203378.

**Comment by mitchblank** [comment]
Unfortunately this still seems to not work, at least for me even in the 23.06 release.

I haven't dug into the source code again, but looking at the #1708 change it only patches one place, while my original bug report found two suspect locations.  Maybe that's related?

**Comment by JeromeMartinez** [comment]
@mitchblank my mistake, I should not have closed the issue so quickly.
Please try [this dev snapshot](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20230628/), I [fixed the other line of code + ID3 (not v2)](https://github.com/MediaArea/MediaInfoLib/pull/1816/files).

**Comment by mitchblank** [comment]
Sorry, I didn't have a chance to try the snapshot you provided (I just am using the `mediainfo` CLI tool from homebrew and never found time to integrate a library snapshot.  However I can verify that the 23.11 release has fixed the issue.
