### ISSUE TITLE
Avoid "using namespace std;"

### ISSUE THREAD

**Issue by mexmer** [MediaArea/MediaInfoLib#1436]
declaring 
```
using namespace std;
```
causes various issues due some types being introduced to std namespace (like std::byte in c++17, or std::min/max macros), while they are still in compiler headers or in headers includes from other projects. especially this causes issues when compiling on windows if you have zlib compiled as dll (or static) with 
```
#define ZLIB_WINAPI
```

if MSVC project is forced to use C++14 (instead of default which is c++ latest) it can be compiled, still i would recommend to not use std namespace without prefix at all

**Comment by JeromeMartinez** [comment]
There is currently no plan to put `std::` prefix everywhere in our code.
That said, it is also not acceptable to break the build due to external include we don't control that use names in std namespace.
We'll put the external libs includes before any external include or any `using namespace`.

**Comment by mexmer** [comment]
seems it was already fixed in 21.09 (i did build 21.03, because that's what we use in our project atm.) by introducing "WindowsNamespace", still there is compilation error, when you define ZLIB_WINAPI in mediainfolib. i will create new issue for it.
