### ISSUE TITLE
Inform from MediaInfoDLL.py returns an empty string with unicode filenames and Python 2 on Linux

### ISSUE THREAD

**Issue by sbraz** [MediaArea/MediaInfoLib#144]
Using `MediaInfoDLL.py` from the git master, on Linux, this works:
```py
# -*- coding: utf-8 -*-
from MediaInfoDLL import *

MI = MediaInfo()
MI.Open(u"Example.ogg")
print repr(MI.Inform())
```
But this shows an empty string on Linux (even though it works on Windows):
```py
# -*- coding: utf-8 -*-
from MediaInfoDLL import *

MI = MediaInfo()
MI.Open(u"Examplé.ogg")
print repr(MI.Inform())
```
Using Python 3, the following works:
```py
# -*- coding: utf-8 -*-
from MediaInfoDLL import *

MI = MediaInfo()
MI.Open(u"Examplé.ogg")
print(repr(MI.Inform()))
```

I have a similar issue in my own Python wrapper: https://github.com/sbraz/pymediainfo/issues/22

**Comment by JeromeMartinez** [comment]
I think more on a Python 2 issue, with UTF-8 not well handled if it is in the source code directly.
empty result usually means that the file is not found, and with accents it is usually due to a wrong encoding (e.g. the "é" is in Latin-9 instead of UTF-8).

"coding: utf-8", ok, but is your source code saved in UTF-8?

Please try with e.g. a file name with accent coming from the command line instead (code pages are usually well handled when it is from command line), in order to see if it comes from your source code or MediaInfo.

You could also try with MI.Open(u"Exampl\u00E9.ogg")

Note: I am lazy, I don't have this configuration here, so I prefer you try first on your side with Python possible issues first, before I test it on my side.

**Comment by sbraz** [comment]
It might be a Python 2 issue but there is definitely something fishy going on. It is not an issue with my source Python file.
```py
# -*- coding: utf-8 -*-
import os
from MediaInfoDLL import *

MI = MediaInfo()
file_name = u"Exampl\u00e9.ogg"
print(file_name is u"Examplé.ogg")
print(os.path.exists(file_name))
MI.Open(file_name)
print repr(MI.Inform())
```
returns
```
True
True
u''
```

**Comment by JeromeMartinez** [comment]
OK, tested on Debian 8 with Python 2.7.
Looks like Python 2 on Linux does not automatically provide the locale to the shared object.
I need to add a workaround.
Please test https://github.com/JeromeMartinez/MediaInfoLib/commit/b1d623ff37dee10514a79ed212a145749119f3a0

**Comment by sbraz** [comment]
Your two ifs are identical. The second one is supposed to be `else:` or `if len(locale.getdefaultlocale()) == 1:`, I guess?

**Comment by sbraz** [comment]
Hmm, wait a second, [all this does](https://github.com/JeromeMartinez/MediaInfoLib/blob/b1d623ff37dee10514a79ed212a145749119f3a0/Source/MediaInfoDLL/MediaInfoDLL.cpp#L811) is set `LC_CTYPE`, right? So the issue was just that `LC_CTYPE` wasn't set, which can be fixed without calling the library.
I've just tested the snippet below which also fixes the issue and has IMHO the advantage of being easier to understand (I'm not even sure we need to exclude Mac OS, maybe changing  the locale on all POSIX systems is a good idea, after all).
```py
if os.name == "posix" and not sys.platform != "darwin":
    locale.setlocale(locale.LC_CTYPE, locale.getdefaultlocale())
```

**Comment by JeromeMartinez** [comment]
> Your two ifs are identical. 

oops. And actually was wrong (must be compared to "NONE")

> Hmm, wait a second, all this does is set LC_CTYPE, right? 

right.
And true, no need to configure in MediaInfoLib, setting it in Python script is enough, I as not aware of that (I learn...)

> I've just tested the snippet below which also fixes the issue 

OK, let's go with that.

> I'm not even sure we need to exclude Mac OS

I prefer that someone test it on Mac OS before I change something.
I don't like to change the locale in the library, I got some complains in the past about that ("the library should not change the locale" and I agree), so I prefer to change it only when I must do it.
This is also the reason I add a test on Python <3
"posix": I prefer to not change the way I test the platform for the moment, I reuse the same test as in the start of the file.
Ha, I also add a test on the empty locale now (same: I prefer to not chnage it if there is already something).

Updated code: https://github.com/JeromeMartinez/MediaInfoLib/commit/f45f80081138883ddc37731c8471f2da0d162fc3 (code is duplicated for MediaInfoList class now)

Acceptable?

**Comment by sbraz** [comment]
>  I don't like to change the locale in the library, I got some complains in the past about that ("the library should not change the locale" and I agree), so I prefer to change it only when I must do it.

Yeah, it makes sense
>  "posix": I prefer to not change the way I test the platform for the moment, I reuse the same test as in the start of the file.

OK, fair enough.

> Acceptable?

Yeah, the updated code looks good :+1: I'll let you close the issue.

**Comment by JeromeMartinez** [comment]
Closed by https://github.com/MediaArea/MediaInfoLib/pull/151

**Comment by sbraz** [comment]
@JeromeMartinez I just got my hands on a Macbook and my package's tests failed with Python 2: https://github.com/sbraz/pymediainfo/commit/56d407397053522e1822d06b98a8470754ed29c9
You should get rid of the `sys.platform != "darwin"` part. I can't re-open the issue but surely you will see my message :)
