### ISSUE TITLE
will not cross-compile using gcc 11.2.0 but is OK under with gcc 10.3.0 

### ISSUE THREAD

**Issue by hydra3333** [MediaArea/MediaInfoLib#1449]
Hello. 

Cross-compiling under Ubuntux64/mingw64, with target Win10 x64.

With an _**identical**_ build system, it cross-compiles OK under gcc 10.3.0 however it fails under gcc 11.2.0.

Attached are uncut logs (.zipx) with 10.3.0 and 11.2.0, hope that helps.

Cheers

[with_gcc11.2.0.zip](https://github.com/MediaArea/MediaInfoLib/files/7448075/with_gcc11.2.0.zip)
[with_gcc10.3.0.zip](https://github.com/MediaArea/MediaInfoLib/files/7448076/with_gcc10.3.0.zip)
.

**Comment by hydra3333** [comment]
a possibly more complete 11.2.0 log is attached

[with_later_gcc11.2.0.zip](https://github.com/MediaArea/MediaInfoLib/files/7448079/with_later_gcc11.2.0.zip)

**Comment by LigH-de** [comment]
[suggested patch for media-autobuild suite](https://github.com/m-ab-s/media-autobuild_suite/issues/2065#issuecomment-953305247)
