### ISSUE TITLE
MediaInfo Maximum bit rate float value

### ISSUE THREAD

**Issue by vish91** [MediaArea/MediaInfoLib#1465]
Hi , I have a question about mediainfo Maximum bitrate . 
If the XML Spec for the mediainfo field `Maximum Bit Rate` is a float64. 
How do parsers usually handle fields with values like this and trying to understand where the bug in on encoder setting or how did mediainfo allow generating this value  because parsing it as float will fail.

I have an input source on which the Audio track has  
```
Maximum bit rate                         : 130723 / 130723
```
From https://mediaarea.net/mediainfo/mediainfo_2_0.xsd
<xsd:element name="BitRate_Maximum" minOccurs="0" maxOccurs="1" type="xsd:float"/>

**Comment by JeromeMartinez** [comment]
Twice the value is a bug, please provide a sample file creating this output (after having checked with latest version of MediaInfo).

**Comment by vish91** [comment]
thanks @JeromeMartinez . Yeah I did check with the latest version of mediaInfo. can I send you the sample file via email or something ? it's a big file.. or I can clip a 10 sec from that and send that over. Let me know and I'll get that over to you.

**Comment by JeromeMartinez** [comment]
If the 10 sec version has the issue, it is enough for me. file or link here or at info@mediaarea.net if not shareable in public.

**Comment by vish91** [comment]
thanks @JeromeMartinez  forwarded sample on email.
Would it be possible for you to check if some older mediainfo version didn't have this bug ?

**Comment by JeromeMartinez** [comment]
> Would it be possible for you to check if some older mediainfo version didn't have this bug ?

Our old versions are [there](https://mediaarea.net/download/snapshots/binary/).

**Comment by vish91** [comment]
thanks @JeromeMartinez  for the fix. ⭐

**Comment by JeromeMartinez** [comment]
In next release or in [dev snapshots](https://mediaarea.net/download/snapshots/binary/).
