### ISSUE TITLE
MediaInfo hangs when analysing certain WAV files

### ISSUE THREAD

**Issue by danielthepope** [MediaArea/MediaInfoLib#1473]
Hi, I was trying to run MediaInfo v21.09 on a 32 bit WAV file and it appeared to go into an infinite loop (100% CPU).

I tried different bitrates and other factors and came to the conclusion that it only hangs with this specific case:
* Format: PCM
* Bit depth: 32 bits (float)
* Sampling rate: 48kHz
* Channels: 2

If you change the bit depth, sampling rate, or use mono audio, MediaInfo succeeds. In the attachment I've included some WAV files with noise generated using Audacity. The file `noise-2ch-32b-48k.wav` doesn't work in the CLI, GUI and Web version, but all the others (which only change one parameter) work fine.

I can also confirm that it worked work MediaInfo CLI v19.07, which produced the following output:
```
$ mediainfo noise-2ch-32b-48k.wav

General
Complete name                            : noise-2ch-32b-48k.wav
Format                                   : Wave
File size                                : 3.66 MiB
Duration                                 : 10 s 0 ms
Overall bit rate mode                    : Constant
Overall bit rate                         : 3 072 kb/s

Audio
Format                                   : PCM
Format profile                           : Float
Codec ID                                 : 3
Codec ID/Hint                            : IEEE
Duration                                 : 10 s 0 ms
Bit rate mode                            : Constant
Bit rate                                 : 3 072 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Bit depth                                : 32 bits
Stream size                              : 3.66 MiB (100%)
```

[wav-files.zip](https://github.com/MediaArea/MediaInfoLib/files/7857482/wav-files.zip)

**Comment by JeromeMartinez** [comment]
It is fixed in [snapshots](https://mediaarea.net/download/snapshots/binary/), we do a public release ASAP.

**Comment by danielthepope** [comment]
My favourite kind of issue is one that's already been fixed 😁 Thanks!
