### ISSUE TITLE
Less Inform() with Open(memory) than Open(file)

### ISSUE THREAD

**Issue by shpshftr** [MediaArea/MediaInfoLib#1607]
I'm trying to update our code to use the latest MediaInfoLib from v0.7.88. Yes, it's been quite a while.
Our unit tests load some data from files and some data from memory output from ffmpeg after processing the file data.
The unit tests loading data directly from files seem to be working.
The unit tests loading from memory are failing because many values are unavailable.

I've tracked down that it breaks with release v0.7.95, specifically the change:
"Rely less on file size (for growing file support)"
https://github.com/MediaArea/MediaInfoLib/commit/ef6968bab7691dbe1c67bc9fae99e63979220356

I've included test code and a couple small ts files that illustrate the problem.

I'm not sure if this is a bug or working as designed, but I'd appreciate knowing how to get more fields available from using memory buffers.

Thx, Katherine

[main.cpp.pdf](https://github.com/MediaArea/MediaInfoLib/files/9820316/main.cpp.pdf)
[187812.log.pdf](https://github.com/MediaArea/MediaInfoLib/files/9820439/187812.log.pdf)
[187812.ts.zip](https://github.com/MediaArea/MediaInfoLib/files/9820436/187812.ts.zip)
[1290996.log.pdf](https://github.com/MediaArea/MediaInfoLib/files/9820437/1290996.log.pdf)
[1290996.ts.zip](https://github.com/MediaArea/MediaInfoLib/files/9820438/1290996.ts.zip)

**Comment by JeromeMartinez** [comment]
Great report.

> from v0.7.88. Yes, it's been quite a while.

It is!

> I've included test code and a couple small ts files that illustrate the problem.

Very useful, we are able to reproduce the issue.

> I'm not sure if this is a bug or working as designed

It is a bug.

> but I'd appreciate knowing how to get more fields available from using memory buffers.

We need to fix this bug. We'll check that soon.

**Comment by shpshftr** [comment]
Oh, good. Looks like you got the right person on it!

Thank you so much!

**Comment by shpshftr** [comment]
Any chance this gets fixed soon? 🙏🏻

**Comment by JeromeMartinez** [comment]
@shpshftr true that we are late on many tiny issues... I'll check soon if it is quick to fix.
But if you need to prioritize this issue over other issues, [we provide prioritization services](https://mediaarea.net/Services).

**Comment by shpshftr** [comment]
I did contribute $50 last year of my own money.
It's kind of an old bug. Really old. Ancient.
Maybe it's prorated?😄

Thank you, Jerome!

**Comment by JeromeMartinez** [comment]
[Development snapshots](https://mediaarea.net/download/snapshots/binary/) should be fine now.

**Comment by shpshftr** [comment]
Wow! Thank you so much! That's amazing.
Sorry, was out for Thanksgiving holiday.
I can't wait to give it a try!
