### ISSUE TITLE
TimeCode.cpp(72): fatal  error C1001: Internal compiler error.

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#1621]
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.5.0 Preview 1.0

1>C:\vc17\r6xx\MediaInfoLib\Source\MediaInfo\TimeCode.cpp(72): fatal  error C1001: Internal compiler error.
1>(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>  CL!RaiseException()+0x69
1>  CL!RaiseException()+0x69
1>  CL!InvokeCompilerPassW()+0x8577b
1>  CL!InvokeCompilerPassW()+0xa4503

**Comment by JeromeMartinez** [comment]
I use VS2022 and I don't have this issu. And line 72 is just a basic function.

**Comment by pavel-pimenov** [comment]
VC++ 2022 17.5.0 Preview 1.0 ?

**Comment by JeromeMartinez** [comment]
17.4.1, latest stable release.
