### ISSUE TITLE
Inform Madness

### ISSUE THREAD

**Issue by OdinVex** [MediaArea/MediaInfoLib#1627]
Completely unable to get mediainfo to **** out the Source files for streams in an MPLS. GUI? I have to toggle Details on, then back off for it to show a web version of the output. It shows Source, but no amount of Inform magic gets Source to print out. Just leaving this here.

**Comment by OdinVex** [comment]
Caffeine, hours of attempting to get this... “problem” ...settled, has burnt out any patience.

**Comment by JeromeMartinez** [comment]
Closing as it is actually more grumbling than a a bug report. If you have a technical issue, provide objective information about it, step to reproduce, results, etc.

**Comment by OdinVex** [comment]
Grumbling, sure, but it raises the issue that Source parameter is not easily available from CLI information and that it is either extremely difficult or impossible to determine how to get that information. I ended up just writing a tool to parse mpls files to get what I want.
