### ISSUE TITLE
Is there anyway to set the output Language?

### ISSUE THREAD

**Issue by wishWinds** [MediaArea/MediaInfoLib#1630]
I have notice there is a function
```
MediaInfoLib::MediaInfo::Option_Static("Language", "fr");
```
But, it seems not work!

Do I miss anything?

**Comment by JeromeMartinez** [comment]
For reducing the size of the library, we don't embed all languages in the delivery, you need to load the [language file content](https://github.com/MediaArea/MediaInfo/tree/master/Source/Resource/Plugin/Language) and provide it to the library.
