### ISSUE TITLE
MP3: Encoder name for Helix MP3 encoder with surplus characters

### ISSUE THREAD

**Issue by maikmerten** [MediaArea/MediaInfoLib#1637]
Hello there,

I maintain a version of the Helix MP3 encoder over at https://github.com/maikmerten/hmp3, which includes bug fixes and support for the LAME info tag, as described over at http://gabriel.mp3-tech.org/mp3infotag.html.

The encoder short version string I use is "LAMEH5.21" (the "LAME"-prefix is necessary so legacy applications detect the info frame, the "H" stands for "Helix" and the last four characters denote a version). For CBR files, MediaInfo displays surplus trailing characters behind the "LAMEH5.21" string. I suspect that MediaInfo expects a zero-terminated string, the "Encoder short VersionString", however, is of a fixed length of 9 characters and the following byte encodes the "Info Tag revision + VBR method" field, which can be non-zero. For VBR files, that byte happens to be zero and by chance terminates the string, for CBR a non-zero value is utilized.

I enclosed sample files. The issue first has been discovered over at https://hydrogenaud.io/index.php/topic,123331.msg1020253.html#msg1020253

A location to investigate regarding info tag parsing may be https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Audio/File_Mpega.cpp#L1432

[helix-mp3-info-tag-samples.zip](https://github.com/MediaArea/MediaInfoLib/files/10276853/helix-mp3-info-tag-samples.zip)

**Comment by JeromeMartinez** [comment]
> (the "LAME"-prefix is necessary so legacy applications detect the info frame

I don't remind exactly but we are adding an extra test on the dot in the version number, maybe due to some false positive detection without it. Maybe this extra test is too strong, no strong opinion about it but it would require extra tests on our files.
Anyway, [patch on the way](https://github.com/MediaArea/MediaInfoLib/pull/1638).

**Comment by maikmerten** [comment]
Thanks a lot for your quick response!
