### ISSUE TITLE
HDR Vivid format support patch

### ISSUE THREAD

**Issue by uwaorg** [MediaArea/MediaInfoLib#1649]
HDR Vivid is a new HDR Tone Mapping standard released by UWA (UHD World Association)(currently the official website of UWA is http://theuwa.com)， which is similiar to Dolby Vision/HDR 10+.  Here is the preliminary patch for it. 

HDR Vivid Config box on MP4RA.org is registered ,see https://github.com/mp4ra/mp4ra.github.io/pull/144
[0001-On-branch-uwa.patch](https://github.com/MediaArea/MediaInfoLib/files/10356938/0001-On-branch-uwa.patch)

https://user-images.githubusercontent.com/121996011/210919206-092f1ce9-4069-4d84-affa-7ecf0be5e588.mp4

**Comment by uwaorg** [comment]
After apply above patch and mediainfo CLI show the following HDR format message:
HDR format                               : SMPTE ST 2094 App 4, Version 1, HDRVivid compatible
Obviously , this patch need  to be fixed. as  SmpteSt209440 is for HDR10+.
and we hope the HDR format message for vivid is something as the following:
UWA, HDR Vivid, Version 1,  HDR10 compatible    <-- for HDR Vivid PQ stream
UWA, HDR Vivid, Version 1,  HLG compatible         <-- for HDR Vivid HLG stream

**Comment by JeromeMartinez** [comment]
Could you provide a HDR Vivid HLG stream? So I can check/debug.

**Comment by uwaorg** [comment]
https://user-images.githubusercontent.com/121996011/210971492-9d091a84-1a17-41d5-89d2-07ddb1dc5c90.mp4

This is HDR Vivid hlg stream. (But might not have cuvv box.)

**Comment by JeromeMartinez** [comment]
> HDR Vivid Config box on MP4RA.org is registered ,see https://github.com/mp4ra/mp4ra.github.io/pull/144

Any public spec about cuvv?

**Comment by uwaorg** [comment]
[TUWA 005.1-2022 HDR Video Technology Part 1 Metadata and Tone Mapping_20221231.pdf](https://github.com/MediaArea/MediaInfoLib/files/10359152/TUWA.005.1-2022.HDR.Video.Technology.Part.1.Metadata.and.Tone.Mapping_20221231.pdf)
[HDR Vivid-Part 2-1 System Integration.pdf](https://github.com/MediaArea/MediaInfoLib/files/10359157/HDR.Vivid-Part.2-1.System.Integration.pdf)
[TUWA_005.1-2022_高动态范围(HDR)视频技术_第1部分_元数据及适配.pdf](https://github.com/MediaArea/MediaInfoLib/files/10359165/TUWA_005.1-2022_.HDR._.1._.pdf)

**Comment by uwaorg** [comment]
all these specs can be downloaded from theuwa.com freely.

**Comment by JeromeMartinez** [comment]
In your patch color_saturation_num is forced to 2, but I don't find that in specs (and if I try to follow the specs, parsing fails). Why 2?

**Comment by uwaorg** [comment]
sorry，that line should be deleted. this line is added when I debug this piece of code. I forget to delete it later.

**Comment by JeromeMartinez** [comment]
But color_saturation_num is 6, and there is place only for 2 8-bit color_saturation_enable_gain, so parsing fails.
Buggy stream? issue with specs? or code?

**Comment by uwaorg** [comment]
[File_Hevc.cpp.txt](https://github.com/MediaArea/MediaInfoLib/files/10359535/File_Hevc.cpp.txt)
replace  File_Hevc.cpp using this File_Hevc.cpp.txt file.
I can see the following output:
uwa@DESKTOP-ZhxThinkBook:~/work/MediaInfoPatch/MediaInfo_BUILD_DIR/MediaInfo/Project/GNU/CLI$ ./mediainfo 
https://user-images.githubusercontent.com/121996011/210998704-bd9cec1d-5294-4371-9dea-da47d098e92e.mp4

In func sei_message_user_data_registered_itu_t_t35_26_0004_0005 line 2780,color_saturation_num=2
In func sei_message_user_data_registered_itu_t_t35_26_0004_0005 line 2784,color_saturation_gain=38
In func sei_message_user_data_registered_itu_t_t35_26_0004_0005 line 2784,color_saturation_gain=25
......
HDR format                               : UWA,HDR Vivid, Version 1, HDR10 compatible
.......

this shows the code is ok.
[B.1-03.mp4.metadata.txt](https://github.com/MediaArea/MediaInfoLib/files/10359561/B.1-03.mp4.metadata.txt)
This is the metadata file for HDR Vivid stream B.1-03.mp4

**Comment by uwaorg** [comment]
[B.1-03.mp4_show_frames.txt](https://github.com/MediaArea/MediaInfoLib/files/10359572/B.1-03.mp4_show_frames.txt)
This is part of output "ffprobe -show_frames B.1-03.mp4"
Note: the above ffprobe is compiled with latest ffmpeg code + a patch file as below:
[patch_for_ffmpeg.patch](https://github.com/MediaArea/MediaInfoLib/files/10359614/patch_for_ffmpeg.patch)

**Comment by JeromeMartinez** [comment]
Issue found, due to using "Skip_S1" for 10+ bit skip, it works by luck (I need to add asserts there...) when used by default, not when [trace](https://mediaarea.net/MediaTrace) feature is activated.

Now fine:
```
002211     itu_t_t35_country_code:             38 (0x26)
002212     itu_t_t35_terminal_provider_code:   4 (0x0004)
002214     itu_t_t35_terminal_provider_oriented_code: 5 (0x0005)
002216     system_start_code:                  1 (0x01)
002217     minimum_maxrgb:                     0 (0x000) - (12 bits)
002218     average_maxrgb:                     2607 (0xA2F) - (12 bits)
00221A     variance_maxrgb:                    2975 (0xB9F) - (12 bits)
00221B     maximum_maxrgb:                     4090 (0xFFA) - (12 bits)
00221D     tone_mapping_mode_flag:             Yes
00221D     tone_mapping_param_num:             No
00221D     tone_mapping_param (22 bytes)
00221D      targeted_system_display_maximum_luminance: 2770 (0xAD2) - (12 bits)
00221E      base_enable_flag:                  Yes
00221E      base_param_m_p:                    7372 (0x1CCC) - (14 bits)
002221      base_param_m_m:                    24 (0x18) - (6 bits)
002221      base_param_m_a:                    818 (0x332) - (10 bits)
002222      base_param_m_b:                    0 (0x000) - (10 bits)
002224      base_param_m_n:                    10 (0xA) - (6 bits)
002224      base_param_k1:                     1 (0x1) - (2 bits)
002225      base_param_k2:                     1 (0x1) - (2 bits)
002225      base_param_k2:                     1 (0x1) - (4 bits)
002225      base_param_Delta_enable_mode:      6 (0x6) - (3 bits)
002226      base_param_Delta:                  6 (0x6) - (7 bits)
002226      3Spline_enable_flag:               Yes
002227      3Spline_num:                       Yes
002227      3Spline (6 bytes)
002227       3Spline_TH_mode:                  0 (0x0) - (2 bits)
002228       3Spline_TH_enable_MB:             236 (0xEC) - (8 bits)
002228       3Spline_TH:                       40 (0x028) - (12 bits)
002229       3Spline_TH_Delta1:                613 (0x265) - (10 bits)
00222B       3Spline_TH_Delta2:                777 (0x309) - (10 bits)
00222D       3Spline_enable_Strength:          158 (0x9E) - (8 bits)
00222D      3Spline (6 bytes)
00222D       3Spline_TH_mode:                  2 (0x2) - (2 bits)
00222E       3Spline_TH_enable_MB:             0 (0x0) - (8 bits)
00222E       3Spline_TH:                       1556 (0x614) - (12 bits)
002230       3Spline_TH_Delta1:                749 (0x2ED) - (10 bits)
002231       3Spline_TH_Delta2:                749 (0x2ED) - (10 bits)
002233       3Spline_enable_Strength:          157 (0x9D) - (8 bits)
002233     color_saturation_mapping_flag:      Yes
002233     color_saturation_enable_num:        2 (0x2) - (3 bits)
002235     color_saturation_enable_gain:       38 (0x26) - (8 bits)
002236     color_saturation_enable_gain:       24 (0x18) - (8 bits)
```

Will provide a modified/adapted version of a patch soon.

Question: wouldn't targeted_system_display_maximum_luminance interesting to display in MediaInfo report?

**Comment by uwaorg** [comment]
Great!
Yes, targeted_system_display_maximum_luminance is a important data to report. 
we are not familiar with mediainfo code and how to decide what to show。
So need your expertise to decide what to do. 
Thank you very much!

**Comment by JeromeMartinez** [comment]
> we are not familiar with mediainfo code and how to decide what to show。

Balance between too much info and pertinence for users. targeted_system_display_maximum_luminance seems similar to Max Mastering display luminance in SMPTE ST 2086, so I would add it there.
Something you think is relevant for most HDR users and/or similar to current MediaInfo fields?

**Comment by uwaorg** [comment]
ok, I will check with HDR Vivid core developers and tell you next week,

**Comment by JeromeMartinez** [comment]
Updated patch is at https://github.com/MediaArea/MediaInfoLib/pull/1653.
It requires master branch of MediaInfoLib because there was an update about how to handle several HDR formats in HEVC.
I added a patch for supporting the MP4 box so HDR Vivid is displayed also when very fast parse speed is request ( " --ParseSpeed=-1", it parses no video frame, only the MP4 header).

Output:
```
HDR format                               : HDR Vivid, Version 1
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : max: 2770 cd/m2
```

Mastering display color primaries is from SMPTE ST 2084 and kept even if HDR Vivid is displayed as it seems that there is no such item in HDR Vivid (does it make sense?), Mastering display luminance is from HDR Vivid replacing SMPTE ST 2084 values.

**Comment by uwaorg** [comment]
Could you please modify the code to display  "Version 1" as "Version 1.0"?  and also, for PQ stream, display additional “HDR10 Compatible” , and for HLG stream, display addtional "HLG Compatible"。
i.e,  for HLG stream, display as below:
HDR format                               : HDR Vivid, Version 1, HLG Compatible
for PQ stream, display as below:
HDR format                               : HDR Vivid, Version 1,HDR10 Compatible

This request is from HDR Vivid core developer.
Thank you very much!

**Comment by uwaorg** [comment]
Also, 2 additional problems:
I. The first is: the Mastering display luminace is wrong 
Mastering display luminance              : max: 2770 cd/m2
This 2770 is for targeted_system_display_maximum_luminance in Vivid and its unit is not cd/m2.
see T/UWA 005.1 -2022, section 7.4.8 
-------------------------------------
7.4.8 targeted_system_display_maximum_luminance_pq[i][w]
A 12-bit unsigned integer that specifies the maximum luminance of the metadata reference display. targeted_system_display_maximum_luminance is equal to targeted_system_display_maximum_luminance_pq[i][w]/4095 and is in increments of 1.0/4095 within a range of 0.0 to 1.0. When targeted_system_display_maximum_luminance_pq[i][w] is equal to 2080, it indicates that the current tone mapping curve parameters are intended for SDR and is used only when SDR signals are output; and when targeted_system_display_maximum_luminance_pq[i][w] is not equal to 2080, it indicates that the current tone mapping curve parameters are intended for HDR.
-----------------------------

II.the Second is:
the following is doubtful:
Mastering display color primaries        : Display P3

where is this parameters comes from?

**Comment by JeromeMartinez** [comment]
> "Version 1.0"

How to detect the change of minor version? In other words, how to detect the a content is not version 1 but not 1.0?
I see only system_start_code in HEVC and cuva_version_map in MP4 and use that, it seems to provide only a major version number.

From specs: "For instance, if cuva_version_map is 0x0009, the ES contains versions 4 and 1 (binary number 1001 being 9 in decimal)." Only version, no minor version.

> for PQ stream, display additional “HDR10 Compatible”

The idea behind “HDR10 Compatible” is to show SMPTE ST 2084 stream with all HDR10 metadata.
It is not displayed when there is a better HDR level, e.g. for HDR10+:

```
SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
```

HDR10 disappears.
Additionally, we don't see HDR10 stuff in the Vivid HDR bitstream itself (no flag about it), it seems neutral. What in the Vivid HDR bitstream makes it HDR compatible?

Note that we see well the SMPTE ST 2084 stuff, it is just hidden by default.
With command line (planned to be added at some point in GUI) option " --LegacyStreamDisplay"

We have :

```
HDR Vivid, Version 1 / SMPTE ST 2086, HDR10 compatible
```

similar to the HDR10+ info:

```
SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible / SMPTE ST 2086, HDR10 compatible
```

Actually our policy is for the moment to show the highest format available, same for e.g. count of channels for Dolby Atmos, we don't show anymore the count of channels for non Atmos aware decoders (but they are displayed with the " --LegacyStreamDisplay" option)

> and for HLG stream, display addtional "HLG Compatible"

We don't find anything related to HLG in the Vivid HDR bitstream, HLG is indicated in its own field 
```
Transfer characteristics                 : HLG
```
(already before the patch) because it is taken from HEVC standard and not from Vivid HDR bitstream.

If the Vivid HDR bitstream has something related to HLG, please indicate where.

> This 2770 is for targeted_system_display_maximum_luminance in Vivid and its unit is not cd/m2

What is the actual unit?
If I use targeted_system_display_maximum_luminance  divided by 4095, it seems a very low value.
We could also just ignore this value if not relevant to display, and keep SMPTE ST 2084 values.

> Mastering display color primaries : Display P3
where is this parameters comes from?

See [my comment](https://github.com/MediaArea/MediaInfoLib/issues/1649#issuecomment-1374928872), Mastering display color primaries is from SMPTE ST 2084 and kept even if HDR Vivid is displayed as it seems that there is no such item in HDR Vivid (does it make sense?). Is there an equivalent in the Vivid HDR bitstream?

**Comment by uwaorg** [comment]
> > This 2770 is for targeted_system_display_maximum_luminance in Vivid and its unit is not cd/m2
> 
> What is the actual unit? If I use targeted_system_display_maximum_luminance divided by 4095, it seems a very low value. We could also just ignore this value if not relevant to display, and keep SMPTE ST 2084 values.
Yes, I think we can ignore  targeted_system_display_maximum_luminance because this is from metadata in each frame, and might be different, in some frames may not have it at all.

**Comment by uwaorg** [comment]
> > "Version 1.0"
> 
> How to detect the change of minor version? In other words, how to detect the a content is not version 1 but not 1.0? I see only system_start_code in HEVC and cuva_version_map in MP4 and use that, it seems to provide only a major version number.

Yes. I think the version info in spec and cuvv box has some issue. the 005.2-1 table 5, the version info is 1.0 <==>0x0005, 2.0 <==> 0x0006, etc. but in cuva_version_map, no minor version info.  
for the time being, just leave it as 1. thank you!

**Comment by JeromeMartinez** [comment]
> Yes, I think we can ignore targeted_system_display_maximum_luminance because this is from metadata in each frame, and might be different, in some frames may not have it at all.

I removed the targeted_system_display_maximum_luminance part so the SMPTE ST 2084 values are kept (as it was before the Vivid patch) now:

```
HDR format                               : HDR Vivid, Version 1
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0500 cd/m2, max: 4000 cd/m2
```

Will merge https://github.com/MediaArea/MediaInfoLib/pull/1653 soon.

**Comment by uwaorg** [comment]
> > Yes, I think we can ignore targeted_system_display_maximum_luminance because this is from metadata in each frame, and might be different, in some frames may not have it at all.
> 
> I removed the targeted_system_display_maximum_luminance part so the SMPTE ST 2084 values are kept (as it was before the Vivid patch) now:
> 
> ```
> HDR format                               : HDR Vivid, Version 1
> Color range                              : Limited
> Color primaries                          : BT.2020
> Transfer characteristics                 : PQ
> Matrix coefficients                      : BT.2020 non-constant
> Mastering display color primaries        : Display P3
> Mastering display luminance              : min: 0.0500 cd/m2, max: 4000 cd/m2
> ```
> 
> Will merge #1653 soon.

great! thank you for your work. Please let me know if you need more input from us!
