### ISSUE TITLE
timecodexml wishes

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaInfoLib#1663]
- change top level from `timecode_streams` to `MediaTime`?
- add sublevel with `<media @ref...` as in other formats
- add `creatingLibrary` element as in other formats

I'm also wondering about how to later mux this back into other formats. Should we store the initial pts of the initial timecode, so we can align things. I imagine in some cases the first timecode value may not be exactly at 0.

**Comment by JeromeMartinez** [comment]
> change top level from timecode_streams to MediaTime?

It is focused on timecodes and not about times, so MediaTimecode?

> Should we store the initial pts of the initial timecode,

I can add a `pts` attribute (float value, in seconds?). Would be always 0 for MXF as there is not other possibility.

**Comment by dericed** [comment]
Thanks

**Comment by dericed** [comment]
actually i see some xml has `creatingLibrary/creatingApplication` and some has 'creator/[program|version|library]'. Have a preference?

**Comment by dericed** [comment]
Could you add in `media/@format` as well?

**Comment by JeromeMartinez** [comment]
`creatingLibrary` as it is what we have in MIXMLv2.

**Comment by JeromeMartinez** [comment]
> media/@size

At the end we have the MI report :-p.

I am fine for `ref` (for getting the analyzed resource) and `format` (for knowing more about the timecode formats), more reluctant about `size` because it is not related to timecodes.

**Comment by dericed** [comment]
Helpful to add an `@n` attribute to tc as a counter?

**Comment by JeromeMartinez** [comment]
> Helpful to add an @n attribute to tc as a counter?

No extra info and increase output size.

**Comment by dericed** [comment]
ok about `@n`. Could you add a namespace to the root? `<MediaTimecode xmlns="https://mediaarea.net/mediatimecode">`?

**Comment by dericed** [comment]
for bg fp bgf attributes, do these exist at the `tc` level is not matching the one at the stream level?

**Comment by JeromeMartinez** [comment]
> for bg fp bgf attributes, do these exist at the tc level is not matching the one at the stream level?

Right. stream level contains defaults, overwritten by tc level if exists.

**Comment by dericed** [comment]
For `mediainfo --ParseSpeed=1 Output=TimecodeXML file.mxf`, if TimecodeXML requires ParseSpeed=1, could ParseSpeed=1 be default if that output is selected?

**Comment by JeromeMartinez** [comment]
> For mediainfo --ParseSpeed=1 Output=TimecodeXML file.mxf, if TimecodeXML requires ParseSpeed=1, could ParseSpeed=1 be default if that output is selected?

Not required, but you get partial info without it. May be useful fro quick check without parsing the file.
But it will create user mistake if not default, so I am fine for default full parsing and option for quick.

Note: I forgot that, please add `full` attribute, it is added with value `0` if not full parsing, in order to catch partial parsing.

**Comment by dericed** [comment]
where would the `full` attribute go? `media`? It is binary, yes?

**Comment by JeromeMartinez** [comment]
> where would the full attribute go? media? It is binary, yes?

Yes and yes.
