### ISSUE TITLE
Start timecode not found in particular ProRes mov in 22.12

### ISSUE THREAD

**Issue by mentaur** [MediaArea/MediaInfoLib#1681]
I just wanted to report what I believe is a regression since updating to 22.12. The file (supplied by email) has a timecode track and a start timecode of 01:00:00;00 but the 22.12 version no longer finds this. I also checked the most recent snapshot build and I don’t believe that worked either.

I don’t think there is anything too funny about the file, though my engineer reports:
_There only oddity is that the stsz (sample size) table is 32112 bytes even though it only contains a single entry and similarly the co64 (chunk offset) table is 4608 bytes but only a single entry. Timecode tracks only ever have a single entry for the start timecode frame count. They are oversized but do not appear to be malformed in any way._

Thanks
Nick

**Comment by JeromeMartinez** [comment]
Regression confirmed.
It is due to the weird (but conforming) stsz, usually 1 sample in stsz is stored differently and we didn't catch an issue in our code in the case of your file and time code.
In next [snapshots](https://mediaarea.net/download/snapshots/binary/).
