### ISSUE TITLE
Chinese (Simplified) is displayed as Chinese (Simplied)

### ISSUE THREAD

**Issue by vevv** [MediaArea/MediaInfoLib#1683]
Seems like a typo got through and no one's reported it yet.
https://github.com/MediaArea/MediaInfoLib/blob/master/Source/Resource/Text/Language/DefaultLanguage.csv#L923

**Comment by JeromeMartinez** [comment]
Oops... [Fixed](https://github.com/MediaArea/MediaInfoLib/pull/1684).
In next [snapshots](https://mediaarea.net/download/snapshots/binary/) and release.
