### ISSUE TITLE
mediainfo lib hangs on a movie

### ISSUE THREAD

**Issue by esok** [MediaArea/MediaInfoLib#1695]
I have a movie that causes mediainfo to hang. This is using the latest version 22.12. It did not occur on 22.09 or 20.03. I verified that the hang occurs on MacOS and on Rocky 8 Linux. The video is located here: https://svs.gsfc.nasa.gov/hyperwall/download/events/2023-aaas/dominic_benford_roman/slide_14_Andromeda_with_Roman.mp4

**Comment by JeromeMartinez** [comment]
We fixed a couple of hangs issues in the last days with similar files, please test the latest [dev snapshots](https://mediaarea.net/download/snapshots/binary/) (for Linux you need to update libmediainfo0) and confirm if it is still there or not.

**Comment by esok** [comment]
Yes, the latest dev build works correctly. Thank you.
