### ISSUE TITLE
DAR/SAR and conflict with ffprobe/ffmpeg

### ISSUE THREAD

**Issue by jimlynnjulian** [MediaArea/MediaInfoLib#1696]
Recently, I had occasion to need the SAR/DAR of a video. To my surprise, I found a conflict between MediaInfo and ffprobe/ffmpeg. Which is correct? Is VLC the problem?

Example:
ffprobe "Hallelujah (1929)._edit.mp4"  reports: 
680x1000 [SAR 1:1  DAR  17:25], while
MediaInfo has the DAR as 4:3 (and the movie is displayed as 4:3 in VLC).
Width    : 640 pixels
Height      : 480 pixels
Display aspect ratio        : 4:3

**Comment by JeromeMartinez** [comment]
We are confident that MediaInfo and VLC are right, but without a file we can not explain the source of the computing (or see our mistake), please share a sample file.
If it can't be shared publicly, send a link to info@mediaarea.net.

**Comment by jimlynnjulian** [comment]
This Dropbox link should work. Let me know if there is a problem.
https://www.dropbox.com/sh/flyrmo7k0jqf4s8/AACacP16QS1qgUHE8-Xl16M8a?dl=0

**Comment by JeromeMartinez** [comment]
All "normal", classic 640x480 4:3 DAR
My FFmpeg says same.

```
ffmpeg -version
ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
ffmpeg -i Hallelujah\ \(1929\)._edit.mp4
 640x480, 792 kb/s, SAR 1:1 DAR 4:3
```

Old FFmpeg?
Closing as there seems that there is no conflict with up to date FFmpeg.

**Comment by jimlynnjulian** [comment]
just downloaded and installed : ffmpeg version N-109937-g05438db024-20230228 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.90_cf9beb1)

No change.
Maybe the fact that you're using Linux and I'm using Win11x64, is the difference.
I'm using thhe version at : https://github.com/BtbN/FFmpeg-Builds/releases
Thanks for your time.
Jim J.

**Comment by JeromeMartinez** [comment]
Tested with https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
```
.\ffmpeg.exe -i '.\Hallelujah (1929)._edit.mp4'
ffmpeg version N-109937-g05438db024-20230228 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.90_cf9beb1)
[...]
 640x480, 792 kb/s, SAR 1:1 DAR 4:3
```

Still 4:3, and 100% in sync with MediaInfo.

don't you mix up with the attached pic 680x1000, 3rd FFmpeg stream (video stream is the first one)? It is the attached picture, MediaInfo doesn't decode it (yet) and VLC doesn't play it, so you can't compare (it is 17:25 DAR vs no information). The DAR is correct (SAR is 1:1 in JPEG), see the picture (manually extracted from your file), it is definitely not a 4:3 picture:
![iTunMOVI and attached pic - Hallelujah (1929) _edit mp4](https://user-images.githubusercontent.com/1641638/221946473-ea39839a-9e9d-4ed7-bc16-042b18f74a25.jpg)

**Comment by jimlynnjulian** [comment]
Come to think of it, I believe this version of the file contains metadata inserted by a program I use, MetaX, which imports tag data from the web and writes metadata tags. There is an option for a scrrenshot/poster image, but I didn't check that box. 
However, that is probably what threw ffprobe off. Thanks for pointing that out.
I'm going to remove the metadata and retry. I'm sure that will work.
Thanks again,
Jim J
