### ISSUE TITLE
H264/TS duration/frame count incorrect

### ISSUE THREAD

**Issue by glazarov-uk** [MediaArea/MediaInfoLib#1701]
In one of the cases, it is believed the tool is not reading a TS file correctly and reports an extra frame (40 ms).  

-	Expected video duration 00:00:30.000 (750 frames)
-	MediaInfo reported video duration 00:00:30.040 (751 frames)

MediaInfo reading compared to other software such as ffprobe, Manzanita, Harmonic AV Codec Analyzer, Switch player, etc.

A file in question has been sent privately.

**Comment by JeromeMartinez** [comment]
Issue confirmed to be in MediaInfo, issue with computing of PTS of last frame.

**Comment by JeromeMartinez** [comment]
@glazarov-uk this [Win/Mac snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo/20230303/) and this [Linux snapshot](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20230303/) has the fix and is fine for production.
