### ISSUE TITLE
FLAC has strange sample count in Advanced mode

### ISSUE THREAD

**Issue by ValZapod** [MediaArea/MediaInfoLib#1709]
[dafa.zip](https://github.com/MediaArea/MediaInfoLib/files/10946667/dafa.zip)

So this file has in STREAMINFO 

Samples: 1875 (0x000000753) - (36 bits)

yet in Advanced mode:

![image](https://user-images.githubusercontent.com/31514790/224440354-23ec51c4-ecc3-4220-bc30-fb9ab0676c0e.png)

File created with ffmpeg but after reencoded with ./flac same happens.

**Comment by JeromeMartinez** [comment]
We have some precision issues, right... This one is easy to fix so fixed, at long term we need to handle intermediate storage differently, planned but no ETA.
