### ISSUE TITLE
Support for reference files in AWS S3

### ISSUE THREAD

**Issue by daniel-pebble** [MediaArea/MediaInfoLib#1721]
I have the requirement to scan mov reference files stored in S3, I've created a resigned URL for the mov file however, media info fails to read the essence files.  Of course this is because the presigned file is for the reference file.
Is there any other method for accessing files stored in S3 without using presigned URL?  If it is possible to provide access key/secret?

**Comment by JeromeMartinez** [comment]
> If it is possible to provide access key/secret?

URI with login/password:
`mediainfo https://AWSAccessKeyId:AWSSecretAccessKey@URL`

But IIRC we don't forward (yet) the login/password to the referenced files parser, only to the master file parser, so it will also fail.
Nothing big to implement, just not done, [let us know](https://mediaarea.net/Contact) if you are interested in sponsoring the prioritization of this issue.

**Comment by JeromeMartinez** [comment]
> It seems to be parsing the essence files however I am getting this error at the top "HTTP server doesn't seem to support byte ranges. Cannot resume"

Separate issue because it is not related to reference files (same error with directly the WAV file).
"byte ranges" is used for seeking in the file and it used to work with S3, we can reproduce and we are debugging for seeing if it is a S3 limitation now or if we can do something about that.

**Comment by JeromeMartinez** [comment]
@daniel-pebble the error seems to come from the old libcurl (the library we use for accessing web links) we kept on Windows, as these errors are not seen on Linux.
Please try on a Linux, and if it is OK on Linux it can be used in production, it is just that our libcurl on Windows is outdated and we'll update it.

**Comment by daniel-pebble** [comment]
Yeah I can confirm it looks good in linux.  We plan to use this in a linux environment so I think this will work fine. Thanks
![image](https://user-images.githubusercontent.com/47243318/230442101-4f576aa1-79fd-4c69-96ec-4997ac7852fa.png)
