### ISSUE TITLE
MediaInfo_Get omits decimal point on call for duration

### ISSUE THREAD

**Issue by F4n4t** [MediaArea/MediaInfoLib#1729]
First of all, I would like to thank you for this great library and your continued commitment to this project.

Recently I started to develop a small wrapper around it using cgo, and while testing some of the function calls I discovered that  whenever I want to get the duration with `MediaInfo_Get()`,  the decimal point gets removed, which results in a too long playtime.

For example this is the the duration part from the JSON output, which I retrieved with the Inform() call:
`"Duration": "6067.083"`

and here is the string MediaInfo_Get() returns: `"6067083"`

Edit:
Here is a test file with an example
[test.zip](https://github.com/MediaArea/MediaInfoLib/files/11152282/test.zip)

Edit2:
Ok my bad, I just realized that the returned measure is ms not seconds :D

**Comment by JeromeMartinez** [comment]
> Ok my bad, I just realized that the returned measure is ms not seconds :D

Right. Due to historical reasons the Get() API has milliseconds, and we fixed the issue when we developed the XML and JSON outputs.
