### ISSUE TITLE
Incorrect color range for Webm (VP9, pc) file.

### ISSUE THREAD

**Issue by KulakovAD** [MediaArea/MediaInfoLib#1737]
Captured sample video from PS5 - [t.webm](https://user-images.githubusercontent.com/53341050/232088998-2a3bec18-b6e2-4c4f-b104-3e9d94790adf.webm)

MediaInfo returns [mediainfo.txt](https://github.com/MediaArea/MediaInfoLib/files/11234563/mediainfo.txt):
> Color range                 : Limited

But this file actually is full range (see [ffprobe.txt](https://github.com/MediaArea/MediaInfoLib/files/11234568/ffprobe.txt)):
> Stream #0:0: Video: vp9 (Profile 0), yuv420p(**pc**, bt709)

PC = Full range, TV = Limited range.

MediaInfo should return **Full** for this file.

**Comment by JeromeMartinez** [comment]
> MediaInfo should return Full for this file.

Yes and no

Analysis of Matroska part:
```
000163      Range - 1 (0x1) - Limited (4 bytes)
000163       Header (3 bytes)
000163        Name:                            5561 (0x15B9)
000165        Size:                            1 (0x01)
000166       Data:                             1 (0x01)
```

Value 1 is "Limited" ([source](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/ebml_matroska.xml#L792)).

Analysis of VP9 part:
Unfortunately currently MediaInfo doesn't parse VP9, but quick manual check based on [specs](http://downloads.webmproject.org/docs/vp9/vp9-bitstream_superframe-and-uncompressed-header_v1.0.pdf)) (look for `bitdepth_colorspace_sampling`) indicates that color space and range comes just after SYNC_CODE 0x498342, hex dump is 0x50 = 0b0101000 so 0b010 for color space (BT.709) then 0b1 for range which is... full range.

So mismatch in this file between container and bitstream.

We should actually show the incoherency. but for that we need to implement a VP9 parser first.

In the meantime you should report a bug to the muxer developer.

**Comment by KulakovAD** [comment]
Thank you very much for taking look and explaining.

In the meantime I will try to find a way to file bug report to Sony (probably they set incorrect flag when creating capture file)

**Comment by JeromeMartinez** [comment]
> I will try to find a way to file bug report to Sony

Sony? The muxing app is "mkvmux-1.0.0", [10+ year old](https://forum.doom9.org/archive/index.php/t-162671.html), I doubt that Sony uses that.

**Comment by JeromeMartinez** [comment]
With next release (and [developments snapshots](), build launched):

```
Color range                              : Limited
colour_range_Original                    : Full
```

First line is from Matroska, second line from VP9.

**Comment by KulakovAD** [comment]
> Sony? The muxing app is "mkvmux-1.0.0", [10+ year old](https://forum.doom9.org/archive/index.php/t-162671.html), I doubt that Sony uses that.

This video created using Sony PlayStation 5 built-in video capture without any modification on top.
I reported this issue to Sony via PlayStation support, hope they will fix it one day.


Thank you for supporting VP9 and helping with investigating.

**Comment by ValeZAA** [comment]
Can you BTW record some moment that has pure blacks? Because with your sample it can be limited or full range, it is hard to tell.
