### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ololoe** [MediaArea/MediaInfoLib#1743]
How to upload a file? File too big.

**Comment by JeromeMartinez** [comment]
There are some file sharing websites like https://gofile.io which accept big files, or we can provide a private FTP server access.
If the link can not be shared publicly, drop me an email.

**Comment by ololoe** [comment]
https://gofile.io/d/KgjrL2

Floating point division by zero.

**Comment by pavel-pimenov** [comment]
1.ts = https://gofile.io/d/KgjrL2

<pre>

cat Dockerfile
FROM almalinux

RUN yum install -y git automake autoconf libtool pkgconfig make gcc gcc-c++ zlib-devel wget

RUN git clone https://github.com/MediaArea/ZenLib.git \
    && cd ZenLib/Project/GNU/Library \
    && ./autogen.sh \
    && ./configure --enable-static --enable-debug \
    && make

RUN git clone https://github.com/MediaArea/MediaInfoLib.git \
    && cd MediaInfoLib/Project/GNU/Library \
    && ./autogen.sh \
    && ./configure --enable-static --enable-staticlibs --enable-debug\
    && make

RUN git clone https://github.com/MediaArea/MediaInfo.git \
    && cd MediaInfo/Project/GNU/CLI \
    && ./autogen.sh \
    && ./configure --enable-staticlibs --enable-debug \
    && make \
    && make install

WORKDIR /MediaInfo

RUN ls

RUN mediainfo  --Help

COPY 1.ts 1.ts

RUN ls

RUN yum install -y valgrind

RUN valgrind --leak-check=full --show-leak-kinds=all mediainfo /MediaInfo/1.ts




./Dockerfile-create-image
Sending build context to Docker daemon  31.72MB
Step 1/12 : FROM almalinux
 ---> f4b24db3d26d
Step 2/12 : RUN yum install -y git automake autoconf libtool pkgconfig make gcc gcc-c++ zlib-devel wget
 ---> Using cache
 ---> f485a118435d
Step 3/12 : RUN git clone https://github.com/MediaArea/ZenLib.git     && cd ZenLib/Project/GNU/Library     && ./autogen.sh     && ./configure --enable-static --enable-debug     && make
 ---> Using cache
 ---> a1f099a3b03e
Step 4/12 : RUN git clone https://github.com/MediaArea/MediaInfoLib.git     && cd MediaInfoLib/Project/GNU/Library     && ./autogen.sh     && ./configure --enable-static --enable-staticlibs --enable-debug    && make
 ---> Using cache
 ---> ebfd67b1bc9b
Step 5/12 : RUN git clone https://github.com/MediaArea/MediaInfo.git     && cd MediaInfo/Project/GNU/CLI     && ./autogen.sh     && ./configure --enable-staticlibs --enable-debug     && make     && make install
 ---> Using cache
 ---> 35cbbb026a30
Step 6/12 : WORKDIR /MediaInfo
 ---> Using cache
 ---> deaee3271778
Step 7/12 : RUN ls
 ---> Using cache
 ---> 3493b8040301
Step 8/12 : RUN mediainfo  --Help
 ---> Using cache
 ---> 2a4529c4161c
Step 9/12 : COPY 1.ts 1.ts
 ---> Using cache
 ---> 2d998f47471f
Step 10/12 : RUN ls
 ---> Using cache
 ---> 170040c11e88
Step 11/12 : RUN yum install -y valgrind
 ---> Using cache
 ---> 690e17a6020a
Step 12/12 : RUN valgrind --leak-check=full --show-leak-kinds=all mediainfo /MediaInfo/1.ts
 ---> Running in 8087beaaa942
==1== Memcheck, a memory error detector
==1== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==1== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==1== Command: mediainfo /MediaInfo/1.ts
==1==
General
ID                                       : 1 (0x1)
Complete name                            : /MediaInfo/1.ts
Format                                   : MPEG-TS
File size                                : 30.2 MiB
Duration                                 : 9 s 960 ms
Overall bit rate mode                    : Variable
Overall bit rate                         : 25.4 Mb/s
Frame rate                               : 25.000 FPS

Video
ID                                       : 211 (0xD3)
Menu ID                                  : 1 (0x1)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5@Main
Codec ID                                 : 36
Duration                                 : 10 s 0 ms
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits

Audio
ID                                       : 221 (0xDD)
Menu ID                                  : 1 (0x1)
Format                                   : AAC LC SBR PS
Format/Info                              : Advanced Audio Codec Low Complexity with Spectral Band Replication and Parametric Stereo
Commercial name                          : HE-AACv2
Format version                           : Version 4
Format settings                          : Implicit
Muxing mode                              : ADTS
Codec ID                                 : 15-2
Duration                                 : 10 s 26 ms
Channel(s)                               : 2 channels
Channel layout                           : M
Sampling rate                            : 48.0 kHz
Frame rate                               : 23.438 FPS (2048 SPF)
Compression mode                         : Lossy
Delay relative to video                  : -38 ms
Language                                 : Russian

Menu
ID                                       : 4095 (0xFFF)
Menu ID                                  : 1 (0x1)
Format                                   : HEVC / AAC
Duration                                 : 9 s 960 ms
List                                     : 211 (0xD3) (HEVC) / 221 (0xDD) (AAC, Russian)
Language                                 :  / Russian
Service name                             : 19262
Service provider                         : TightVideo
Service type                             : digital television


==1==
==1== HEAP SUMMARY:
==1==     in use at exit: 0 bytes in 0 blocks
==1==   total heap usage: 242,498 allocs, 242,498 frees, 59,222,196 bytes allocated
==1==
==1== All heap blocks were freed -- no leaks are possible
==1==
==1== For lists of detected and suppressed errors, rerun with: -s
==1== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Removing intermediate container 8087beaaa942
 ---> fc9dd8f4c580
Successfully built fc9dd8f4c580

<\pre>

**Comment by JeromeMartinez** [comment]
@pavel-pimenov  This is surprising but actually there is really a crash, in the GUI, not in the CLI, on Windows.
This may be due to a specific compiler config (the GUI is compiled with another compiler) which flag a division by 0 as a failure (this is not mandatory for float, result can be also just `inf`).

If you know how to activate a crash on a division by zero with Valgrind or Visual Studio, I am interested, it would help to catch the source of the division by 0.

**Comment by JeromeMartinez** [comment]
(Note: the Visual Studio DLL build in debug mode has also no crash, so right now playing with Visual Studio options for seeing which option triggers the crash)

**Comment by JeromeMartinez** [comment]
The option to change for avoiding a crash is [`/arch`](https://learn.microsoft.com/en-us/cpp/build/reference/arch-x86?view=msvc-170), from "Not set" to "/arch:IA32" ("legacy 32-bit x86 instruction set without any vector operations and using x87 for floating-point calculations"), **but** there is no crash if I run that with the command line. So impossible to have automatic catch of the crash, looks like that we need to remove a piece of code, compile, test. Boring... @pavel-pimenov if you have another solution for catching the place of the crash, I am very interested in it!

**Comment by pavel-pimenov** [comment]
C++Builder
![image](https://user-images.githubusercontent.com/920705/233566443-81452842-3ba3-4635-b204-55643072cd15.png)

**Comment by JeromeMartinez** [comment]
I need to refresh my C++ Builder setup, it was not building out of the box 😅. @pavel-pimenov Thanks.
(and stupid mistake)
