### ISSUE TITLE
Access Violation in module 'MediaInfo_i386.dll' when loading a Matroska file with HDR10+ metadata

### ISSUE THREAD

**Issue by jamrial** [MediaArea/MediaInfoLib#1756]
Tested on Windows 11 with MediaInfo GUI 23.04. The application doesn't crash after the error popups, but the file is not loaded.

Sample to reproduce:
[hdr10_plus_vp9_sample.webm](https://user-images.githubusercontent.com/2442845/236365801-b8374e42-d006-4749-8961-7175e709ab07.webm)

**Comment by JeromeMartinez** [comment]
Ugly mistake :(.
Fixed, [development snapshot](https://old.mediaarea.net/download/snapshots/binary/mediainfo-gui/20230505-2/MediaInfo_GUI_23.04.20230505_Windows.exe).

**Comment by jamrial** [comment]
Can confirm it works now.
