### ISSUE TITLE
Mpd : media info does not find files with non ascii chars in name

### ISSUE THREAD

**Issue by Valgil** [MediaArea/MediaInfoLib#1759]
Hello, 

Before all thanks for the great media info tool :) 

I am running an issue while trying to run the mediaInfo tool on an mpd file. This file contains several  "BaseURL" tags which are set to the file name of the different streams (video, audio). 

In this case, the file names contain a "û" char but it's the same behavior with é, à or other characters of the sort. 

The filename in the file system is : 
20040807185900154_JT 1900 7 août 2004_rendered.h264.160x88.10.2kbps.mp4

In the mpd file, the <BaseURL> tag of the file name looks like such: 
<BaseURL>20040807185900154_JT%201900%207%20ao%C3%BBt%202004_rendered.h264.160x88.10.2kbps.mp4</BaseURL>

When I run the media tool on the mpd, it says "Source_Info": "Missing" and we have very limited info (we don't have the format info for example )

If in the mpd file,  I modify the filenames in the <BaseURL> tags within the mpd and change the "%C3%BB" to "û" as such: 
from

<BaseURL>20040807185900154_JT%201900%207%20ao%C3%BBt%202004_rendered.h264.160x88.10.2kbps.mp4</BaseURL>

To 

<BaseURL>20040807185900154_JT%201900%207%20août%202004_rendered.h264.160x88.10.2kbps.mp4</BaseURL>

Then I have the complete info from mediaInfo. Everything is great :)

Is there some way to make sure media info succeeds in finding the files without having to tweak the mpd file? 

Your help is greatly appreciated.

**Comment by JeromeMartinez** [comment]
I tested with:

```
$ more output.mpd
<?xml version="1.0"?>
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" mediaPresentationDuration="PT19.052S" minBufferTime="PT9.98S" profiles="urn:m
peg:dash:profile:isoff-live:2011" type="static">
  <Period>
    <AdaptationSet maxHeight="476" maxWidth="854" mimeType="video/mp4" minHeight="476" minWidth="854" segmentAlignment="
true" startWithSAP="1">
      <SegmentTemplate duration="9877" initialization="$RepresentationID$/août 2004_rendered.h264.160x88.10.2kbps.mp4" m
edia="$RepresentationID$/août 2004_rendered.h264.160x88.10.2kbps-$Number$.m4f" startNumber="1" timescale="1000"/>
      <Representation bandwidth="249374" codecs="avc1.42C01F" frameRate="30000/1001" height="476" id="vidéo/1" scanType=
"progressive" width="854"/>
    </AdaptationSet>
  </Period>
</MPD>
$ mediainfo output.mpd
General
Complete name                            : output.mpd
Format                                   : DASH MPD
File size                                : 304 KiB
Duration                                 : 9 s 977 ms
Overall bit rate                         : 250 kb/s
Frame rate                               : 29.970 FPS

Video
ID                                       : 0-1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : Constrained Baseline@L3.1
Format settings                          : 1 Ref Frames
Format settings, CABAC                   : No
Format settings, Reference frames        : 1 frame
Muxing mode                              : MPEG-4
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 9 s 977 ms
Bit rate                                 : 247 kb/s
Width                                    : 854 pixels
Height                                   : 476 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.020
Stream size                              : 301 KiB (99%)
Writing library                          : Zencoder Video Encoding System
Source                                   : vidéo/1/août 2004_rendered.h264.160x88.10.2kbps.mp4
Codec configuration box                  : avcC
```

Same on Windows.
Note: XML file is encoded in UTF-8.

Please provide a way to reproduce the issue on our side.

**Comment by Valgil** [comment]
Hello Jérôme, 
Thank you for your response! 

I just uploaded a zip with an example, 
The original mpd is the one with not working. It has all "funky chars" replaced by corresponding ascii code. 
I made a copy of the mpd for the sake of the example. The original contains %C3%BB as a replacement of û, when I right-click on this file to get the media info, then I get a "source_info: missing"

`{
"creatingLibrary": {
"name": "MediaInfoLib",
"version": "23.03",
"url": "https://mediaarea.net/MediaInfo"
},
"media": {
"@ref": "C:\\Users\\vgi\\OneDrive - EVS Broadcast Equipment SA\\Desktop\\vgi août\\vgi août_rendered - not working.mpd",
"track": [
{
"@type": "General",
"VideoCount": "3",
"AudioCount": "1",
"FileExtension": "mpd",
"Format": "DASH MPD",
"FileSize": "3777",
"File_Created_Date": "2023-05-09 08:15:25.238 UTC",
"File_Created_Date_Local": "2023-05-09 10:15:25.238",
"File_Modified_Date": "2023-05-09 08:13:34.932 UTC",
"File_Modified_Date_Local": "2023-05-09 10:13:34.932"
},
{
"@type": "Video",
"@typeorder": "1",
"ID": "1",
"Format": "AVC",
"CodecID": "avc1",
"BitRate": "1000448",
"Width": "704",
"Height": "576",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.222",
"extra": {
"Source": "vgi%20ao%C3%BBt_rendered.h264.704x576.1mbps.mp4",
"Source_Info": "Missing"
}
},
{
"@type": "Video",
"@typeorder": "2",
"ID": "2",
"Format": "AVC",
"CodecID": "avc1",
"BitRate": "400384",
"Width": "352",
"Height": "288",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.222",
"extra": {
"Source": "vgi%20ao%C3%BBt_rendered.h264.352x288.400kbps.mp4",
"Source_Info": "Missing"
}
},
{
"@type": "Video",
"@typeorder": "3",
"ID": "3",
"Format": "AVC",
"CodecID": "avc1",
"BitRate": "10240",
"Width": "160",
"Height": "88",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.818",
"extra": {
"Source": "vgi%20ao%C3%BBt_rendered.h264.160x88.10.2kbps.mp4",
"Source_Info": "Missing"
}
},
{
"@type": "Audio",
"ID": "4",
"Format": "mp4a.40",
"CodecID": "mp4a.40",
"BitRate": "96000",
"extra": {
"Source": "vgi%20ao%C3%BBt_rendered.tr0.ch0.aac.96000bps.48000hz.mp4",
"Source_Info": "Missing"
}
}
]
}
}
`

On the "working" file, the difference is that I replaced the %C3%BB by û. 
If I right-click on the mpd and run the media info on it, then I get the full info 

`{
"creatingLibrary": {
"name": "MediaInfoLib",
"version": "23.03",
"url": "https://mediaarea.net/MediaInfo"
},
"media": {
"@ref": "C:\\Users\\vgi\\OneDrive - EVS Broadcast Equipment SA\\Desktop\\vgi août\\vgi août_rendered - working.mpd",
"track": [
{
"@type": "General",
"VideoCount": "3",
"AudioCount": "1",
"FileExtension": "mpd",
"Format": "DASH MPD",
"FileSize": "4964186",
"Duration": "26.000",
"OverallBitRate_Mode": "VBR",
"OverallBitRate": "1527442",
"FrameRate": "25.000",
"FrameCount": "629",
"StreamSize": "3757",
"File_Created_Date": "2023-05-09 08:14:59.612 UTC",
"File_Created_Date_Local": "2023-05-09 10:14:59.612",
"File_Modified_Date": "2023-05-09 08:16:11.161 UTC",
"File_Modified_Date_Local": "2023-05-09 10:16:11.161"
},
{
"@type": "Video",
"@typeorder": "1",
"ID": "1-1",
"Format": "AVC",
"Format_Profile": "Main",
"Format_Level": "3.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"Format_Settings_GOP": "M=1, N=25",
"MuxingMode": "MPEG-4",
"CodecID": "avc1",
"Duration": "25.160",
"BitRate_Mode": "VBR",
"BitRate": "1016593",
"BitRate_Maximum": "1200128",
"Width": "704",
"Height": "576",
"Sampled_Width": "704",
"Sampled_Height": "576",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.222",
"Rotation": "0.000",
"FrameRate_Mode": "CFR",
"FrameRate": "25.000",
"FrameCount": "629",
"Standard": "PAL",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"StreamSize": "3197185",
"Language": "en",
"BufferSize": "1200128",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"extra": {
"Source": "vgi%20août_rendered.h264.704x576.1mbps.mp4",
"CodecConfigurationBox": "avcC"
}
},
{
"@type": "Video",
"@typeorder": "2",
"ID": "2-1",
"Format": "AVC",
"Format_Profile": "Main",
"Format_Level": "3.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_RefFrames": "4",
"MuxingMode": "MPEG-4",
"CodecID": "avc1",
"Duration": "25.160",
"BitRate_Mode": "VBR",
"BitRate": "401215",
"BitRate_Maximum": "480256",
"Width": "352",
"Height": "288",
"Sampled_Width": "352",
"Sampled_Height": "288",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.222",
"Rotation": "0.000",
"FrameRate_Mode": "CFR",
"FrameRate": "25.000",
"FrameCount": "629",
"Standard": "PAL",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"StreamSize": "1261822",
"Language": "en",
"BufferSize": "480256",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"extra": {
"Source": "vgi%20août_rendered.h264.352x288.400kbps.mp4",
"CodecConfigurationBox": "avcC"
}
},
{
"@type": "Video",
"@typeorder": "3",
"ID": "3-1",
"Format": "AVC",
"Format_Profile": "Main",
"Format_Level": "1.1",
"Format_Settings_CABAC": "Yes",
"Format_Settings_GOP": "N=1",
"MuxingMode": "MPEG-4",
"CodecID": "avc1",
"Duration": "26.000",
"BitRate_Mode": "VBR",
"BitRate": "10380",
"BitRate_Maximum": "12288",
"Width": "160",
"Height": "88",
"Stored_Height": "96",
"Sampled_Width": "160",
"Sampled_Height": "88",
"PixelAspectRatio": "1.000",
"DisplayAspectRatio": "1.818",
"Rotation": "0.000",
"FrameRate_Mode": "CFR",
"FrameRate": "1.000",
"FrameCount": "26",
"ColorSpace": "YUV",
"ChromaSubsampling": "4:2:0",
"BitDepth": "8",
"ScanType": "Progressive",
"StreamSize": "33735",
"Language": "en",
"BufferSize": "49152",
"colour_range": "Limited",
"colour_range_Source": "Stream",
"extra": {
"Source": "vgi%20août_rendered.h264.160x88.10.2kbps.mp4",
"CodecConfigurationBox": "avcC"
}
},
{
"@type": "Audio",
"ID": "4-1",
"Format": "AAC",
"Format_AdditionalFeatures": "LC",
"MuxingMode": "MPEG-4",
"CodecID": "mp4a-40-2",
"Duration": "25.195",
"BitRate": "93305",
"Channels": "2",
"ChannelPositions": "Front: L R",
"ChannelLayout": "L R",
"SamplesPerFrame": "1024",
"SamplingRate": "48000",
"SamplingCount": "1209360",
"FrameRate": "46.875",
"FrameCount": "1181",
"Compression_Mode": "Lossy",
"StreamSize": "293854",
"Language": "en",
"extra": {
"Source": "vgi%20août_rendered.tr0.ch0.aac.96000bps.48000hz.mp4"
}
}
]
}
}
`

[vgi août.zip](https://github.com/MediaArea/MediaInfoLib/files/11428904/vgi.aout.zip)

**Comment by Valgil** [comment]
Merci beaucoup Jérôme :)

**Comment by JeromeMartinez** [comment]
Dev snapshot: [Windows](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230509/MediaInfo_GUI_23.04.20230509_Windows.exe), [macOS](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20230509/MediaInfo_GUI_23.04.20230509_Mac.dmg), [Linux](https://mediaarea.net/download/snapshots/binary/libmediainfo0/).

Usually this kind of issue with rare files is managed through [professional services](https://mediaarea.net/Services) but I was a bit lazy with this small fix, you may consider to [support us through a small sponsorship](https://mediaarea.net/SupportUs).
