### ISSUE TITLE
[build] macos build failed to run Apple m1

### ISSUE THREAD

**Issue by chenrui333** [MediaArea/MediaInfoLib#1772]
trying to [build libmediainfo for homebrew](https://github.com/Homebrew/homebrew-core/pull/131612), but failed to run against the library as some error show below:

```
Undefined symbols for architecture arm64:
  "MediaInfoLib::MediaInfo::Get(MediaInfoLib::stream_t, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, MediaInfoLib::info_t, MediaInfoLib::info_t)", referenced from:
      _main in test-4efa00.o
  "MediaInfoLib::MediaInfo::Open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      _main in test-4efa00.o
ld: symbol(s) not found for architecture arm64
```

I am running on Ventura ARM, and let me know I need to provide more info

**Comment by alebcay** [comment]
Probably just need to `#define _UNICODE` at the top of the source file when building/linking against `mediainfolib`, as described at https://sourceforge.net/p/mediainfo/discussion/297610/thread/db175ffe96/#5bf8/abaf.

**Comment by chenrui333** [comment]
Thanks to @alebcay's test update, resolved on my end :)
