### ISSUE TITLE
TrackType element reported as "(Multiple info)"

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaInfoLib#180]
Referenced file: [http://samples.ffmpeg.org/archive/all/matroska+h264+vorbis++COLORS.mkv](http://samples.ffmpeg.org/archive/all/matroska+h264+vorbis++COLORS.mkv)

The mediatrace for this contains:
```xml
<block offset="698" name="FlagLacing" info="0" size="3">
  <block offset="698" name="Header" size="2">
    <data offset="698" name="Name">28</data>
    <data offset="699" name="Size">1</data>
  </block>
  <data offset="700" name="Data">0</data>
</block>
<block offset="701" name="(Multiple info)" info="1" size="3">
  <block offset="701" name="Header" size="2">
    <data offset="701" name="Name">3</data>
    <data offset="702" name="Size">1</data>
  </block>
  <data offset="703" name="Data">1</data>
</block>
<block offset="704" name="MinCache" info="1" size="4">
  <block offset="704" name="Header" size="3">
    <data offset="704" name="Name">11751</data>
    <data offset="706" name="Size">1</data>
  </block>
  <data offset="707" name="Data">1</data>
</block>
```

`(Multiple info)`? In this posiiton is a normal looking `TrackType` element: 0x838101. The elements before and after it look okay.

Should the implementation checker expect `(Multiple info)` in this case?

**Comment by dericed** [comment]
The same sample does something similar in the second track entry:

```xml
<block offset="5103" name="(Multiple info)" info="2" size="3">
  <block offset="5103" name="Header" size="2">
    <data offset="5103" name="Name">87</data>
    <data offset="5104" name="Size">1</data>
  </block>
  <data offset="5105" name="Data">2</data>
</block>
```

The `TrackNumber` element is supposed to be there.

**Comment by dericed** [comment]
Possibly related, but the SeekHead references a `Tracks` element at 73610536 but it is actually at 564.

**Comment by dericed** [comment]
This appears to be a db bug. After deleting my database file this file works.

**Comment by JeromeMartinez** [comment]
> Possibly related, but the SeekHead references a Tracks element at 73610536 but it is actually at 564.

Not related.

**Comment by JeromeMartinez** [comment]
https://github.com/MediaArea/MediaInfoLib/commit/64722ddfcbeeffccf6c563ef786435b7e80a10a2
