### ISSUE TITLE
Time code of first frame inaccurate in recent versions

### ISSUE THREAD

**Issue by SamuelCBlum** [MediaArea/MediaInfoLib#1804]
In the latest version 23 of mediainfo I am seeing the following incorrect timecode:
Time code of first frame                 : 70:01:14:20

In previous versions (ex. 20.09), the timecode shows correctly:
Time code of first frame                 : 23:55:35:07

Attached is the terminal output when running mediainfo using the two versions.

[mediainfo_v20_09.txt](https://github.com/MediaArea/MediaInfo/files/11616500/mediainfo_v20_09.txt)
[mediainfo_v23_03.txt](https://github.com/MediaArea/MediaInfo/files/11616501/mediainfo_v23_03.txt)

**Comment by JeromeMartinez** [comment]
You can test with [latest snapshots](https://mediaarea.net/download/snapshots/binary/).
It is also more correct than in 20.03 (title, in first "Other" track, ...).

Issue was that there are 2 tracks with same ID, behavior was less ugly in v20.03 but also not so good. Now:

```
Other #1
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 17 min 43 s
Bit rate mode                            : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Time code of first frame                 : 23:55:35:07
Time code of last frame                  : 24:13:17:06
Time code, stripped                      : Yes
Title                                    : GoPro TCD
Language                                 : English
```

The second "Other" is actually a "GoPro SOS" (name of the handler written in the file) metadata track, but I have no info about the content itself, I'll add some info (codec ID, name of the handler...) in the next PR.

**Comment by JeromeMartinez** [comment]
@SamuelCBlum latest snapshots have a better display of the 2 weird tracks having the same value (and a quicker parsing):

```
Other #1
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 17 min 43 s
Bit rate mode                            : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Time code of first frame                 : 23:55:35:07
Time code of last frame                  : 24:13:17:06
Time code, stripped                      : Yes
Title                                    : GoPro TCD
Language                                 : English
Encoded date                             : 2015-01-10 23:56:51 UTC
Tagged date                              : 2015-01-10 23:56:51 UTC

Other #2
ID                                       : 3
Type                                     : meta
Format                                   : fdsc
Codec ID                                 : fdsc
Duration                                 : 17 min 43 s
Bit rate mode                            : Variable
Title                                    : GoPro SOS
Language                                 : English
Encoded date                             : 2015-01-10 23:56:51 UTC
Tagged date                              : 2015-01-10 23:56:51 UTC
mdhd_Duration                            : 1063062
Conformance errors                       : Yes
 tkhd                                    : Yes
  track_ID                               : track_ID 3 is already used by another track
```

There is a [conformance check now on the track ID](https://mediaarea.net/Specs/ISO_IEC_14496-12/moov/trak/tkhd/track_ID) in addition to not so buggy support of such content.

`fdsc` format (GOPRO metadata, firmware version, serial number, model) is not yet supported, drop us an email if you are interested in that).
