### ISSUE TITLE
Blackmagic RAW Crop Information Support

### ISSUE THREAD

**Issue by craftycodie** [MediaArea/MediaInfoLib#1807]
Hi! I'm looking at a .braw file which uses cropping. I can see from the Blackmagic SDK that the crop data is like this:

```
crop_origin: 16,8,
crop_size: 4096,2160,
```

MediaInfo shows me both of these fields but their values are 'Unknown kind of value!'.

I'd be happy to try to PR a fix for this with some basic guidance :)

**Comment by JeromeMartinez** [comment]
It is [there](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mpeg4_Elements.cpp#L3607), the `Kind` field seems to have a non classic value.

Having a sample file would be good, in order to quickly see the value and the actual content.

**Comment by craftycodie** [comment]
The file I'm working with isn't mine to share unfortunately, I'll have a go at debugging and fixing myself though :)

**Comment by JeromeMartinez** [comment]
We accept NDA and private sharing, don't hesitate to drop a mail to info@mediaarea.net
It would help for regression test (after we remove all the necessary parts, actually we only need the `moov` which has no content, if you can cut the file)

**Comment by craftycodie** [comment]
I've been on holiday for a week but I'm getting back to this.
Think I've got a list of the unrecognised braw fields now:

```
76 post_3dlut_embedded_size
77 braw_codec_bitrate
71 crop_origin
71 crop_size
76 anamorphic_enable
76 tone_curve_video_black_level
76 viewing_bmdgen
```

Will continue to implement :)
