### ISSUE TITLE
Android only: FLAC recognzied as AAC main in ADIF

### ISSUE THREAD

**Issue by ValeZAA** [MediaArea/MediaInfoLib#1819]
Why? I also tried latest armv8 and armv7 nightly from here: 

https://mediaarea.net/download/snapshots/binary/mediainfo-gui/

Both give this strange result.

Sample `https://mailccsf-my.sharepoint.com/:u:/g/personal/dirizar2_mail_ccsf_edu/Ea2VAaVb3GFLh8mOuP6mkyoBF1WxaPTj5_SJkJjge0eT1w?e=hsQapl`

**Comment by JeromeMartinez** [comment]
Tested on Windows x64, Linux x64, Android ARMv8, and it is all fine (detected as FLAC). Need more details about how to reproduce.

**Comment by ValeZAA** [comment]
Can only provide a screenshot. I use Galaxy S23 Ultra.

![Screenshot_20230703_000943_MediaInfo](https://github.com/MediaArea/MediaInfoLib/assets/123130979/2add7968-535b-4750-b4e1-5190d798c6de)

**Comment by JeromeMartinez** [comment]
Mine below.
Can not see why this different behavior, we'll check a bit more in case we can catch a random behavior, but don't expect much quickly.

![Screenshot_20230703-043022_MediaInfo](https://github.com/MediaArea/MediaInfoLib/assets/1641638/4d6b4a97-29a9-4a90-8007-e5de9603bea2)

**Comment by JeromeMartinez** [comment]
I can reproduce the issue with [MediaInfoOnline](https://mediaarea.net/MediaInfoOnline), so it should be corrected soon after some research about why the behavior changed in some cases.
