### ISSUE TITLE
CURLINFO breaking JSON output

### ISSUE THREAD

**Issue by benswinburne** [MediaArea/MediaInfoLib#1829]
When using mediainfo with libcurl, curl is outputting a string of information about the certificate.

```
default ca info path: /etc/ssl/cert.pem
{
  "creatingLibrary":{"name":"MediaInfoLib","version":"23.06","url":"https://mediaarea.net/MediaInfo"},
  ...
```

Obviously this means parsing the json output becomes more problematic than it should be.

Looking into the code it appears it's to do with this line but I can't see an obvious way how to turn this off.

https://github.com/MediaArea/MediaInfoLib/blob/785ce8f4816d6e96afbac18c99319c1e2f590100/Source/MediaInfo/Reader/Reader_libcurl.cpp#L957

I'm not sure if this is a bug or a feature request or just the expected behaviour so figured I'd drop it here.

**Comment by JeromeMartinez** [comment]
> When using mediainfo with libcurl, curl is outputting a string of information about the certificate.

We don't have that. Which OS (name/version) and which command?

> Obviously this means parsing the json output becomes more problematic than it should be.

I would expect that libcurl outputs on stderr so not conflicting with the JSON output on stdout, isn't it the case?

**Comment by JeromeMartinez** [comment]
> Also just realised I may have found myself in the wrong repo? 

It is the right one, about libcurl (it is in the lib).

**Comment by benswinburne** [comment]
Fantastic, thanks for fixing so quickly. Can confirm this works as expected now. Much appreciated.
