### ISSUE TITLE
QuickTime File Short TimeCode Track

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaInfoLib#1878]
I have a QuickTime MOV file that has a timecode track showing in MediaInfo shorter than the actual video and playable timecode track. You can see here the duration is 23 minutes but the timecode stops at 01:03:46;28. Inspecting the file I can see what appears to be 3 samples in the QT Timecode track when inspecting via atombox. The timecode when pulled up in a player appears contiguous. These timecode samples appear at at what look like different chunk offsets. Would this cause the issue? I can send the file over out of band.

<img width="580" alt="image" src="https://github.com/MediaArea/MediaInfo/assets/114635378/9f3a8cd8-80a5-492d-9b43-2495b5173c92">

> Other
ID                                       : 1
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 23 min 23 s
Bit rate mode                            : Constant
Frame rate                               : 29.970 (30000/1001) FPS
Time code of first frame                 : 00:59:40;00
Time code of last frame                  : 01:03:46;28
Time code, stripped                      : No
Title                                    : looneytunes_028
Language                                 : English
Default                                  : No
Encoded date                             : 2014-03-04 19:25:03 UTC
Tagged date                              : 2014-03-04 19:48:26 UTC

**Comment by JeromeMartinez** [comment]
@joe-sciame-wm while doing QA with the updated code, we found a file in our database with a weird time code track, something like media duration is 100, there are 100 continuous time codes with a duration of 1, then 1 additional and non continuous time code with a duration of 0, so there but not part of media duration due to frame number being more than indicated frame count and a duration which technically leads to no display. Do you consider this 101st time code as non continuous or do you consider it as not part of the stream so no discontinuity info about it?

**Comment by joe-sciame-wm** [comment]
Thanks @JeromeMartinez. I downloaded the latest version and I can now see. 

> Time code of first frame                 : 00:59:40;00
> Time code of last frame                  : 01:23:02;29
> Time code, stripped                      : No
> Discontinuities                          : 01:03:46;26-01:03:46;26 / 01:03:46;26-01:03:46;28

This looks good. On the if the 101 is a timecode discontinuity, what did you end up deciding? How does that scenario happen?  I'm not sure what the implications might be on that extra zero duration TC and whether those implications would warrant a discontinuity. If its not part of the stream and not displayed, I would tend to think no i.e. its extra data that file decoders would ignore, but not sure.

**Comment by JeromeMartinez** [comment]
> On the if the 101 is a timecode discontinuity, what did you end up deciding?

The current patch discards data with a duration of 0, so no discontinuity displayed. Can be changed, either by checking the discontinuity if it the last frame (but currently not in favor of that as it is not intended to be displayed) or a conformance warning (information that this is a weird stream; but a more complete conformance checking would include a lot more tests, expensive, not sure it is worth it); or we stay with showing nothing.

>  How does that scenario happen?

No idea!
I can only say that it exists in the wild and prefer to warn you about the limitation of the current behavior.

Anecdote: I also found a file with 2000 time codes, some frames having a duration of 400 ticks as expected (tick rate of 100 so 4 time codes) and some other frames having a duration of -200 ticks (I try to imagine what is the meaning of a negative duration there...), FYI I treat duration as unsigned so a huge discontinuity is displayed in that case.
Crazy muxers :).

```
0000C446      Time to Sample (35384 bytes)
0000C446       Header (8 bytes)
0000C446        Size:                            35384 (0x00008A38)
0000C44A        Name:                            stts
0000C44E       Version:                          0 (0x00)
0000C44F       Flags:                            0 (0x000000)
0000C452       Number of entries:                4421 (0x00001145)
0000C456       Sample Count:                     1 (0x00000001)
0000C45A       Sample Duration:                  400 (0x00000190)
0000C45E       Sample Count:                     1 (0x00000001)
0000C462       Sample Duration:                  -200 (0xFFFFFF39)
0000C466       Sample Count:                     1 (0x00000001)
0000C46A       Sample Duration:                  100 (0x00000064)
0000C46E       Sample Count:                     1 (0x00000001)
0000C472       Sample Duration:                  400 (0x00000190)
0000C476       Sample Count:                     1 (0x00000001)
0000C47A       Sample Duration:                  -200 (0xFFFFFF39)
[...]
```
