### ISSUE TITLE
CaptionServiceName T1 in ST 436 and ATSC/53 Text Tracks

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfoLib#1882]
I have an MPEG2 in an MXF OP1a file with ATSC/53 and SMPTE ST 436 text tracks.  MediaInfo is reporting something I've never seen before:

```
      <extra>
        <CaptionServiceName>T1</CaptionServiceName>
        <CaptionServiceDescriptor_IsPresent>Yes</CaptionServiceDescriptor_IsPresent>
        <cdp_length_Min>82</cdp_length_Min>
        <cdp_length_Max>89</cdp_length_Max>
      </extra>
```

I'm not sure what a T1 service represents and I'm not seeing it in other tools. Full XML attached and caption byte payloads or the entire file available if needed.

[UXKV_01_mediainfo.xml.txt](https://github.com/MediaArea/MediaInfo/files/12798799/UXKV_01_mediainfo.xml.txt)

**Comment by JeromeMartinez** [comment]
New option (CLI only for the moment, GUI will be with other options):

```
mediainfo UXKV-A_01_D01.scc.txt "--Inform=Text;%ID%,"
CC1,T1,
mediainfo UXKV-A_01_D01.scc.txt "--Inform=Text;%ID%," --File_CommandOnlyMeansEmpty=1
CC1,
```

**Comment by plondino** [comment]
This works from the command line as expected.

However, it doesn't seem to work when I use the Python bindings via:

`self.mediainfo.Option_Static('File_CommandOnlyMeansEmpty', '1')`

Is there any reason why these new parameters wouldn't work via the DLL directly?

**Comment by plondino** [comment]
Ah ok, this works:

`self.mediainfo.Option('File_CommandOnlyMeansEmpty', '1')`

What's the difference between Option and Option_Static?

**Comment by JeromeMartinez** [comment]
@plondino while working on the GUI I remarked that there is an incompatibility between this request and https://github.com/MediaArea/MediaInfo/issues/674, so I added an option without incompatibilities at https://github.com/MediaArea/MediaInfoLib/pull/2085.
"Old" options are still there but the last one replaces the previous one, please use the new option instead when you can.

I also added `extra/InternalDetectionKind` field when no content is detected, with values `Command` (indicating that no 608/708 content was found, only commands) or `Stream` (indicating that no 608/708 content or command was found, only an empty 680/708 stream), in case it helps e.g. if you use self.mediainfo.Option('File_File_DisplayCaptions ', 'Stream') and then want to know if a content was actually detected . More relevant with a full parsing.

> What's the difference between Option and Option_Static?

There was a tentative to do a difference between global options for all MediaInfo instances (the static one, usable in C++ without creating a single instance of a class) and options only for one instance (the non static one, usable in C++ only when an instance if a class is created) for avoiding too much mutex locks but in practice it is not a good way to do it, at long term we need to remove the difference and consider all the `File_*` and if they are without this prefix, and usable with or without an instance of the class.
