### ISSUE TITLE
Multiple frame count values in PCM / MXF

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfoLib#1884]
I have an MPEG2 MXF file with PCM audio.  For most of the audio tracks the frame count is a single value:

`<FrameCount>11189</FrameCount>`

But for some of them it has two frame count values:

`<FrameCount>11189 / 11189</FrameCount>`

It's not clear to me what this is conveying - if there's a difference in sample counts between the channels that information would be extremely useful but in both cases I see:

`<SamplingCount>17920320</SamplingCount>`

Full XML is attached, files available if needed.

[1AAR3-A_06_mediainfo.xml.txt](https://github.com/MediaArea/MediaInfoLib/files/12851513/1AAR3-A_06_mediainfo.xml.txt)

**Comment by JeromeMartinez** [comment]
We found a file in our database with such glitch (doubled at one place, missing at the other place, the span of the value across all Dolby E tracks fails), working on it.
