### ISSUE TITLE
Problem with GoPro 8 video files

### ISSUE THREAD

**Issue by Tomek398** [MediaArea/MediaInfoLib#1885]
Media info is not working with video files from GoPro8 camera, both in H.265 and H.264 format

https://forum.selur.net/thread-3427.html

**Comment by JeromeMartinez** [comment]
We need a sample file.

**Comment by Tomek398** [comment]
Thanks for replying. How can send the link to the sample file? I'm very new to this forum and I don't see an option to send private message.

**Comment by JeromeMartinez** [comment]
You can send the link to our generic email address info@mediaarea.net.

**Comment by Tomek398** [comment]
I've just sent link to the above email address. Thanks

**Comment by JeromeMartinez** [comment]
> Media info is not working

Be more precise about "not working", I see very well in MediaInfo (GUI or CLI) everything: video, audio, time code, and the (unsupported but listed) GoPro metadata.

Note that we do free support only for MediaInfo related issue, so the MediaInfo output, not the behavior from another tool.

**Comment by Tomek398** [comment]
I fully understand that you can't be responsible for behaviour of another tools. I was referred here by author of Hybrid video.  I'm not an video expert at all. 

As far as I understand the following command is not saving a log file if the input file comes from GoPro8 (this is only example):

"C:\Program Files\Hybrid\64bit\mediainfo.exe" --Language=en --File_TestContinuousFileNames=0 "--LogFile=C:/Users/Tomek398/AppData/Local/Temp/mediaInfoLog.txt" --Full "J:\GoPro8_Media\2023.09.17 Canonball Ireland 2023\GH010827.MP4"

I tested it with other video files and it fact, it work, but doesn't work (doesn't generate log file) in the case of video files coming from GoPro8

Thanks for checking it.

**Comment by Tomek398** [comment]
Please check the test I've just done:

https://youtu.be/BqlBWQoa0ks

**Comment by JeromeMartinez** [comment]
Thank you for the method for reproducing the issue as standalone.

I Installed (thus huge!) Hybrid 2023.03.17.1 and tested:

```
C:\Users\jerom\Downloads>"C:\Program Files\Hybrid\64bit\mediainfo.exe" --version
MediaInfo Command line,
MediaInfoLib - v22.12

C:\Users\jerom\Downloads>"C:\Program Files\Hybrid\64bit\mediainfo.exe" .\GoPro8_0.1.MP4

C:\Users\jerom\Downloads>.\MediaInfo.exe --version
MediaInfo Command line,
MediaInfoLib - v23.10

C:\Users\jerom\Downloads>.\MediaInfo GoPro8_0.1.MP4
General
Complete name                            : GoPro8_0.1.MP4
Format                                   : MPEG-4
[...]
```

So already fixed, the fix for you is to update MediaInfo, you can try to replace directly the binary in Hybrid directory, no incompatibility expected.
