### ISSUE TITLE
Bug in MediaInfoDLL.h header

### ISSUE THREAD

**Issue by clsid2** [MediaArea/MediaInfoLib#1904]
`bool IsReady() {return (Handle && MediaInfo_Module) ? true : false;}`
should be
`bool IsReady() {return (Handle != nullptr && MediaInfo_Module != nullptr);}` 

I was getting false result while both pointers were valid. Current code is doing math instead of checking for non-null values. Fails if one pointer has zeros in least significant bits.

**Comment by JeromeMartinez** [comment]
Very awful old code, me 20 years ago is hiding.
We'll change that but I don't get how 1 valid pointer with zeros in least significant bits could make a "false", could you elaborate? To me it is a "&&" so no math.

**Comment by clsid2** [comment]
You are right, my conclusion was too quick. It was probably getting casted to a negative value.

**Comment by JeromeMartinez** [comment]
It still does not explain how the current code could fail with non zero values.
Please provide an example of values so I could reproduce and understand the source of the issue.

**Comment by clsid2** [comment]
Sorry, I am not spending time recreating the problem again. This fixes a bug in MPC-HC, so do with the info what you want.
