### ISSUE TITLE
Detect Dolby Surround EX & Dolby Pro Logic IIx/IIz in TrueHD

### ISSUE THREAD

**Issue by rixtox** [MediaArea/MediaInfoLib#1928]
According to Table 6 and Table 9 from the [Dolby TrueHD high level bitstream description][1]:

When there are three or more encoded channels, the `6ch_presentation_channel_modifier` shall only have meaning if the Surround (Ls/Rs) channels are present, in which case Table 6 shall apply.

![image](https://github.com/MediaArea/MediaInfoLib/assets/2001277/ef7406db-ebf0-4a15-9716-6c3e54702ca9)

When there are three or more encoded channels the `8ch_presentation_channel_modifier` shall only have meaning if the Surround (Ls/Rs) channels are the **only surround channels** present, in which case Table 9 shall apply.

![image](https://github.com/MediaArea/MediaInfoLib/assets/2001277/9af072a4-4b5b-4a4d-a590-0c457e916074)

Currently [MediaInfo is skipping these modifier fields][2]. Please add support to detect and report these fields. It's a bit difficult to find samples though, but implementing it according to the spec above should be straightforward.

[1]: https://developer.dolby.com/globalassets/technology/dolby-truehd/dolbytruehdhighlevelbitstreamdescription.pdf
[2]: https://github.com/MediaArea/MediaInfoLib/blob/af5de661de10a7cf5948c144f6a01147b9ae603b/Source/MediaInfo/Audio/File_Ac3.cpp#L4506-L4508

**Comment by JeromeMartinez** [comment]
> It's a bit difficult to find samples though

I don't like to implement without real files, but as it is very rare and not big...

> but implementing it according to the spec above should be straightforward.

I added a mapping from `8ch_presentation_channel_modifier` to `dsurexmod` (advantage is that it is quick, disadvantage is that it is not known if the flag comes from AC-3 or TrueHD when both are present, but I don't want to spend much time on such rare case), we don't use `6ch_presentation_channel_assignment` so I don't map `6ch_presentation_channel_modifier`.
