### ISSUE TITLE
Analyzing media from Panansonic DC-GH6 camera takes a very long time

### ISSUE THREAD

**Issue by RensvanderZwan** [MediaArea/MediaInfoLib#1940]
Linked is one of the media files where MediaInfo takes way longer to retrieve Media information than normal. 
Looks like MediaInfo 23.11.1 does a full decode and not a quick scan.
Files are on local storage and dont look damaged or corrupt and once the media information has been extracted it looks pretty normal.

Tried also older versions but the result is the same.

Sample File: https://we.tl/t-ZfZDS7deCn

**Comment by JeromeMartinez** [comment]
> Looks like MediaInfo 23.11.1 does a full decode and not a quick scan.

No, it was a super slow tentative (and fail) to decode a big (it seems to contain a JPEG image) unrecognized metadata block.
[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/1941), will be in [next development snapshots](https://mediaarea.net/download/snapshots/binary/) and next release.

Note that Panasonic metadata (XML or binary) are not yet decoded (on our todo-list but no ETA as we have no sponsor for that so lower priority).
