### ISSUE TITLE
Please add VVC support in MPEG-TS container

### ISSUE THREAD

**Issue by svlobanov** [MediaArea/MediaInfoLib#1942]
VVC is not supported in MPEG-TS container, but it is allowed by actual version of ISO 13818-1. Could you please add vvc mpegts support?

sample: [vvc-720p.zip](https://github.com/MediaArea/MediaInfo/files/13818164/vvc-720p.zip)

ffplay with libvvcdec (https://github.com/fraunhoferhhi/vvenc/wiki/FFmpeg-Integration) plays this file normally,

ffprobe output:
~~~
% ffprobe  vvc-720p.ts 
ffprobe version n6.1.1 Copyright (c) 2007-2023 the FFmpeg developers
  built with Apple clang version 15.0.0 (clang-1500.0.40.1)
  configuration: --enable-libxml2 --enable-libvvdec --enable-libvvenc --enable-gpl
...
Input #0, mpegts, from 'vvc-720p.ts':
  Duration: 00:00:59.08, start: 600.000000, bitrate: 423 kb/s
  Program 1 
  Stream #0:0[0x1011](hin): Video: vvc (Main 10) (3[0][0][0] / 0x0033), yuv420p10le(tv), 1280x720, 25 fps, 25 tbr, 90k tbn
~~~

**Comment by JeromeMartinez** [comment]
I have [started a dev](https://github.com/MediaArea/MediaInfoLib/pull/1943) for showing basic details based on the TS related descriptor, this shows that:

```
Video
ID                                       : 4113 (0x1011)
Menu ID                                  : 1 (0x1)
Format                                   : VVC
Format/Info                              : Versatile Video Coding
Format profile                           : Main 10@L3.1@Main
Codec ID                                 : 51
Duration                                 : 59 s 0 ms
Bit rate                                 : 403 kb/s
Stream size                              : 2.83 MiB (95%)
Language                                 : Hindi
```
Available in [dev snapshots](https://mediaarea.net/download/snapshots/binary/).

But it is long to do more (parsing the bitstream itself) so it would not be (yet) in free support to do more.
Please contact us at [info@mediaarea.net](mailto:info@mediaarea.net) if you are interested in sponsoring the prioritization of the development of this feature.

**Comment by svlobanov** [comment]
Thanks you. I'm closing this ticket
