### ISSUE TITLE
Official DyLib download for macOS no longer exports any symbols for x86_64 architecture

### ISSUE THREAD

**Issue by mthies-unibi** [MediaArea/MediaInfoLib#1961]
Since version 23.11 (as far as I can tell) the official download of the MediaInfo DyLib for macOS no longer exports any symbols for the x86_64 architecture. The library claims to support architectures x86_64 and arm64 according to the output of `lipo libmediainfo.0.dylib -info` but `nm -arch x86_64 libmediainfo.0.dylib` lists no symbols at all. With `nm -arch arm64 ...` the exported symbols are listed as expected.

This means that the currently provided download
<https://mediaarea.net/download/binary/libmediainfo0/24.01/MediaInfo_DLL_24.01_Mac_x86_64+arm64.tar.bz2>
no longer works on Intel Macs.

The last version that I have used successfully, on both Intel and M1 Macs, was 23.10. It is suspicious that the size of the `.dylib` binary file has dropped from 15 MiB (version 23.10) to 7.3 MiB (version 24.01) which looks like all x86_64 code got stripped from the library, except for the header entry still mentioning support for x86_64.

**Comment by g-maxime** [comment]
Please test [this snapshot](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20240205-2/MediaInfo_DLL_24.01.20240205_Mac_x86_64+arm64.tar.xz)

**Comment by mthies-unibi** [comment]
In my testing, the library in the snapshot works on Intel-based Macs again (and also on M1-based Macs), like version 23.10 did.
:smile:

**Comment by plondino** [comment]
The snapshot works for me as well, but is there a plan to create a release version that fixes this issue? We don't want to use a snapshot in our production workflows but are unable to test locally on many dev's machines with 23.11-24.01.
