### ISSUE TITLE
Duration format differs GUI/Export vs DLL

### ISSUE THREAD

**Issue by myron0815** [MediaArea/MediaInfoLib#1963]
Short: 
Duration has different format when calling via DLL vs showing in GUI/export XML

Long:
MediaInfo 24.01.1
MediaInfoGUI shows duration of a videofile as "97.099" -> parsed as double this results correctly in 1m 37s
Export as XML (sidecar file) also same value

But: when calling the Library (via java, with `String value = getI(streamKind, streamNumber, i, InfoKind.Text);`) 
i get an integer of "97099"

Since i have a factory method in my app to read MediaInfo values, i have (basically) no clue where the value comes from (DLL vs XML)... so  this gets parsed in a wrong way.

I read in an very old SO post from you, that duration is ALWAYS in milliseconds, so i assume, the XML export format should also adhere to that? (I even would assume for the GUI to display this same - but for display it might be easier to read)  
Or what is the deal with with that notation?

I dunno how long this is already the case, and if you could even change that behavior (b/c backward compatibility) - but how should i as consumer deal with that? is there any rule of thumb?  
Ignore double, remove the dot and always parse as int?
But that doesn't always work, since i found some old XMLs with a General.duration of "297.432307444" or "3508.800000000" so i have to parse it as double?!? - (But i might be able to ignore the pre2017 format)
(Ok, fallback i could parse Duration/String3 for myself)

br

**Comment by JeromeMartinez** [comment]
We didn't use the unit without prefix in our first version of the text output and now it is in the wild so we would break lot of tools if we change that now, but we "fixed" that when we created the XML (and JSON) output as it was new outputs so breaking nothing.
Checking dot would be worse, you can have precision more than milliseconds so dots with it too.

If you lose track of the source, would it be useful to have an option forcing seconds for `getI()`?

In the meantime, a work around would be to check `getI(streamKind, streamNumber, i, InfoKind.Measure)` just after `getI(streamKind, streamNumber, i, InfoKind.Text)`, if it is " ms" divide the value by 1000.

**Comment by myron0815** [comment]
ok, thanks for clarification; thought so...

Nah, no change needed; will try with "measure" param.

My problem is more dealing with the XMLs in the wild, so a new MI lib would not help here.  
Thanks :)
