### ISSUE TITLE
Crashes on corrupt PDF

### ISSUE THREAD

**Issue by hackerfactor** [MediaArea/MediaInfoLib#1967]
MediaInfoLib - v19.09  (Probably lots of other versions)

Edit the PDF so that the startxref is off by 1.
E.g., If startxref is 12345, then set it to 12346.
PDF viewers detect the error and fix it by scanning for the startxref object.

mediainfo crashes.

**Comment by JeromeMartinez** [comment]
> PDF viewers detect the error and fix it by scanning for the startxref object.

For the moment we don't use it much so we don't implement scanning, maybe in the future if there is a need for it.

Crash fixed, in next [dev snapshot](https://mediaarea.net/download/snapshots/binary/) and next public release.
