### ISSUE TITLE
Add a Travis CI test for some #defines

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfoLib#197]
Compilation should be tested with the equivalent of:
`MEDIAINFO_ADVANCED_NO;MEDIAINFO_ARCHIVE_NO;MEDIAINFO_DEMUX_NO;MEDIAINFO_DVDIF_ANALYZE_NO;MEDIAINFO_EVENTS_NO;MEDIAINFO_LIBCURL_NO;MEDIAINFO_LIBMMS_NO;MEDIAINFO_MD5_NO;MEDIAINFO_MINIMAL_YES;MEDIAINFO_MPEGTS_DUPLICATE_NO;MEDIAINFO_N19_NO;MEDIAINFO_OTHERTEXT_NO;MEDIAINFO_TRACE_NO;MEDIAINFO_READTHREAD_NO;MEDIAINFO_EXPORT_NO;MEDIAINFO_TEXT_YES`

Note: they are the ones used by [MPC-HC](https://github.com/mpc-hc/mpc-hc/blob/b1d9c80d860dc2c064ba5d11c661557c3ceaf237/src/thirdparty/MediaInfo/MediaInfoLib.vcxproj#L45)

**Comment by g-maxime** [comment]
https://github.com/MediaArea/MediaInfoLib/commit/fa4d6d9a6783ba48a6a20396adb38471fbc4c812
