### ISSUE TITLE
MediaInfoLib in ARM64

### ISSUE THREAD

**Issue by ReneeBolivar** [MediaArea/MediaInfoLib#1979]
Hello everyone,

Is it possible to build MediaInfoLib DLLs for Windows ARM64?

**Comment by JeromeMartinez** [comment]
Is there any issue when you use the [source code](https://mediaarea.net/MediaInfo/Download/Windows) for building for ARM64? As far as we know there is nothing blocking the compilation.
If you mean that we should provide the ARM64 build, for the moment we don't see enough Windows ARM64 usage for putting that on our build farm and we note your interest, we'll see if there are more people interested.
Can also be part of [professional services](https://mediaarea.net/Services) if you need it before we find enough users for doing it within the free support.

**Comment by ReneeBolivar** [comment]
I tried to create the DLL for ARM64, but I received an error in the "aes_ni.c" file. I found that the original AES repository has a pending update, but I think just updating wouldn't be enough to fix the error.
We tried to use the DLLs from ARM32, but on new devices with Windows 11, the bridge that currently supports the old DLLs will no longer receive support.

**Comment by aylaholanda** [comment]
Looking at the code the defined appoint to cryptography AES and ARM64 do not support this, Do you suggest any other cryptography available on code to use in this architecture?

**Comment by JeromeMartinez** [comment]
> Examining the code, it appears that the specified cryptography for ARM64 is AES. 

Could you explain more?
AFAIK this is standard C and should compile well, I didn't yet install ARM64 support on my Visual Studio but I bet on tiny details.

By the way, AES support is for very specific use cases e.g. encrypted HLS content and as a quick workaround you can disable it with MEDIAINFO_AES_NO preprocessor directive and removal of the aes dir in the Visual Studio project.

**Comment by aylaholanda** [comment]
if we try compilated the dll to arm64, because of AES is not possible to generate MediaInfo-Static_UWP.pch throw this exception: "
 the Severity  Code  Description  Project  File  Line  Suppression State  Details Error  C1083  Cannot open precompiled header file: 'ARM64\Debug\MediaInfo-Static_UWP.pch'" I do not know why but to arm64 he enters in this defined "#if defined( USE_INTEL_AES_IF_PRESENT )"

**Comment by aylaholanda** [comment]
If we skip the AES, it is possible to create the "MediaInfo-Static_UWP.pch', but the media info is not working.

**Comment by JeromeMartinez** [comment]
Definition is there:

~~~
#if 1 && defined( _WIN64 ) && defined( _MSC_VER )
#  define INTEL_AES_POSSIBLE
#endif

#if defined( INTEL_AES_POSSIBLE ) && !defined( USE_INTEL_AES_IF_PRESENT )
#  define USE_INTEL_AES_IF_PRESENT
#endif
~~~

I guess that the _WIN64 unfortunately includes ARM64 and it is the wrong check, so just comment the define lines.

> If we skip the AES, it is possible to create the "MediaInfo-Static_UWP.pch', but the media info is not working.

How not working? Which kind of behavior?

**Comment by JeromeMartinez** [comment]
From [Mircrosoft docs](https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170), it seems that the first line should have an additional ` && defined(_M_AMD64)`, could you test?

**Comment by aylaholanda** [comment]
After many tests, I finally can build the mediainfolib to ARM64.
The only change necessary to work is on Aesopt. h, change this line of code.
#if defined( INTEL_AES_POSSIBLE ) && !defined( USE_INTEL_AES_IF_PRESENT ) && !defined(_M_ARM64)
#  define USE_INTEL_AES_IF_PRESENT
#endif

**Comment by JeromeMartinez** [comment]
> !defined(_M_ARM64)

I prefer `defined(_M_AMD64)` because we'll have the issue again if Microsoft decides to support another platform, could you confirm that replacing `!defined(_M_ARM64)` by `defined(_M_AMD64)` is fine for you?

**Comment by aylaholanda** [comment]
I tried using _M_AMD64 and not working.
I think the defined _M_AMD64 is for devices architecture x64 from AMD.

**Comment by aylaholanda** [comment]
The device of the test is a Windows arm, with the processor from Snapdragon

**Comment by JeromeMartinez** [comment]
> I think the defined _M_AMD64 is for devices architecture x64 from AMD.

Exactly, and the idea is that I expect that it is not defined with ARM64 build.

> I tried using _M_AMD64 and not working.

Do you mean that `_M_AMD64` **is** defined (note that the `!` is not present with the `_M_AMD64` check) with ARM build?

**Comment by aylaholanda** [comment]
I do not understand, why add in definition AMD64 because the first part of sentence check if machine is Intel, not has any another situation with machine is Intel and amd64 in same time. You can explain how scenario this occurs?

**Comment by JeromeMartinez** [comment]
>  why add in definition AMD64 because the first part of sentence check if machine is Intel

No, it tests if a custom flag is already set.

> You can explain how scenario this occurs?

Your patch tests if it is not ARM64. if another architecture appears, the issue comes back (considered as Intel even if it is not)
My proposal is to test if it is AMD64. if another architecture appears, the issue **does not** come back (considered as not Intel)

In practice, your and my test should be a line above.

it is currently 

```
#if 1 && defined( _WIN64 ) && defined( _MSC_VER )
#  define INTEL_AES_POSSIBLE
#endif

#if defined( INTEL_AES_POSSIBLE ) && !defined( USE_INTEL_AES_IF_PRESENT )
#  define USE_INTEL_AES_IF_PRESENT
#endif
```

the test on `_WIN64` is wrong because it includes both AMD64 and ARM64, and it should be replace by `_M_AMD64`.

So please test with:
```
#if 1 && defined( _M_AMD64 ) && defined( _MSC_VER )
#  define INTEL_AES_POSSIBLE
#endif

#if defined( INTEL_AES_POSSIBLE ) && !defined( USE_INTEL_AES_IF_PRESENT )
#  define USE_INTEL_AES_IF_PRESENT
#endif
```

The only change is `_WIN64` replaced by `_M_AMD64`.

**Comment by aylaholanda** [comment]
Hi,

I tested your suggestion, and it worked well. Thank you!

**Comment by rednoah** [comment]
@JeromeMartinez If it's easy to add a `MediaInfo.dll` for `ARM64` target (DLL only is fine) to the build process, then I'd be happy to sponsor the work. We would be able to contribute `800 USD`. 

That said, the `ARM64` number of Windows PCs with `ARM64` is indeed very very small still, I just happen to be one of them. At this time, I wouldn't bother with `ARM64` support if that were to require extra hardware in the build system. It only makes sense if it's easy and just a matter minor modifications of some makefile somewhere.

**Comment by JeromeMartinez** [comment]
@rednoah you cheat, you are already a sponsor :-p

>  It only makes sense if it's easy and really just a matter some minor modifications of in some makefile somewhere.

I think that this is the case (+install of ARM toolchain on our build farm), we'll give it a try, cc @g-maxime,

**Comment by JeromeMartinez** [comment]
> If it's easy to add a MediaInfo.dll for ARM64 target (DLL only is fine) to the build process, 

@rednoah we don't have any ARM64 Windows machine, so we built it but we can not test, please test [this ARM64 build](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20241202/MediaInfo_DLL_24.11.20241202_Windows_ARM64_WithoutInstaller.zip).

**Comment by cjee21** [comment]
It will be great if someone with an ARM64 Windows 11 PC can help test whether the new Explorer context menu for MediaInfo GUI works on ARM.

**Comment by JeromeMartinez** [comment]
> It will be great if someone with an ARM64 Windows 11 PC can help test whether the new Explorer context menu for MediaInfo GUI works on ARM.

@cjee21 Currently we provide only the DLL, not the GUI, so we don't compile the Windows 11 integration.
C++ Builder has no support of ARM64 the GUI is not for soon (but I'll think to add the CLI and maybe the Windows 11 integration for just opening Notepad with the text output).

**Comment by cjee21** [comment]
> > It will be great if someone with an ARM64 Windows 11 PC can help test whether the new Explorer context menu for MediaInfo GUI works on ARM.
> 
> @cjee21 Currently we provide only the DLL, not the GUI, so we don't compile the Windows 11 integration. C++ Builder has no support of ARM64 the GUI is not for soon (but I'll think to add the CLI and maybe the Windows 11 integration for just opening Notepad with the text output).

I am expecting the current x64 GUI with Windows 11 context menu integration will work on Windows 11 ARM64 via Windows 11's emulation but I do not have access to an ARM PC to test. It may also be possible to include an ARM64EC MediaInfo DLL with the x64 GUI for better performance.

**Comment by JeromeMartinez** [comment]
> via Windows 11's emulation but I do not have access to an ARM PC to test.

Ho, right. Let's see if anyone in this thread is interested in testing and we may try to package that.

> It may also be possible to include an ARM64EC MediaInfo DLL with the x64 GUI for better performance.

I forgot this one. [ARM64EC](https://learn.microsoft.com/en-us/windows/arm/arm64ec).
The GUI definitely doesn't need to be ARM64, only the DLL.

**Comment by rednoah** [comment]
> > If it's easy to add a MediaInfo.dll for ARM64 target (DLL only is fine) to the build process,
> 
> @rednoah we don't have any ARM64 Windows machine, so we built it but we can not test, please test [this ARM64 build](https://mediaarea.net/download/snapshots/binary/libmediainfo0/20241202/MediaInfo_DLL_24.11.20241202_Windows_ARM64_WithoutInstaller.zip).

Nice work!

I've run some tests on my `Samsung Galaxy Book4 Edge` test machine and it all works. I've loaded the DLL from an `arm64` process, then read a couple of media files, and it all worked. I'll see about running some more tests on some more files, but I expect this to be done and dusted. :)


I can run tests for the standalone MediaInfo GUI / CLI if you wish. But I've already tested the `x64` binaries on my `arm64` and the translation layer works fast and flawless, so there's definitely less of a need for those.

**Comment by JeromeMartinez** [comment]
>  it all works.

Thanks for the confirmation.

> I can run tests for the standalone MediaInfo GUI / CLI if you wish. 

We are preparing the CLI.
For the GUI, a first shot will be to have the Windows Explorer integration for ARM64, then we'll see... Issue may be the Windows Explorer tooltip.
Do you have Win11?

**Comment by rednoah** [comment]
Yep, I'm on the latest Win11.

**Comment by cjee21** [comment]
> Yep, I'm on the latest Win11.

Can you test https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20241202-4/MediaInfo_GUI_24.11.20241202_Windows_x64.exe? It is fully x64 but contains new Windows 11 context menu integration added recently compared to the release version. What we are interested to find out is if the shell extensions work under emulation on ARM64.

To test, enable `Explorer extension` and `Explorer Tooltip` in MediaInfo Preferences and let us know if the following works:
- Right clicking a media file should have a MediaInfo entry in the new modern Windows 11 context menu (without clicking "Show more options") and clicking it should open the file in MediaInfo.
- Hovering over a media file should produce a tooltip pop-up that is generated by MediaInfo.

Note: To revert to an older version of MediaInfo after installing this build, you should uninstall first before installing the older build to ensure the new things which the older installer does not know about are properly removed.

**Comment by JeromeMartinez** [comment]
@rednoah and others with Windows ARM machine, please test [this snapshot of the CLI](https://mediaarea.net/download/snapshots/binary/mediainfo/20241203/MediaInfo_CLI_24.11.20241203_Windows_ARM64.zip).

**Comment by cjee21** [comment]
> @rednoah and others with Windows ARM machine, please test [this snapshot of the CLI](https://mediaarea.net/download/snapshots/binary/mediainfo/20241203/MediaInfo_CLI_24.11.20241203_Windows_ARM64.zip).

Sure this is correct? It appears to contain x64 MediaInfo.exe and libcurl.dll... It even runs on my x64 machine 😮

**Comment by g-maxime** [comment]
@cjee21 Thanks, copy error in the script, I rebuild

**Comment by g-maxime** [comment]
> > @rednoah and others with Windows ARM machine, please test [this snapshot of the CLI](https://mediaarea.net/download/snapshots/binary/mediainfo/20241203/MediaInfo_CLI_24.11.20241203_Windows_ARM64.zip).
> 
> Sure this is correct? It appears to contain x64 MediaInfo.exe and libcurl.dll... It even runs on my x64 machine 😮

Should be fixed in-place now (same link)

There's no libcurl.dll in the package, I'll fix that soon.

**Comment by rednoah** [comment]
Unfortunately, explorer extension / explorer tooltip test case from @cjee21 does not work. I have enabled it in the GUI and then restarted the machine just in case. The MediaInfo.exe shared by @JeromeMartinez does not print anything, unfortunately no error either.

![menu](https://github.com/user-attachments/assets/fcec6a37-9bd7-4e6a-92b6-7b969e48084a)
![Screenshot 2024-12-03 211911](https://github.com/user-attachments/assets/4bf6fab0-ba7e-4396-b2f6-e0d4d70dd355)
![Screenshot 2024-12-03 210814](https://github.com/user-attachments/assets/5785b228-6929-4ae3-8e93-d098bbb59731)

Note that I'm also working on context menu integration so there's some example integration from me on the screenshot as well.

I've also tested the GUI after installation and that starts and can read media file.



EDIT: I will retry since @g-maxime seems to just have updated the test files.

**Comment by cjee21** [comment]
> Unfortunately, explorer extension / explorer tooltip test case from @cjee21 does not work.

If possible can you check if the sparse package is installed by doing `Get-AppxPackage MediaInfo` in powershell? If yes then if possible, check if there is an attempt by `DLLHost.exe` to load the shell extension DLL.

**Comment by JeromeMartinez** [comment]
> The MediaInfo.exe shared by @JeromeMartinez does not print anything, unfortunately no error either.

(it was the x64 version but still valid) Actually the wildcard does not work (broken in x64 too), please retry with directly the file name.

**Comment by JeromeMartinez** [comment]
> >  Unfortunately, explorer extension / explorer tooltip test case from @cjee21 does not work.

> If possible can you check if the sparse package is installed by doing Get-AppxPackage MediaInfo in powershell? If yes then if possible, check if there is an attempt by DLLHost.exe to load the shell extension DLL.

I am not surprised, I doubt the integrated the support of calling another arch. They already did not do that for x64 with x86. We'll have to compile the ARM64 version of the DLL. But I think that it won't be a big deal there.

**Comment by cjee21** [comment]
> I am not surprised, I doubt the integrated the support of calling another arch. They already did not do that for x64 with x86. We'll have to compile the ARM64 version of the DLL. But I think that it won't be a big deal there.

I saw [this](https://answers.microsoft.com/en-us/windows/forum/all/how-are-x86-shell-extensions-able-to-run-on-arm64/cb223cb8-a03e-4d44-ab29-ccd25082a0e2) so I thought it would work. Just need to see if the sparse package is installed properly then. If yes then we'll only need to build ARM64 DLLs.

**Comment by rednoah** [comment]
> > The MediaInfo.exe shared by @JeromeMartinez does not print anything, unfortunately no error either.
> 
> (it was the x64 version but still valid) Actually the wildcard does not work (broken in x64 too), please retry with directly the file name.

Good catch! I forgot Windows leaves parsing the command-line to the executable itself. I have retried and the executable does indeed work when called with the exact file path instead of `*.mkv`.

**Comment by JeromeMartinez** [comment]
> I saw [this](https://answers.microsoft.com/en-us/windows/forum/all/how-are-x86-shell-extensions-able-to-run-on-arm64/cb223cb8-a03e-4d44-ab29-ccd25082a0e2) so I thought it would work. Just need to see if the sparse package is installed properly then.

Wild, but if they did that... Main issue there is that we don't have ARM machine so we'll need a lot of tests, direct x64 usage or ARM64 or ARMX or whatever. @rednoah are you interested enough in the GUI Win11 integration for doing theses tests?

**Comment by rednoah** [comment]
I can help out. Off for today but I should be able to run a few tests every 1-2 days at least.

**Comment by cjee21** [comment]
> > > I am not surprised, I doubt the integrated the support of calling another arch. They already did not do that for x64 with x86. We'll have to compile the ARM64 version of the DLL. But I think that it won't be a big deal there.
> > 
> > 
> > I saw [this](https://answers.microsoft.com/en-us/windows/forum/all/how-are-x86-shell-extensions-able-to-run-on-arm64/cb223cb8-a03e-4d44-ab29-ccd25082a0e2) so I thought it would work. Just need to see if the sparse package is installed properly then. If yes then we'll only need to build ARM64 DLLs.
> 
> `Get-AppxPackage MediaInfo` works:
> 
> ```
> PS D:\Test> Get-AppxPackage MediaInfo
> 
> 
> Name              : MediaInfo
> Publisher         : CN=MEDIAAREA.NET, O=MEDIAAREA.NET, L=Curienne, S=Auvergne-Rhône-Alpes, C=FR
> Architecture      : Neutral
> ResourceId        :
> Version           : 24.11.1202.0
> PackageFullName   : MediaInfo_24.11.1202.0_neutral__0z25jj8eabac0
> InstallLocation   : C:\Program Files\WindowsApps\MediaInfo_24.11.1202.0_neutral__0z25jj8eabac0
> IsFramework       : False
> PackageFamilyName : MediaInfo_0z25jj8eabac0
> PublisherId       : 0z25jj8eabac0
> IsResourcePackage : False
> IsBundle          : False
> IsDevelopmentMode : False
> NonRemovable      : False
> IsPartiallyStaged : False
> SignatureKind     : Developer
> Status            : Ok
> ```

Thank you. Good to know that at least the package is installed successfully. So likely Windows 11 has emulation for x86 shell extensions on ARM64 but not for x64 shell extensions.

> Main issue there is that we don't have ARM machine so we'll need a lot of tests,

Just need one test after making ARM64 DLLs. I have an idea how to make everything ARM64 except the GUI and plugins. That is if you are willing to build more DLLs and an installer for ARM64.

**Comment by JeromeMartinez** [comment]
> That is if you are willing to build more DLLs and an installer for ARM64.

We do, let's finish that as we are there with everyone motivated.

>  except the GUI and plugins

My current idea is to move to ARM64X after we finish ARM64, for every project but the GUI (impossible due to C++ Builder limitation) and the CLI (it can stay ARM64, no need of ARM64X with it, whatever is the direction of the compatibility layer)

**Comment by cjee21** [comment]
> We do, let's finish that as we are there with everyone motivated.

My plan...

MediaInfo.exe (GUI) - x64
MediaInfo.dll - ARM64X
MediaInfo_InfoTip.dll - ARM64
MediaInfo_WindowsShellExtension.dll - ARM64
MediaInfo_PackageHelper.dll - x86
WebView2Loader.dll - x64
LIBCURL.DLL - ARM64X or ARM64EC or x64

Need to wait till the ARM64 PRs are done first of course.

**Comment by JeromeMartinez** [comment]
> MediaInfo.dll - ARM64X

Note that there is another possibility: Keeping MediaInfo.dll as pure ARM64 and using a [ARM64x pure forwarder DLL](https://learn.microsoft.com/en-us/windows/arm/arm64x-build#building-an-arm64x-pure-forwarder-dll), my understanding is that it would be even more lightweight as we don't need to have anything else than the MediaInfo API compatible with x64 & ARM64.

> LIBCURL.DLL - ARM64X or ARM64EC or x64
FFmpeg/Graph plugins - ARM64X or ARM64EC or x64

My understanding is that ARM64 is enough for both as it is used by MediaInfo DLL only and in ARM64 mode.

**Comment by cjee21** [comment]
If anyone wants to go deeply into Windows + ARM64, here are some resources I found:
http://www.emulators.com/docs/abc_arm64ec_explained.htm
https://devblogs.microsoft.com/oldnewthing/20220726-00/?p=106898

**Comment by JeromeMartinez** [comment]
> This requires both ARM64 and x64/ARM64EC DLLs to forward to from my understanding. Total 3 DLLs and double size. ARM64X combines ARM64 and ARM64EC while only having a single copy of similar codes.

Possible that I misunderstood the page, no "translation" from x86 to ARM with the forwarder, OK. So let's keep the idea of ARMX for the DLLs.
