### ISSUE TITLE
Mediainfo return inaccurate metadata with S3 Pre-signed URL

### ISSUE THREAD

**Issue by changma2** [MediaArea/MediaInfoLib#2014]
Hi there, this is a separate issue with pre-signed url, we are trying to extract metadata on a tiff file, the version we are using is v23.01, when we use pre-signed url, the mediainfo is returning the metadata as an audio file, but when we download the file and extract in local with v24.01, we are getting the correct info as image. In order to rule out the version issue, we created a pre-signed url and tried with local v24.01 mediainfo and we are getting audio type again. I cannot attach tiff file here because of the file extension, but I will attach a 12 hr s3 signed-url, so you can download to your local and try it out. The file type for this file should be image.

**Comment by JeromeMartinez** [comment]
> when we download the file and extract in local with v24.01, we are getting the correct info as image

It is because we prioritize the TIFF parser when we have the extension on the local file, and not when we get the file remotely.
One of 2 potential fixes are needed (and implementing both would be even better):
- Fix the MPEG audio parser for not synching with this content
- Prioritizing the parsers depending on the file extension even for remote files.

**Comment by JeromeMartinez** [comment]
> I cannot attach tiff file here because of the file extension

I downloaded the file but for uour information you may just append .txt to the filename and GitHub considers it as acceptable.
(and at the same time MediaInfo behaves same locally as with remote content with this extension)

**Comment by changma2** [comment]
@JeromeMartinez Tried by adding .txt to the file extension and it worked with pre-signed url, thank you. But question is why it is working fine for most of the tiff(with pre-signed url), but just some not working, like this one.

**Comment by JeromeMartinez** [comment]
> But question is why it is working fine for most of the tiff(with pre-signed url), but just some not working, like this one.

For this file the MPEG Audio parser catches the stream because it found MPEG Audio patterns. Not the case of other files, such catch being "random" (depending of "luck" if the TIFF content has so bits similar to MPEG Audio).
i.e. false positive catches.

**Comment by changma2** [comment]
@JeromeMartinez Thanks for the explanation, then I think we know this is a known issue and for immediate mitigation we will have the check on all tiff files and if it failed we can try adding the extension and retry. Thanks a lot.

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/2016) by moving the MPEG Audio parser after the TIFF parser (making the MPEG Audio parser having less false positives would be longer to develop).
You can test with [dev snapshots](https://mediaarea.net/download/snapshots/binary) (mediainfo for Windows and macOS, libmediainfo0 for Linux).

**Comment by JeromeMartinez** [comment]
> Is it because of similar reason? 

Maybe. For being sure, on local drive append ".txt" to the file name and run locally MediaInfo.
But without the video format name I can not see what to do.

**Comment by changma2** [comment]
I tried add .txt extension, but seems not working on this one, I replied on the other thread about the content sharing conversation with our security team, will share this one together with the other files. Thank you again for your prompt support.
