### ISSUE TITLE
mediainfo: segmentation fault with multiple Dolby Vision HEVC Blu-Ray clips

### ISSUE THREAD

**Issue by bconway** [MediaArea/MediaInfoLib#2045]
Other files can be inspected without issue, and these files worked at some time in the past (don't recall the version number, sorry). The files play without issue, and were created as test clips from Blu-Ray rips using `mkvmerge`. Installation is on macOS Sonoma on Apple M1 with the latest release on Homebrew.

```
$ mediainfo --Version
MediaInfo Command line, 
MediaInfoLib - v24.04
```

```
$ mediainfo segfault1.mkv 
zsh: segmentation fault  mediainfo segfault1.mkv
$ mediainfo segfault2.mkv 
zsh: segmentation fault  mediainfo segfault2.mkv
```

https://www.dropbox.com/scl/fi/tdk3en8ojf2jeevwpjznk/segfault1.mkv?rlkey=dd47j4un4pfgbp0jnnssll3mg&st=hlp50n1s&dl=0

https://www.dropbox.com/scl/fi/pw11f4xtdq41l8fnhwxl9/segfault2.mkv?rlkey=j2z1auclyafauv6u3e1sglrk9&st=w0oclcz5&dl=0

Let me know if I can provide additional information.

**Comment by JeromeMartinez** [comment]
Maybe a duplicate of https://github.com/MediaArea/MediaInfoLib/issues/2047, please try  [development snapshots](https://mediaarea.net/download/snapshots/binary/).

**Comment by bconway** [comment]
That seems to work fine, thank you.
