### ISSUE TITLE
no Timecode Readout with Sony FX3 XAVC mp4

### ISSUE THREAD

**Issue by se-wi** [MediaArea/MediaInfoLib#2094]
Issue: MediaInfo cannot read the Timecode of a Sony XAVC-Intra mp4 Video

[sewi_Test_Fallers_Clip33_Contai_30_Jahre_Fallers_08_0_0033.MP4.MediaInfo.txt](https://github.com/user-attachments/files/16190177/sewi_Test_Fallers_Clip33_Contai_30_Jahre_Fallers_08_0_0033.MP4.MediaInfo.txt)

i know that the file includes Timecode because ffprobe 6.0 is able to extract:
[sewi_Test_Fallers_Clip33_Contai_30_Jahre_Fallers_08_0_0033.txt](https://github.com/user-attachments/files/16190255/sewi_Test_Fallers_Clip33_Contai_30_Jahre_Fallers_08_0_0033.txt)

i can provide an example video from the Sony Camera.

**Comment by JeromeMartinez** [comment]
[Stupid typo](https://github.com/MediaArea/MediaInfoLib/pull/2093/files) :(, you may test the fix with [development snapshots](https://mediaarea.net/download/snapshots/binary/).

**Comment by se-wi** [comment]
Thank you Jerome, you fixed both the TC Problems of XAVC Files, even the problem with semicolon instead of colon before the frames of another XAVC p50 example 
it was 
Time code of first frame : 02:49:46;02 
instead of 
Time code of first frame : 02:49:46:02 

many thanks to you!
sewi
