### ISSUE TITLE
[MPEG7] Incorrect output in strict mode when activating collection detection

### ISSUE THREAD

**Issue by tledoux** [MediaArea/MediaInfoLib#2097]
When outputting MPEG-7_Strict while activating collection (--Collection_Trigger=0 --Collection_Display=supported) for DVD in particular, the XML generated is not valid because it includes comments within comments.
The comment giving the ColorSampling (<mpeg7:ColorSampling> ) is included in the
"More than 1 track" comment.

Indeed, the count of tracks in MPEG7Strict is limited to one, so the others are in comments.
But when collections are used, every new Content can have its own VisualCoding and AudioCoding. 
So the first one of each Content shouldn't be commented out.

**Comment by JeromeMartinez** [comment]
Fix available in [development snapshots](https://mediaarea.net/download/snapshots/binary/).
Do you need a backport to a specific version (which one)?

**Comment by tledoux** [comment]
Hi, thanks for the quick correction. No specific need for a version, we can use the development snapshots until next "official" version is out. Best regards
