### ISSUE TITLE
Read timecode and other header info from EXR files

### ISSUE THREAD

**Issue by electron-rotoscope** [MediaArea/MediaInfoLib#2130]
I'm not sure if there's a better place to add feature requests, but it would be great if MediaInfo could read timecode data and more of the header information strings from ACES EXR files. The one I'm looking at is timecode 19:24:55:23, and has a section that reads in a hex editor
74 69 6D 65 43 6F 64 65 00 74 69 6D 65 63 6F 64 65 00 08 00 00 00 23 55 24 19
Which translates in ANSI to
timeCode.timecode [0x00 08 00 00 00] and then the count in frames, then seconds, then minutes, then hours

I'll try to get an example file I can upload

**Comment by JeromeMartinez** [comment]
@joelBrun it is [on the way](https://github.com/MediaArea/MediaInfoLib/pull/2131):

```
Frame rate                               : 23.976
Time code                                : 00:59:52:00
```

**Comment by JeromeMartinez** [comment]
@electron-rotoscope 

> Which translates in ANSI to
timeCode.timecode [0x00 08 00 00 00] and then the count in frames, then seconds, then minutes, then hours

FYI this is not what is in OpenEXR source code and not what is in the file provided by @joelBrun.
(little endian 32-bit 21HHhhhh0MMMmmmmfSSSsssscdFFffff style then 32-bit binary groups)
