### ISSUE TITLE
TTML Media Time Calculation Incorrect

### ISSUE THREAD

**Issue by joe-sciame-wm** [MediaArea/MediaInfoLib#2133]
Hi Jerome,

Looking at TTML Media Time calculations and they are incorrect.  From what I can tell, Media Info appears to be taking values at face value instead of calculating timecode from mediatime.

```
<p style="style.center" region="region.after" begin="01:00:10:16" end="01:00:12:04"><span tts:fontStyle="italic">text</span></p>
<p style="style.center" region="region.after" begin="01:27:19:04" end="01:27:20:22">text</p>
```
Frame Rate is 23.976 and timebase is media. Checking a couple of other caption tools and importing these files into those tools agree with the expected value that i'm calculating.

**Expected**:
Start: 01:00:07:01
End: 01:27:15:16

Result returned:

```
Start time                               : 3614277
Start time                               : 1 h 0 min
Start time                               : 1 h 0 min 14 s 277 ms
Start time                               : 1 h 0 min
Start time                               : 01:00:14.277
Start time                               : 01:00:10:16
Start time                               : 01:00:14.277 (01:00:10:16)
End time                                 : 5246158
End time                                 : 1 h 27 min
End time                                 : 1 h 27 min 26 s 158 ms
End time                                 : 1 h 27 min
End time                                 : 01:27:26.158
End time                                 : 01:27:20:22
End time                                 : 01:27:26.158 (01:27:20:22)
Time code of first frame                 : 01:00:10:16
Time code of last frame                  : 01:27:20:21
```

I'll send file offline.

**Comment by JeromeMartinez** [comment]
> Media Info appears to be taking values at face value instead of calculating timecode from mediatime.

I don't get whey it is wrong, the first begin is 01:00:10:16 and the last end is 01:27:20:22, how do you guess 01:00:07:01 and 01:27:15:16?
From what you provided it, if it is first and last elements this is the intended behavior.

> I'll send file offline.

I only need the elements you use in your guess of the outcome, no need of the full content.

**Comment by joe-sciame-wm** [comment]
Hi Jerome,

Here are the elements that are first and last lines.
```

<p style="style.center" region="region.after" begin="01:00:10:16" end="01:00:12:04"><span tts:fontStyle="italic">Multi-Man 2</span></p>
<p style="style.center" region="region.after" begin="01:27:19:04" end="01:27:20:22">Sous-titrage : VSI - Paris</p>
```

The values in the TTML are to be interpreted by mediatime given ttp:timeBase="media" so the timecode value has to be converted from mediatime to timecode.

**Comment by JeromeMartinez** [comment]
@joe-sciame-wm I still don't get how you change e.g. "01:00:10:16" from the file to "01:00:07:01" from your expected output, please explain the maths behind this conversion.

**Comment by joe-sciame-wm** [comment]
Hi Jerome,

We use the mediatime calculation from the TTML2 specification to get value in seconds.

`M = referenceBegin + 3600 * hours + 60 * minutes + seconds + ((frames + (subFrames / subFrameRate)) / effectiveFrameRate)`

Convert the value into seconds.

01:00:10:16 = 3610.6673333333333

Then we calculate the timecode from the duration in seconds by calculating the number of frames.

```
frames_float = seconds * framerate.float()
if mode == 'closest':
    frame_number = int(round(frames_float))
```

Then frame number (86569) is what we use to produce the timecode. internally our library treats everything as frames.

<img width="474" alt="image" src="https://github.com/user-attachments/assets/a0cbecb3-fcbf-47b8-84c5-cf2bc6b0d7b5">

**Comment by JeromeMartinez** [comment]
@joe-sciame-wm Thank you for the explanation, we missed [I.2 Media Time Base](https://www.w3.org/TR/2018/REC-ttml2-20181108/#time-expression-semantics-media) we are handling every `clock-time` as `smpte`.
It is a bit crazy that we have to do some rounding here, anyway it is the spec...

Do you need another mode than "closest"? We plan to implement "closest" only.

**Comment by joe-sciame-wm** [comment]
Hi Jerome,

Our code uses closest so that would be correct.

**Comment by JeromeMartinez** [comment]
> I was testing out the latest snapshot from 11/2 and it did not calculate correctly.

It was merged on Nov 2 after the Nov 2 snapshot, later snapshots should be OK.
