### ISSUE TITLE
Add Amazon S3 tests to Travis

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfoLib#214]
There is a need to verify that Amazon S3 support is not broken after each commit.

On Windows, I do something like:
```
@echo off

call:MI_S3 travis-standard.s3.amazonaws.com
call:MI_S3 s3.amazonaws.com/travis-standard

call:MI_S3 travis-oregon.s3.amazonaws.com
call:MI_S3 travis-oregon.s3-us-west-2.amazonaws.com
call:MI_S3 s3-us-west-2.amazonaws.com/travis-oregon

call:MI_S3 travis-frankfurt.s3.amazonaws.com
call:MI_S3 s3-eu-central-1.amazonaws.com/travis-frankfurt
call:MI_S3 travis-frankfurt.s3.eu-central-1.amazonaws.com
call:MI_S3 s3-eu-central-1.amazonaws.com/travis-frankfurt
call:MI_S3 s3.eu-central-1.amazonaws.com/travis-frankfurt

GOTO:EOF

:MI_S3
set Result=
if exist tmp del tmp
mediainfo https://%Amazon_AccessKeyID%:%Amazon_SecretAccessKey%@%~1/Example.ogg "--Output=General;%%Format%%" > tmp
set /p Result= <tmp
del tmp
if "%Result%" EQU "Ogg" (set Result= OK) else (set Result=NOK)
echo %Result% : %~1
GOTO:EOF
```

Result is something like:
```
 OK : travis-standard.s3.amazonaws.com
 OK : s3.amazonaws.com/travis-standard
 OK : travis-oregon.s3.amazonaws.com
 OK : travis-oregon.s3-us-west-2.amazonaws.com
 OK : s3-us-west-2.amazonaws.com/travis-oregon
 OK : travis-frankfurt.s3.amazonaws.com
 OK : s3-eu-central-1.amazonaws.com/travis-frankfurt
 OK : travis-frankfurt.s3.eu-central-1.amazonaws.com
 OK : s3-eu-central-1.amazonaws.com/travis-frankfurt
 OK : s3.eu-central-1.amazonaws.com/travis-frankfurt
```

Should be added to Travis tests suite.
Key and Pass should be tied to the official repo and encrypted, see [Travis Encrypted-Variables)](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables.

**Comment by g-maxime** [comment]
So we need mediainfo binary in the travis environment... The one from the .deb package will not cause any problem?

**Comment by JeromeMartinez** [comment]
> So we need mediainfo binary in the travis environment...

There is [a glue in the test folder](https://github.com/MediaArea/MediaInfoLib/blob/master/Project/GNU/Library/test/Source/analyze.cpp), adapting it (i.e. move [hard-coded options](https://github.com/MediaArea/MediaInfoLib/blob/master/Project/GNU/Library/test/Source/analyze.cpp#L84-L87) to the script in order to have it more generic, and reuse it in several scripts) would be better than install ine mediainfo CLI .deb.

**Comment by g-maxime** [comment]
https://github.com/MediaArea/MediaInfoLib/commit/4ad4d6aea51d992ba508ebed3bd51c49e8912671
