### ISSUE TITLE
support mkv:FieldOrder in MediaTrace

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaInfoLib#240]
see https://github.com/dericed/matroska-specification/blob/gh-pages/ebml_matroska.xml#L279

**Comment by JeromeMartinez** [comment]
do you have a sample file?

**Comment by dericed** [comment]
`ffmpeg -f lavfi -i testsrc -vf setfield=tff -frames:v 1 tff.mkv` via a modern ffmpeg.

**Comment by dericed** [comment]
Might as well as some color data in there too,
`ffmpeg -f lavfi -i testsrc -vf setfield=tff,colormatrix=bt601:bt709 -frames:v 1 -strict experimental tff_bt709.mkv`

**Comment by dericed** [comment]
fix for color example:

`ffmpeg -f lavfi -i testsrc -frames:v 1 -color_primaries 1 -strict experimental hey1.mkv`

**Comment by JeromeMartinez** [comment]
https://github.com/MediaArea/MediaInfoLib/pull/241
