### ISSUE TITLE
File_Hevc::Streams_Fill

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#262]
Strange expression:
chroma_sample_loc_type_bottom_field!=chroma_sample_loc_type_bottom_field

    if (chroma_sample_loc_type_top_field!=(int32u)-1)
        Fill(Stream_Video, 0, "ChromaSubsampling_Position", __T("Type ") + Ztring::ToZtring(chroma_sample_loc_type_top_field));
    if (chroma_sample_loc_type_bottom_field!=(int32u)-1 && chroma_sample_loc_type_bottom_field!=chroma_sample_loc_type_bottom_field)
        Fill(Stream_Video, 0, "ChromaSubsampling_Position", __T("Type ") + Ztring::ToZtring(chroma_sample_loc_type_bottom_field));

**Comment by JeromeMartinez** [comment]
should be 

    if (chroma_sample_loc_type_top_field!=(int32u)-1)
    {
        Fill(Stream_Video, 0, "ChromaSubsampling_Position", __T("Type ") + Ztring::ToZtring(chroma_sample_loc_type_top_field));
        if (chroma_sample_loc_type_bottom_field!=(int32u)-1 && chroma_sample_loc_type_bottom_field!=chroma_sample_loc_type_top_field)
            Fill(Stream_Video, 0, "ChromaSubsampling_Position", __T("Type ") + Ztring::ToZtring(chroma_sample_loc_type_bottom_field));
    }
