### ISSUE TITLE
File_Mpeg4v::video_object_layer_start()

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#263]
//Coherancy
    if (shape!=2 && shape==0 && (object_layer_width==0 || object_layer_height==0 || ((float32)object_layer_width)/object_layer_height<((float32)0.1) || object_layer_width/object_layer_height>10))
        Trusted_IsNot("Problem with width and height!");

Remove shape!=2 ?

**Comment by JeromeMartinez** [comment]
Should be removed
