### ISSUE TITLE
Diff PreprocessorDefinitions vc++2015 vc++ 2013

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#265]
![mediainfo-diff-2015-2013](https://cloud.githubusercontent.com/assets/920705/19717829/243d20da-9b6b-11e6-9543-c09bd960ce01.png)

**Comment by JeromeMartinez** [comment]
Hum... It is time to have something more coherent, right.
Should be 

    MEDIAINFO_LIBCURL_DLL_RUNTIME;%(PreprocessorDefinitions)

Everywhere (for other defines, I'll change that in setup.h if needed, in order to have the default behavior on all platforms)
