### ISSUE TITLE
bool File_Vc1::Demux_UnpacketizeContainer_Test()

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#266]
for (; Header_End<Demux_Offset; Header_End++)
                    if (Buffer[Header_End  ]==0x00
                     && Buffer[Header_End+1]==0x00
                     && Buffer[Header_End+2]==0x01
                     && Buffer[Header_End+2]==0x0D)

Buffer[Header_End+2]==0x0D ->  Buffer[Header_End+3]==0x0D ?

**Comment by JeromeMartinez** [comment]
Ouch. Yes.

**Comment by pavel-pimenov** [comment]
Create PR or close issue?

**Comment by JeromeMartinez** [comment]
Create PR for all bugs you find, please.
