### ISSUE TITLE
Call strlen(nullptr)

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#273]
int element_details::Element_Node::Print_Tree(
...
int nb_free = NB_SPACES - level - (Name ? 0 : strlen(Name)); // 40 - len(Name) - len(spaces)

**Comment by JeromeMartinez** [comment]
@tribouille shouldn't it (Name ? strlen(Name) : 0)?
(and how did I miss that... I'll test it after it is changed)

**Comment by tribouille** [comment]
yep
