### ISSUE TITLE
File_Als: BitsPerSample+1/8

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#301]
https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Audio/File_Als.cpp#L118
UncompressedSize=((int64u)Samples)*Channels*(BitsPerSample+1/8);

Bug?

UncompressedSize=((int64u)Samples)*Channels*((BitsPerSample+1)/8);

**Comment by JeromeMartinez** [comment]
Oops... yes. Weird I did not see it in the results. Will test first the behavior with my sample files.

**Comment by JeromeMartinez** [comment]
OK, I spoke too quickly: 
For ALS, "BitsPerSample" is actually in bytes, so should be:
CalcDurationUncompressedSize(Samples, SampleRate, (BitsPerSample+1)*8, Channels)

Note: it was previously buggy (the result was wrong), but the "fix" is also wrong.
