### ISSUE TITLE
unused bitstream_restriction_struct

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#312]
https://github.com/MediaArea/MediaInfoLib/search?utf8=%E2%9C%93&q=bitstream_restriction_struct
https://github.com/MediaArea/MediaInfoLib/search?utf8=%E2%9C%93&q=bitstream_restriction

Remove?

**Comment by JeromeMartinez** [comment]
It is used by a non open source code, but right it could be removed from the open source version.

**Comment by pavel-pimenov** [comment]
Remove or #ifdef MEDIAINFO_... for simple merge?

**Comment by JeromeMartinez** [comment]
remove, it will be in the diff for them.
