### ISSUE TITLE
missing Matroska Elements

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaInfoLib#320]
I'm looking at https://github.com/MediaArea/MediaInfoLib/blob/40152d7d5a6a0503f87c2081f197922079b3b276/Source/MediaInfo/Multiple/File_Mk.cpp and see several Matroska Elements missing. Including:

# Cues
- CueCodecState
- CueReference
- CueRefTime
- CueRefCluster
- CueRefNumber
- CueRefCodecState

# Chapters
- ChapterStringUID

# Clusters
- BlockAdditionID
- FrameNumber
- Delay
- SliceDuration
- ReferenceFrame
- ReferenceOffset
- ReferenceTimeCode
- EncryptedBlock

# Tracks
- DefaultDecodedFieldDuration
- CodecDelay
- SeekPreRoll
- TrackTranslateCodec
- AlphaMode
- OldStereoMode
- GammaValue
- ChromaSubsamplingHorz
- ChromaSubsamplingVert
- CbSubsamplingHorz
- CbSubsamplingVert
- ChromaSitingHorz
- ChromaSitingVert
- MaxCLL
- MaxFALL
- MasteringMetadata
- PrimaryRChromaticityX
- PrimaryRChromaticityY
- PrimaryGChromaticityX
- PrimaryGChromaticityY
- PrimaryBChromaticityX
- PrimaryBChromaticityY
- WhitePointChromaticityX
- WhitePointChromaticityY
- LuminanceMax
- LuminanceMin
- ChannelPositions
- TrackOperation
- TrackCombinePlanes
- TrackPlane
- TrackPlaneUID
- TrackPlaneType
- TrackJoinBlocks
- TrackJoinUID
- TrickTrackUID
- TrickTrackSegmentUID
- TrickTrackFlag
- TrickMasterTrackUID
- TrickMasterTrackSegmentUID

Also [this line](https://github.com/MediaArea/MediaInfoLib/blob/40152d7d5a6a0503f87c2081f197922079b3b276/Source/MediaInfo/Multiple/File_Mk.cpp#L178) it says `Duration` maybe it means `SliceDuration`.

Another typo in [this line](https://github.com/MediaArea/MediaInfoLib/blob/40152d7d5a6a0503f87c2081f197922079b3b276/Source/MediaInfo/Multiple/File_Mk.cpp#L302), should be `TrackTranslateCodec`, not `Codec`.

Typo in this [line](https://github.com/MediaArea/MediaInfoLib/blob/40152d7d5a6a0503f87c2081f197922079b3b276/Source/MediaInfo/Multiple/File_Mk.cpp#L299). Should be `OldStereoMode` not `StereoModeBuggy`.

**Comment by dericed** [comment]
status?

**Comment by JeromeMartinez** [comment]
implemented via https://github.com/MediaArea/MediaInfoLib/pull/525
