### ISSUE TITLE
mi_input and mi_output memory leak

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#343]
https://github.com/MediaArea/MediaInfoLib/blob/9c77babfa699347c4ca4a79650cc1f3ce6fcd6c8/Source/MediaInfoDLL/MediaInfoDLL.cpp#L61-L62

Creat PR: ?

-typedef std::map<void*, mi_output*> mi_outputs;
+typedef std::map<void*, mi_output> mi_outputs;
  struct mi_input
 {
     Ztring Unicode[8];  //Unicode characters multiple times
 };
-typedef std::map<void*, mi_input*> mi_inputs;
+typedef std::map<void*, mi_input> mi_inputs;

**Comment by JeromeMartinez** [comment]
hum... I don't see any reason it is a pointer (Ztring constructor would be called more often but it is nothing), so OK on the idea, I prefer to avoid any memory eak so debugging is easier when we need to find a bigger memory leak.

**Comment by pavel-pimenov** [comment]
ok
