### ISSUE TITLE
V756 The 'y' counter is not used inside a nested loop.

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#373]
V756 The 'y' counter is not used inside a nested loop. Consider inspecting usage of 'c' counter. file_ffv1.cpp 1278

![default](https://cloud.githubusercontent.com/assets/920705/22109982/217c0c9c-de6b-11e6-9273-7eca0cc771c0.png)

**Comment by JeromeMartinez** [comment]
false positive, this is the intended code, 'c' is correct everywhere and the swap (with c) must be done y times.
