### ISSUE TITLE
[crash] MediaInfo_Internal::Open_Buffer_Init

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#390]
https://drdump.com/Problem.aspx?ProblemID=265378&Login=Guest

![default](https://cloud.githubusercontent.com/assets/920705/22882903/7b06217a-f1fe-11e6-92af-9978750d1b5e.png)

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/561ea219c6f097e1fca6877ba34c232d543cc13b)
