### ISSUE TITLE
DTS-HD MA audio files don't have the "core" duration field

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#455]
https://github.com/MediaArea/MediaInfo/files/880803/hd_dthd_7.1_track2_ger_TrueHD.thd.txt
[hd_dtsma_7.1_DTS.dts.txt](https://github.com/MediaArea/MediaInfoLib/files/889953/hd_dtsma_7.1_DTS.dts.txt)

The duration is used in the DIDL string while streaming media over DLNA.
It's also used to calculate approximately the trancoded file size that need to be send in the DIDL-Lite string as well.

**Comment by JeromeMartinez** [comment]
They are VBR files, without any index or timestamp.
It is impossible to find duration without parsing the whole file (in order to count the frames 1 per 1).
Is loading the whole file not a problem for your goal?

**Comment by Sami32** [comment]
Thank you for your insight :)

If we don't give a duration and size it'll not play, but it's inacurate the search capabilities will not work or incorrectly/partially.
To avoid delay and HDD space the stream is sended by the video engine directly to the renderer via a pipe.

That's said, these kind of files are not popular, so our workaround should be "fine".

**Comment by Sami32** [comment]
DTS-HS is displayed as CBR. is that normal ?

**Comment by JeromeMartinez** [comment]
I see "VBR / CBR", this is due to the "Core" part being CBR, and "HD" part being VBR. If you "un-interleave" and remove the HD part, you would have a CBR stream at 1509 kb/s ("Unknown / 1509000" indicated in the bitrate part).

**Comment by Sami32** [comment]
Should it be possible to get the "core" duration displayed in the case of DTS-HD MA files ?

**Comment by JeromeMartinez** [comment]
The "Core" part is interleaved with the "HD" part so you can not computer the duration from only File size and "Core" part bitrate.

**Comment by JeromeMartinez** [comment]
there is no "Core duration and HD duration", there is only one duration. The title is invalid.

**Comment by Sami32** [comment]
OK, thank for taking time to explain me :smile:
