### ISSUE TITLE
CLI doesn't show color matrix

### ISSUE THREAD

**Issue by rhazor** [MediaArea/MediaInfoLib#466]
```
mediainfo --Inform=Video;%matrix_coefficients% color_matrix-sample.mkv
%matrix_coefficients%
```

[5 second 2MB video sample (Zippyshare)](http://www52.zippyshare.com/v/qEs4iEK6/file.html)
(sample cannot be attached attached because of limited format support.)

**Comment by JeromeMartinez** [comment]
Will be available tomorrow in [snapshots](https://mediaarea.net/download/snapshots/binary/).

**Comment by rhazor** [comment]
I'm on Windows, I don't know how to compile this to executable.

**Comment by JeromeMartinez** [comment]
As said in the previous comment, it will be available in snapshots tomorrow or you wait for next release.
If you are in hurry and absolutely need it today, let us know (not free support).

**Comment by rhazor** [comment]
Is there a date for next release?

**Comment by JeromeMartinez** [comment]
> Is there a date for next release?

End of month, in theory.
but you could use the snapshot (it is same binary, just less tests on it) tomorrow too.
