### ISSUE TITLE
AAC and ALS / SLS codecs have the same ID

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#473]
I just find that surprising, that doesn't mean that it's a bug though.
AAC/HE-AAC and ALS have the same "40" codec ID.

[luckynight-ALS.mp4.txt](https://github.com/MediaArea/MediaInfoLib/files/907188/luckynight-ALS.mp4.txt)

**Comment by JeromeMartinez** [comment]
Complicated, identifier can come from ObjectTypeIndication or audioObjectType, they are 2 different lists and 40 is possible depending of which list is used.

I guess I need to better show the origin of the codec id.

**Comment by Sami32** [comment]
That's said, now i'm not sure anymore that worst the effort, so feel free to close this issue.
As we can always parse these files correctly using the others MediaInfo fields.

Thanks for have taken the time to explain me :)

**Comment by JeromeMartinez** [comment]
Let have it still open, something should be changed.

**Comment by Sami32** [comment]
OK. In fact i discovered that it apply to SLS as well.

As a side note, i was not able to found the `program_config_element()` field in the _MediaInfo_ parsing. I don't know if it is a deliberate choice from your side, but in the AAC specifications they say that they use this field, and others that you've already implemented, to identify the AAC profile.

**Comment by JeromeMartinez** [comment]
> As a side note, i was not able to found the program_config_element() field in the MediaInfo parsing. 

In [File_Aac_GeneralAudio.cpp](https://github.com/MediaArea/MediaInfoLib/blob/d98821368a6bbbac94233cfc0ceeb22fc4386aa9/Source/MediaInfo/Audio/File_Aac_GeneralAudio.cpp#L110).

**Comment by Sami32** [comment]
Thank you, i only searched in the results parsing file, i guess that explain why ;)

**Comment by Sami32** [comment]
Have been fixed in 0.7.99.
