### ISSUE TITLE
Possible bug in RealAudio 1.0/v3 parsing

### ISSUE THREAD

**Issue by Nadahar** [MediaArea/MediaInfoLib#474]
I'm not familiar enough with C++ or your code to be certain, but [this line](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Rm.cpp#L486) looks like a bug to me. 

AFAIK there is not duration available in this header, it must be calculated/estimated (FFmpeg simply uses bitrate and data size). If see that there's no duration parsing in v4 and v5, so it was probably never intended to parse duration?

**Comment by JeromeMartinez** [comment]
Oops, typo, fixed.
thanks.
