### ISSUE TITLE
EXR file not recognized as image

### ISSUE THREAD

**Issue by bigzed** [MediaArea/MediaInfoLib#490]
This [sample](http://dl.flavoursys.com/samples/mediainfo/not_recognized.exr) is not properly recognized by MediaInfo. It is a valid EXR file, but MediaInfo does not recognized it as an image. I used the current git master to test this.
```
$ mediainfo -f bad_EV215_comp_output1_Flat_v020.0001.exr                                                 [11:59:48]
General
Count                                    : 325
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Complete name                            : bad_EV215_comp_output1_Flat_v020.0001.exr
File name                                : bad_EV215_comp_output1_Flat_v020.0001
File extension                           : exr
File size                                : 3696420
File size                                : 3.53 MiB
File size                                : 4 MiB
File size                                : 3.5 MiB
File size                                : 3.53 MiB
File size                                : 3.525 MiB
Stream size                              : 3696420
Stream size                              : 3.53 MiB (100%)
Stream size                              : 4 MiB
Stream size                              : 3.5 MiB
Stream size                              : 3.53 MiB
Stream size                              : 3.525 MiB
Stream size                              : 3.53 MiB (100%)
Proportion of this stream                : 1.00000
File last modification date              : UTC 2017-05-03 09:34:28
File last modification date (local)      : 2017-05-03 11:34:28
```

**Comment by JeromeMartinez** [comment]
Lot of tags in this file ;-).
OK, issue with tags having the maximum length, [fixed](https://github.com/MediaArea/MediaInfoLib/commit/c01687c784772e99e2d863813bab5fd58842df57).

Note: [at the same time](https://github.com/MediaArea/MediaInfoLib/pull/492), I added support of "long names" (more than 31 chars) and display of compression method as well as "Deep" and "Multipart" flags, I tried to add color space and chroma subsampling but it is long so I stop as there is currently no sponsor for it, so for a later time maybe.

**Comment by bigzed** [comment]
Thanks.

**Comment by gurka** [comment]
> Lot of tags in this file ;-). OK, issue with tags having the maximum length, [fixed](https://github.com/MediaArea/MediaInfoLib/commit/c01687c784772e99e2d863813bab5fd58842df57).
> 
> Note: [at the same time](https://github.com/MediaArea/MediaInfoLib/pull/492), I added support of "long names" (more than 31 chars) and display of compression method as well as "Deep" and "Multipart" flags, I tried to add color space and chroma subsampling but it is long so I stop as there is currently no sponsor for it, so for a later time maybe.

Is this LongName-handling according to specification? e.g. if flag not set then maximum name length is 31 otherwise it's 255? I'm trying to parse EXR-files generated from Unreal Engine 4 and they do not have this flag set, yet they have some very long tag names like `Unreal Camera Final Image Dof Diaphragm Blade Count`.

I noticed that `exiftool` parses the files correct, but I'm not sure how they handle long names...

**Comment by gurka** [comment]
The 4 bytes after the magic number (`0x762F3101`) in my file are: `0x02 0x04 0x00 0x00`.

`exiftool` reads all four bytes as `0x00000402` and then does `& 0xFF` to read version `= 2` and `& 0x400` to set LongName flag (`0x00000402 & 0x400 = 0x400 => true`).

`MediaInfoLib` does:

```
    Get_L3 (Flags,                                              "Flags");
        Skip_Flags(Flags, 0,                                    "Single tile");
        Get_Flags (Flags, 1, LongName,                          "Long name");
        Get_Flags (Flags, 2, Deep,                              "Non-image");
        Get_Flags (Flags, 3, Multipart,                         "Multipart");
```

I'm not entirely sure but it seems it should look at bit 2 for LongName and not bit 1? That is, unless `exiftool` is the one that is doing it wrong

**Comment by gurka** [comment]
diff which made it work better with the Unreal EXR files:

```
diff --git a/Source/MediaInfo/Image/File_Exr.cpp b/Source/MediaInfo/Image/File_Exr.cpp
index 92e0f8b6f..2accf7b24 100644
--- a/Source/MediaInfo/Image/File_Exr.cpp
+++ b/Source/MediaInfo/Image/File_Exr.cpp
@@ -118,10 +118,10 @@ void File_Exr::FileHeader_Parse()
     Skip_L4(                                                    "Magic number");
     Get_L1 (Version,                                            "Version field");
     Get_L3 (Flags,                                              "Flags");
-        Skip_Flags(Flags, 0,                                    "Single tile");
-        Get_Flags (Flags, 1, LongName,                          "Long name");
-        Get_Flags (Flags, 2, Deep,                              "Non-image");
-        Get_Flags (Flags, 3, Multipart,                         "Multipart");
+        Skip_Flags(Flags, 1,                                    "Single tile");^M
+        Get_Flags (Flags, 2, LongName,                          "Long name");^M
+        Get_Flags (Flags, 3, Deep,                              "Non-image");^M
+        Get_Flags (Flags, 4, Multipart,                         "Multipart");^M
 
     //Filling
     if (Frame_Count==0)
```
