### ISSUE TITLE
Crash File_Avc::Streams_Fill

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#498]
https://drdump.com/Problem.aspx?ProblemID=292291&login=guest

static const char* Avc_Colorimetry_format_idc[]=
{
    "monochrome",
    "4:2:0",
    "4:2:2",
    "4:4:4",
};
...
Fill(Stream_Video, 0, Video_Colorimetry, Avc_Colorimetry_format_idc[(*seq_parameter_set_Item)->chroma_format_idc]);

(*seq_parameter_set_Item)->chroma_format_idc > 3  ?

![default](https://cloud.githubusercontent.com/assets/920705/25963341/9b5dd8bc-3689-11e7-8b68-40b34f7db08f.png)

**Comment by JeromeMartinez** [comment]
yes (it is done elsewhere in the file).
Having the file would be great, as it is not expected (AVC is detected, but i guess it is not AVC so we should find a method for having the AVC parser not accepting this file)

**Comment by pavel-pimenov** [comment]
* remove Avc_Colorimetry_format_idc[]
* add help-function Avc_Colorimetry_format_idc(int8u) and return "Unknown" ?

https://github.com/MediaArea/MediaInfoLib/blob/4b233a15cec394ff5832c0d2b820377b87a3dae9/Source/MediaInfo/Video/File_Hevc.cpp#L87
static const char* Hevc_chroma_format_idc(int8u chroma_format_idc)
{
    switch (chroma_format_idc)
    {
        case   0 : return "monochrome";
        case   1 : return "4:2:0";
        case   2 : return "4:2:2";
        case   3 : return "4:4:4";
        default  : return "Unknown";
    }
}

**Comment by JeromeMartinez** [comment]
ok.

**Comment by pavel-pimenov** [comment]
i will create PR
