### ISSUE TITLE
standardize and support a trace export in xml

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaInfoLib#5]
Starting this ticket as a start to conversation surrounding efforts to define, document, and support a report of labelled file architecture in XML format (initially known as mediatrace xml).

MediaInfo 0.7.74 supports an initial alpha implementation of mediatrace xml. Please note this this xml report is under development and not intended for use in production. You can generate an xml report by this command:

```mediainfo --Details=1 --Output=XML yourfavoritedpxfilehere.dpx```

A sample XML produced from this dpx file: https://github.com/epiil/dpxderivatives/blob/master/DPX_sample/000001.dpx is available at https://gist.github.com/dericed/6d2efda11c16f00db207.

A few specific items to do in relation to the development of mediatrace XML:

- clarify the namespace, currently we have an xsd but the expression made from MI has no namespace associated to it

- considering adding select file attribute data. The XML refers to the contents of the file but not the file attributes, thus the XML does not, for instance, contain the name of the file. The scope of the mediatrace xml should focus primary on describing the contents of the file but think there are certain key pieces of metadata, such as the filename where we could expand that scope.

- consider better element names than item/items?

- a schema is drafted, but should it have a new repo or be incorporated into the MediaInfoLib repo?

**Comment by epiil** [comment]
With regard to element names, I propose that we use names that distinguish header information from raw data information, e.g,:

<headerElement></headerElement>
<dataElement></dataElement>

"Element" here refers to EBML parlance, FWIW.

**Comment by epiil** [comment]
With regard to element names, I propose that we use names that distinguish header information from raw data information, e.g, "headerElement" "dataElement" (Element here refers to EBML parlance, FWIW).

**Comment by jhsimpson** [comment]
+1 for considering betting element names (not items/item)
+1 for using a namespace
+1 to seeing the schema, I think it might be good to consider publishing the schema in its own repo, so it can be referenced separately from this code that produces xml that follows the schema.

**Comment by dericed** [comment]
Better element names: https://github.com/MediaArea/MediaInfoLib/commit/06f268d215cd5d8354e98b4b92df625fe2b395cf. <items> and <item> changed to <block> and <data>

Namespace added: https://github.com/MediaArea/MediaInfoLib/commit/d5f2a46c5908ee19e6b5479882df861f77e4eca1  See: https://mediaarea.net/mediatrace/

Schema published here https://mediaarea.net/mediatrace/mediatrace.xsd and under version control here https://github.com/mediaarea/mediatrace

And lots of other updates to get the output to be both comprehensive and sane. Documentation is at the namespace url.

cc @jhsimpson @finoradin
