### ISSUE TITLE
Crash  File__Tags_Helper::Finish

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#534]
https://drdump.com/DumpGroup.aspx?DumpGroupID=819217 (only stack dump)

![default](https://user-images.githubusercontent.com/920705/27150434-ed9ffff2-514f-11e7-9de3-7582c7f81882.png)

TTH = ZXCR7DQETMTRQGCX5CJZALKC3B2SH526RQNWTII 
File size = 5742563400
File name = Слоёный торт (Layer Cake) 2004 HDTV 1080i.ts

**Comment by JeromeMartinez** [comment]
Difficult to fix it without the file :(.

**Comment by pavel-pimenov** [comment]
ok.
