### ISSUE TITLE
Channels not detected in MPC files

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#535]
```
Audio
Format                                   : Musepack SV7
Duration                                 : 2 min 30 s
Bit rate                                 : 130 kb/s
Sampling rate                            : 44.1 kHz
Bit depth                                : 16 bits
Compression mode                         : Lossy
Stream size                              : 2.32 MiB (100%)
Writing library                          : 0.96 Beta
```

[01 - Pumpkin and Honey Bunny (dialogue) - Dick Dale & His Del-Tones , Misirlou.mpc.txt](https://github.com/MediaArea/MediaInfoLib/files/1078697/01.-.Pumpkin.and.Honey.Bunny.dialogue.-.Dick.Dale.His.Del-Tones.Misirlou.mpc.txt)

**Comment by JeromeMartinez** [comment]
[SV7](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Audio/File_Mpc.cpp) support is definitely poor, but no plan on our side to improve it.
Patch accepted ;-).

**Comment by Sami32** [comment]
Not that i don't want, but my C++ skill is too weak :(
If adding one line of code `Fill(Stream_Audio, 0, Audio_Channel_s_, Channels);`
was suffisant it'll be nice, because this i can do :wink: 

That's said, as a workaround i defined 2 channels as a default value ;)

**Comment by JeromeMartinez** [comment]
C++ is not the main issue. Main issue is where to locate the channel count in the bitstream. So... You can do it ;-), it is digging in spec (if it exists), questioning people, digging in other code.
If you are sure (link please) that SV7 is stereo only, `Fill(Stream_Audio, 0, Audio_Channel_s_, 2);` would be enough.

**Comment by Sami32** [comment]
To be honest i thought about it, stereo only, but didn't read any specifications yet. I'll check the FFmpeg code.
Thank you for you advices ;-)

**Note**: As i guess that will not deserve it's own issue, i prefer add here a RMVB (RealAudio Lossless) similar issue:
 
[luckynight.rmvb.txt](https://github.com/MediaArea/MediaInfoLib/files/1078820/luckynight.rmvb.txt)

**Comment by JeromeMartinez** [comment]
> i prefer add here a RMVB (RealAudio Lossless) 

I don't like that, because even if the result is same for both the reason and the answer I do, it is 2 different issues, not in the same container so not the same code to change.
Here, RMVB header does not contain any channel info, and "RALF" audio format is not supported.

**Comment by Sami32** [comment]
OK, i understand, i'll not do anymore.
