### ISSUE TITLE
Condition 'Speex_version_id==1' is always true

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#544]
Remove if (Speex_version_id==1)?

https://github.com/MediaArea/MediaInfoLib/blob/9c77babfa699347c4ca4a79650cc1f3ce6fcd6c8/Source/MediaInfo/Audio/File_Speex.cpp#L110

![default](https://user-images.githubusercontent.com/920705/27368964-340cfa2c-565e-11e7-83e3-417e299d5b6a.png)

**Comment by JeromeMartinez** [comment]
Oops, the first "Filling" block should be with the second one, I'll change that.
