### ISSUE TITLE
"ReadByHuman" set to "false" disable the "Duration"

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#563]
I could be wrong, but i suspect that it's not the expected output.
`MI.Option("ReadByHuman", "0");`

**Comment by JeromeMartinez** [comment]
Disable the duration how? No MediaInfo::Get(x, x, "Duration")?
If in "text" output, do you have also `MI.Option("Complete", "1");`?

**Comment by Sami32** [comment]
Yes.
```logtalk
MI.Option("Internet", "0");
MI.Option("Complete", "1");
MI.Option("Language", "raw");
MI.Option("File_TestContinuousFileNames", "0");
MI.Option("ParseSpeed", "1"); // For testing purpose with ADTS only, as normally set to 0
```

Trying to win a little speed, i also added:
```logtalk
MI.Option("ReadByHuman", "0");
MI.Option("Legacy", "0");
MI.Option("Verbosity", "0");
```

`EDIT`: Aaarrgh...My bad. I missed that we use `Duration/String1` in our code, it why the duration was not given. I didn't tested yet, but i'm confident that's the root of this "issue".
