### ISSUE TITLE
CMake building broken with (MinGW) GCC

### ISSUE THREAD

**Issue by wiiaboo** [MediaArea/MediaInfoLib#567]
This one I don't actually know how to fix.

```
C:/builds/ab/build/libmediainfo-git/Source/MediaInfo/Text/File_AribStdB24B37.cpp: In member function 'void MediaInfoLib::File_AribStdB24B37::aption_statement()':
C:/builds/ab/build/libmediainfo-git/Source/MediaInfo/Text/File_AribStdB24B37.cpp:744:72: error: cannot convert 'const char*' to 'const wchar_*' in assignment
             Event.Content=Streams[(size_t)(Element_Code-1)].Line.c_str();
                                                                        ^
[178/223] Building CXX object CMakeFiles/mediainfo.dir/C_/builds/ab/build/libmediainfo-git/Source/MediaInfo/Text/File_Eia608.cpp.o
In file included from C:/builds/ab/build/libmediainfo-git/Source/ThirdParty/aes-gladman/aescpp.h:26:0,
                 from C:/builds/ab/build/libmediainfo-git/Source/MediaInfo/File__Analyze.h:23,
                 from C:/builds/ab/build/libmediainfo-git/Source/MediaInfo/Text/File_Eia608.h:19,
                 from C:/builds/ab/build/libmediainfo-git/Source/MediaInfo/Text/File_Eia608.cpp:24:
C:/builds/ab/build/libmediainfo-git/Source/ThirdParty/aes-gladman/aes.h:85:3: warning: 'align' attribute directive ignored [-Wattributes]
 } aes_encrypt_ctx;
   ^~~~~~~~~~~~~~~
C:/builds/ab/build/libmediainfo-git/Source/ThirdParty/aes-gladman/aes.h:93:3: warning: 'align' attribute directive ignored [-Wattributes]
 } aes_decrypt_ctx;
   ^~~~~~~~~~~~~~~
```

**Comment by JeromeMartinez** [comment]
Is easy to fix for me, but looks like you try to build in non Unicode mode, I suggest to use Unicode mode (should be the configuration by default), better tested and supports better complex non-US character strings.

**Comment by wiiaboo** [comment]
Doesn't seem related to GCC 7.1 either, it also failed with 6.3.
Wasn't unicode mode always enabled?

**Comment by wiiaboo** [comment]
I don't see any option to enable or disable unicode in CMake projects.

**Comment by wiiaboo** [comment]
This seems to work, but I'm not confident enough if this is the right way to do this.

```diff
diff --git a/Project/CMake/CMakeLists.txt b/Project/CMake/CMakeLists.txt
index 9a714365..a13412a6 100644
--- a/Project/CMake/CMakeLists.txt
+++ b/Project/CMake/CMakeLists.txt
@@ -20,6 +20,8 @@ else()
   set(BUILD_SHARED_LIBS OFF)
 endif()

+option(UNICODE "Build unicode-enabled build" ON)
+
 set(LIB_SUFFIX "" CACHE STRING "Define suffix of directory name (32/64)" )
 set(BIN_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/bin" CACHE STRING "Directory where binary will install")
 set(LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib${LIB_SUFFIX}" CACHE STRING "Directory where library will install")
@@ -70,6 +72,10 @@ else()
   set(MediaInfoLib_CONFIG_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/cmake/")
 endif()

+if(UNICODE)
+  add_definitions(-DUNICODE)
+endif()
+
 set(MediaInfoLib_SOURCES_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../../Source)

 # On Windows debug library should have 'd' postfix.
```

**Comment by JeromeMartinez** [comment]
It is expected that MedaiInfoLib checks WenLib config for Unicode config.
I guess the ZenLib / CMake patches make that broken;
we'll check tomorrow (both fixing non unicode build and having MedaiInfoLib checking ZenLib pkgconfig for -D parts, if I remember well; note that with our Travis tests it compiles with CMake, but we don't use it the same way)

**Comment by wiiaboo** [comment]
Well, I can temporarily workaround this by adding `-DUNICODE` to CXXFLAGS, so that'll have to do.

**Comment by wiiaboo** [comment]
Also, ZenLib's pkg-config file is also missing -DUNICODE from Cflags, so it'll be needed for mediainfo executable too.

**Comment by JeromeMartinez** [comment]
missing ZenLib's pkg-config is the source of the issue, I guess.
We'll rework all of this, check that all is as before, today.

**Comment by JeromeMartinez** [comment]
@wiiaboo would https://github.com/MediaArea/ZenLib/commit/67d3ddff64865d595e0f0d91b8fd3b2881da5018 fix your issue?

**Comment by wiiaboo** [comment]
I don't think Cmake find_package() is using the pkg-config files. It's still missing the UNICODE flag. I do see it in /lib/cmake/zenlib/ZenLibTargets.cmake in
```cmake
set_target_properties(ZenLib::zen PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "UNICODE;_UNICODE;_FILE_OFFSET_BITS=64"
  INTERFACE_INCLUDE_DIRECTORIES "C:/builds/ab/local64/include"
)
```
but maybe it needs to be defined elsewhere? Either way, it still sounds like the issue is still in ZenLib.

**Comment by wiiaboo** [comment]
Doing a diff between ZenLibTargets before and after the Cmake changes in ZenLib, the big difference seems to be the rename of 'zen' to 'ZenLib::zen'. That's what MediaInfoLib isn't accepting.

**Comment by JeromeMartinez** [comment]
Thanks @wiiaboo.
The goal was not to break compatibility when we accepted (too quickly) the PR, so we'll look at this diff and will revert it if it is breaking something, and putting this change for later (when we decide to break compatibility because we absolutely need to).

**Comment by JeromeMartinez** [comment]
@wiiaboo is it OK for you after https://github.com/MediaArea/ZenLib/commit/5627436aff60e9b079f5f3cac226277e47ce53f7?

**Comment by wiiaboo** [comment]
Yes, that fixes it right up. Thanks.

**Comment by JeromeMartinez** [comment]
great!
So no more hacks on your side, it is "as before", right?

**Comment by wiiaboo** [comment]
Yeah, I also removed the seds in the build suite. Though there's [one that might break in the future](https://github.com/MediaArea/MediaInfoLib/blob/master/Project/CMake/CMakeLists.txt#L12). But I pass explicit BUILD_ZLIB=off and BUILD_ZENLIB=off now and I've always used BUILD_SHARED_LIBS=off.

**Comment by wiiaboo** [comment]
There's probably another separate issue concerning mixing CMake builds of libmediainfo with the automake build of mediainfo, in that it expects the pkg-config to contain a Libs_Static variable instead of using the proper `--static --libs` syntax, but I'll open a PR for that one in mediainfo.

**Comment by JeromeMartinez** [comment]
> but I'll open a PR for that one in mediainfo.

Would be appreciated (priority on  Libs_Static, but having a "proper" way in addition would be also great, we are not expert and we do often things wrong and help is appreciated, just not possible now to break compatibility so we need both good and wrong methods during some time)

**Comment by wiiaboo** [comment]
Priority for Libs_Static as in completely overwriting `--static --libs` or appending it?

**Comment by JeromeMartinez** [comment]
Hum... Was thinking to not have any regressions (e.g. Libs_Static as before the PR merge).
My view was to have both Libs_Static as before and what you need for `--static --libs`.
Maybe too complicated.
Let say that you do the "good practice" and I'll see what happens with Libs_Static.

**Comment by wiiaboo** [comment]
I'd be OK with just appending them. The CMake .pc files never had Libs_Static. I've always had to add `LIBS="$(pkg-config --static --libs libmediainfo)"` to the configure command, since I started using the CMake build scripts along with libcurl inclusion.

**Comment by JeromeMartinez** [comment]
OK, I see, the one who added CMake didn't care about it, and we did not verified that all is same compared to automake (we should check).

If you don't mind, please add both method, so this is more similar to automake version.
In the future, we definitely need to do more checks (some people don't like CMake, so we provide several methods, also different methods for lining, but it is more work).
