### ISSUE TITLE
PBCore output not escaping invalid XML chars

### ISSUE THREAD

**Issue by JeromeMartinez** [MediaArea/MediaInfoLib#572]
From https://www.facebook.com/MediaAreaNet/posts/1524124344329242

***

I climbed out of the Great Firewall just to report a bug on MediaInfoCLI ver0.7.97-win64. The CLI version outputs malformed PBCore2 XMLs by not escaping special characters in the text data between two XML tags. e.g.the &, <, and > in <essenceTrackAnnotation annotationType="Copyright">John & Jane<tm> Co.Ltd</essenceTrackAnnotation> will result the Python's DOM parser to fail. The correct XML text should be "John &amp; Jane&lt;tm&gt; Co.Ltd"

**Comment by kieranjol** [comment]
Is this similar to this issue: https://github.com/MediaArea/MediaInfoLib/issues/572

**Comment by g-maxime** [comment]
Fixed by d55cb6f135d41c72b2e6c1b0c5ffaf99663da95c
