### ISSUE TITLE
FLAC is not correctly identified in MOV container

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#594]
FLAC is identified as 19D in MOV container (having FFV1 video). FFmpeg identify it correctly.

Sample taken from here:
https://archive.org/download/test20100622_v210_and_ffv1/DHC36.ffv1.flac.mov

**Comment by Sami32** [comment]
Btw, while generate an ISMV file from this one with the following command line:
`ffmpeg -y -i DHC36.ffv1.flac.mov -f ismv testout.mp4`
or
`ffmpeg -y -i DHC36.ffv1.flac.mov testout.ismv`

As already reported here:
https://github.com/MediaArea/MediaInfo/issues/173

**Comment by JeromeMartinez** [comment]
Fixed by https://github.com/MediaArea/MediaInfoLib/pull/916.
