### ISSUE TITLE
How to differentiate AAC codecs ID variant in MKV with the latest MediaInfo version ?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#613]
That's great to have the codecs ID enhancement for the MPEG-4 format :+1: :smile:  but it seem that the Matroska ones are "lost" somewhere ?

Now i get `A_AAC-2` instead of `a_aac/mpeg4/lc`, `a_aac/mpeg2/lc/sbr`, `a_aac/mpeg4/ssr`... with the previous version.
So the IDs only available under Matroska container, by now, as SSR profile, are "lost", hidden.

**Comment by JeromeMartinez** [comment]
I don't remember having truncated the CodecID from Matroska when I added the feature, I just append the audioObjectType (which will be redundant in that case, but this is not a big issue).
Can you provide a sample with something else than `A_AAC`?

**Comment by Sami32** [comment]
Any MKV with AAC audio will be fine, as the only codec ID that i get is `A_AAC-2`.
[MKV-H264-AACHE-6ch.mkv.txt](https://github.com/MediaArea/MediaInfoLib/files/1311421/MKV-H264-AACHE-6ch.mkv.txt)

Example:
```logtalk
Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : HE-AAC / LC
Format settings                          : Explicit
Codec ID                                 : A_AAC-2
Duration                                 : 11 s 435 ms
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz / 24.0 kHz
Frame rate                               : 23.438 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 31 ms
Stream size                              : 267 KiB (6%)
Default                                  : Yes
Forced                                   : No
```

**Comment by Sami32** [comment]
Damn ! i cannot remember which version given me `A_AAC/MPEG4/LC`, `A_AAC/MPEG2/LC/SBR`, `A_AAC/MPEG4/SSR` informations like.
Alzheimer i guess.

**Comment by JeromeMartinez** [comment]
With AAC Main, you get the Format_Profile `Main `and now CodecID `A_AAC-1` (1 is for Main profile).

The file you provide has only `A_AAC` CodecID, previous behavior was `A_AAC` only. The ticket would be valid if you find a file with `A_AAC/MPEG4/LC` in Matroska and not displayed as such in MI.

Checking my own files, I have the expected behavior:

```
Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format version                           : Version 4
Format profile                           : HE-AAC / LC
Format settings                          : Explicit
Codec ID                                 : A_AAC/MPEG4/LC/SBR-2
Duration                                 : 45 min 33 s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 96.0 kHz / 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No
```

From my point of view this issue is invalid.

**Comment by Sami32** [comment]
Damn, it why i didn't get the expected result, i've forgotten that such case could arise :flushed: 
Sorry for this inadequat report, i will clode it.

Than you for the explanations :+1:

**Comment by Sami32** [comment]
By the way, how SSR profile will be called ? A_AAC-3 ?

**Comment by JeromeMartinez** [comment]
FYI there is a [talk](https://github.com/Matroska-Org/matroska-specification/issues/100#issuecomment-330326069) abut `A_AAC/xxx` stufff, maintainers speak about deprecating them.

**Comment by JeromeMartinez** [comment]
> By the way, how SSR profile will be called ? A_AAC-4 ?

2 things:
- `Format_Profile`: will be "SSR"
- `CodecID`: Full list of known audioObjectType values is [here](https://github.com/MediaArea/MediaInfoLib/blob/e79d77b90c208f1ad976989bd5e383146ccb0a92/Source/MediaInfo/Audio/File_Aac_Main.cpp#L113-L156). This is **not** a name, this is a codec identifier, bytes in the stream. Here, actually 2 identifiers, 1 from Matroska and 1 from AAC descriptor (if it is present).

**Comment by Sami32** [comment]
Thank you for sharing the link, i was not aware of this move, i will need to adapt the parsing and anticipate it :wink: 

Great :+1: I didn't saw that part of your code :smile:
