### ISSUE TITLE
Question: What is the "ErrorDetectionType" meaning ?

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#617]
In a Matroska file i got this into the log:
`ErrorDetectionType                       : Per level 1`

What is the meaning of a such string ?
It seem that others users meet that as well with MKV files:
https://github.com/Radarr/Radarr/issues/294
https://trac.videolan.org/vlc/ticket/17855

It seem to appear when the "menu", chapters or metadata are modified ?
http://ffmpeg.gusari.org/viewtopic.php?f=11&t=3498

Sample:
[testUnholy.mkv.txt](https://github.com/MediaArea/MediaInfoLib/files/1352445/testUnholy.mkv.txt)

**Comment by JeromeMartinez** [comment]
The file is "protected" against file corruption (i.e. if a byte changes during storage), important for e.g. archives or just knowing that your file was stored correctly (you can check its integrity with MediaConch).
There are several methods for storing the CRC, can be on level 1 element only (so CRC is across a large amount of data, e.g. several seconds of data) or several levels (e.g. at the frame level), size of data vs easiness to locate the issue when CRC fails.

See [this thread](https://www.ietf.org/mail-archive/web/cellar/current/msg00899.html) for more details.

**Comment by Sami32** [comment]
Thanks for having enlighted my lantern :)
