### ISSUE TITLE
Copy-paste Infos["Format_Settings_PS"].empty()

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#632]
![default](https://user-images.githubusercontent.com/920705/31886420-e7b89b94-b7fc-11e7-8887-db382868aba3.png)

Create help function for consolidation and reduse code size?

**Comment by JeromeMartinez** [comment]
This code is definitely a mess.
I was planning to review it completely, but I guess that a small (not taking too much time for you) help function for consolidation would not hurt (I could reuse it during my refactoring)
