### ISSUE TITLE
Encoded bit rate of 0 b/s in a Dolby E stream

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#635]
FFmpeg is displaying an audio bitrate of 2304 kb/s.

Sample: (Link valid for 7 days)
https://we.tl/s4YuGuJHTc

```logtalk
ID                                       : 4144 (0x1030)-3
Menu ID                                  : 1 (0x1)
Format                                   : Dolby E
Format settings                          : Little
Mode                                     : 20
Format settings, Endianness              : Little
Muxing mode                              : SMPTE ST 302 / SMPTE ST 337
Codec ID                                 : 6
Duration                                 : 19 s 840 ms
Bit rate mode                            : Constant
Encoded bit rate                         : 0 b/s
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 48.0 kHz
Frame rate                               : 25.000 FPS (1920 SPF)
Bit depth                                : 20 bits
Delay relative to video                  : -80 ms
Language                                 : English
```

**Comment by JeromeMartinez** [comment]
> FFmpeg is displaying an audio bitrate of 2304 kb/s.

Same with MediaInfo, except that MediaInfo understands Dolby E so displays Dolby E services. Check the ID of the 3 last audio tracks, it is same ID + dash + Dolby service number.
"0 b/s" is "encoded bit rate", not "bit rate", it means that data is muxed with the 1st Dolby track info, i.e. Track 3 has "2340 kbps" encoded bit rate (not bit rate, it is unknown) including the bit rate of tracks 3, 4, and 5 (they are from the same stream, and bit rate per Dolby E service is unknown).

**Comment by Sami32** [comment]
Ok, thank you for the explanations :+1: , that's make sens.

But i still don't see the need to display the encoded bit rate when it is zero ? (also if it is not really)
