### ISSUE TITLE
The MI version of 23 october seem to freeze while trying to open any media

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#637]
At least on Windows XP SP3 32-bit.

**Comment by pavel-pimenov** [comment]
Share Full memory dump MI + src + pdb files?

Dump for XP:
https://blogs.msdn.microsoft.com/junfeng/2008/06/19/getting-a-full-memory-dump-for-a-process/
process explorer https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by Sami32** [comment]
@pavel-pimenov Thanks for the tips, but Process Explorer doesn't seem to run for me, i suspect that my CPU is too old and that i find where is the old version that i did used some years ago...

I have no trace of _ntsd.exe_ excecutable...

**Comment by pavel-pimenov** [comment]
try http://processhacker.sourceforge.net/ 
Support: Windows XP (SP2)/Vista/7/8/10, 32-bit or 64-bit.

**Comment by Sami32** [comment]
I didn't knew that one so i have downloded it, just in case ;). Cool, thanks.
Anyway, i used the Process Explorer 15.30 version. Here is the dump file:

[MediaInfo.7z.txt](https://github.com/MediaArea/MediaInfoLib/files/1411016/MediaInfo.7z.txt)

**Comment by pavel-pimenov** [comment]
@Sami32  share "MI version of 23 october" ?
1. source code 
2. mediainfo*.exe
3. *.pdb

**Comment by Sami32** [comment]
Wouah, you are fast guys ;)
Yes, @JeromeMartinez is correct, that were i get the 23 october snapshot.

**Comment by JeromeMartinez** [comment]
Should be fixed with https://github.com/MediaArea/MediaInfoLib/pull/639.
Snapshot during the night :).

**Comment by Sami32** [comment]
Solved :+1:
