### ISSUE TITLE
8-bit RF64 wave file reported as signed instead of unsigned

### ISSUE THREAD

**Issue by david-russo** [MediaArea/MediaInfoLib#641]
[Attached file](https://github.com/MediaArea/MediaInfoLib/files/1414172/rf64-pcm-44khz-8bit-mono-minimal.zip) generated with Audacity 2.1.3, using an RF64 header, and "Unsigned 8-bit PCM" export setting.

Following the PCMWAVEFORMAT, I believe samples of eight or less bits should be treated as unsigned integers, even in RF64 files. MediaInfo correctly reports 8-bit PCMWAVEFORMAT files as unsigned.

Issue found using MediaInfo 0.7.99.

**Comment by pavel-pimenov** [comment]
Signed - default value
https://github.com/MediaArea/MediaInfoLib/blob/51cce7e6ac0bc76a3385c23a404ea66ce2a469b8/Source/MediaInfo/Multiple/File_Riff_Elements.cpp#L1558

Calc Sign:
https://github.com/MediaArea/MediaInfoLib/blob/51cce7e6ac0bc76a3385c23a404ea66ce2a469b8/Source/MediaInfo/Audio/File_Pcm.cpp#L106

Codec = L"00001000-0000-0100-8000-00AA00389B71"

![default](https://user-images.githubusercontent.com/920705/31994924-15dbbe7c-b98b-11e7-8ca4-642bdd7e1316.png)

General
Complete name                            : C:\1\rf64-pcm-44khz-8bit-mono-minimal.wav
Format                                   : Wave
Format profile                           : RF64
File size                                : 105 Bytes
Overall bit rate mode                    : Constant

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Format settings, Endianness              : Little
Format settings, Sign                    : Signed
Codec ID                                 : 00001000-0000-0100-8000-00AA00389B71
Bit rate mode                            : Constant
Bit rate                                 : 352.8 kb/s
Channel(s)                               : 1 channel
Channel positions                        : Front: C
Sampling rate                            : 44.1 kHz
Bit depth                                : 8 bits

**Comment by JeromeMartinez** [comment]
Checking FFmpeg code, they consider ==8 as unsigned else signed:

```
    { AV_CODEC_ID_PCM_U8,          0x0001 },
    { AV_CODEC_ID_PCM_S16LE,       0x0001 },
    { AV_CODEC_ID_PCM_S24LE,       0x0001 },
    { AV_CODEC_ID_PCM_S32LE,       0x0001 },
    { AV_CODEC_ID_PCM_S64LE,       0x0001 },
```

So OK to change to same behavior.

**Comment by david-russo** [comment]
The logic already exists here:
https://github.com/MediaArea/MediaInfoLib/blob/51cce7e6ac0bc76a3385c23a404ea66ce2a469b8/Source/MediaInfo/Audio/File_Pcm.cpp#L123-L130

But the code might not be taking into account that the subformat GUID reported as "00001000-0000-0100-8000-00AA00389B71" is equivalent to the format codec `0x0001`. Although the representation of the GUID also looks a little off to me... for PCM, I'd expect it to be: "0000**0001**-0000-0010-8000-00AA00389B71".

All short format codec identifiers (such as `0x0001`) have subformat GUID equivalents when specified in WAVEFORMATEXTENSIBLE files, as mentioned [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/audio/converting-between-format-tags-and-subformat-guids). (RF64 being an extension of WAVEFORMATEXTENSIBLE.)

**Comment by JeromeMartinez** [comment]
> The logic already exists here:

Will do same for RIFF directly, then I'll see (later) how to merge code because it should not be in 2 different places.

> for PCM, I'd expect it to be:

good to know.
But i don't see the relationship with my code.

**Comment by david-russo** [comment]
I think it would be useful to have the GUIDs represented in a manner that allows them to be readily compared to other sources when searching for information on specific codecs. At the moment searching for MediaInfo's GUID almost exclusively [returns MediaInfo reports](https://www.google.co.uk/search?q=%2200001000-0000-0100-8000-00AA00389B71%22), while searching for Microsoft's [returns a variety of other sources](https://www.google.co.uk/search?q=%2200000001-0000-0010-8000-00AA00389B71%22), of which there is sadly [little overlap](https://www.google.co.uk/search?q=%2200001000-0000-0100-8000-00AA00389B71%22+%2200000001-0000-0010-8000-00AA00389B71%22).

Microsoft's GUIDs are also intended for use as unique identifiers, and 0000**1000**-0000-0**100**-8000-00AA00389B71 ≠ 0000**0001**-0000-0**010**-8000-00AA00389B71, so there's that.

**Comment by JeromeMartinez** [comment]
I guess there is also a bug in the the way we convert GUID to character strings, to be studied, definitely!

**Comment by JeromeMartinez** [comment]
I don't have a lot of files for testing, but I think I handle all cases now.

Please test the latest snapshot https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20171031/

I focused on:
- No endianess for 8-bit content (irrelevant)
- endianess and sign of PCM in Matroska
- unsigned for 8-bit content
- not hiding "A_MS/ACM" in audio CodecID for Matroska.
- GUID in the right order

I hope that I missed nothing and that I introduced no regression!

**Comment by david-russo** [comment]
Tested fine on my end. Thanks for the speedy improvements :)
