### ISSUE TITLE
[cppcheck] FrameRate > 11.984 && FrameRate <= 11.094 always false

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#65]
void File__Analyze::Video_FrameRate_Rounding(size_t Pos, video Parameter)
{
    float64 FrameRate=Retrieve(Stream_Video, Pos, Parameter).To_float64();
    float64 FrameRate_Sav=FrameRate;

         if (FrameRate> 9.990 && FrameRate<=10.010) FrameRate=10.000;
    else if (FrameRate>11.984 && FrameRate<=11.094) FrameRate=11.988; <----- Bug?
    else if (FrameRate>11.994 && FrameRate<=12.010) FrameRate=12.000;
    else if (FrameRate>14.980 && FrameRate<=14.990) FrameRate=14.985;

**Comment by JeromeMartinez** [comment]
Stupid bug.
Fixed in https://github.com/MediaArea/MediaInfoLib/commit/1dd25c1946470000c86deec0b397ea7775b66703
