### ISSUE TITLE
MediaInfo shows strange characters when using Lame 3.100

### ISSUE THREAD

**Issue by d4k0** [MediaArea/MediaInfoLib#655]
I updated to Lame 3.100 and noticed that MediaInfo now shows some strange characters in the writing library line:

```
Writing library                          : LAME3.100Í
```

With Lame 3.95.5 it looked like this:

```
Writing library                          : LAME3.99r
Encoding settings                        : -m j -V 4 -q 3 -lowpass 20.5
```

Notice that the encoding settings is not present when using Lame 3.100.

robert from the hydrogenaud.io forums [found the line](https://hydrogenaud.io/index.php/topic,114777.msg946909.html#msg946909) where the bug probably occurs:

>The bug is in file MediaInfo/Audio/File_Mpega.cpp line 1408. It assumes it reads the very first version of the lame info, because it makes the wrong test. In its first draft the version text was up to 20 bytes.
>
>https://sourceforge.net/p/mediainfo/code/HEAD/tree/MediaInfoLib/trunk/Source/MediaInfo/Audio/File_Mpega.cpp

**Comment by JeromeMartinez** [comment]
Please provide a sample file, easier for me to test.

**Comment by JeromeMartinez** [comment]
Note that the code on Sourceforge is old, still there for historical reasons only, GitHub has the up to date code (it does not change the issue here, the old and buggy code is still present).

**Comment by d4k0** [comment]
Here is a sample file:

https://app.box.com/s/40b6tbcqvjaannupmyn2bkek5fye0f2f

**Comment by d4k0** [comment]
One more note: The character at the end seems to change depending on the used encoding mode (CBR, VBR etc.).

**Comment by JeromeMartinez** [comment]
Bad LAME version number detection ("10" is less than "90", the 3rd number is not tested).
Working on it.

**Comment by JeromeMartinez** [comment]
For reference, [Sourceforge ticket](https://sourceforge.net/p/mediainfo/bugs/1070/).

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/pull/656), with [Windows snapshot](https://mediaarea.net/download/snapshots/binary/mediainfo-gui/20171101-2/MediaInfo_GUI_17.09.20171101_Windows.exe) available.
Note: this is an hot fix, there is [a debate](https://sourceforge.net/p/mediainfo/bugs/1070/#656a) about how to detect new LAME versions and corresponding Info tag, discussion is not closed in case a better method for detecting new versions is found.

**Comment by d4k0** [comment]
Thanks for the quick fix!
