### ISSUE TITLE
Wave file reported as truncated when appended with extra data

### ISSUE THREAD

**Issue by david-russo** [MediaArea/MediaInfoLib#657]
MediaInfo 0.7.99 reports [this file](https://github.com/MediaArea/MediaInfoLib/files/1433880/wf-pcm-44khz-8bit-mono-file-extra-data.zip), which has one extra trailing null byte, as "IsTruncated: Yes".

**Comment by JeromeMartinez** [comment]
IMO it is the expected behavior: the extra trailing null byte may be the beginning of a new chunk, so the file is flagged as truncated (=missing bytes after this null byte). A single byte alone is not correct, so there is an issue somewhere, or did I miss something? current algo is "if there is more data, null byte included, we expect a new chunk so minimum 8 bytes; if no 8 bytes, it is considered as truncated".

What is the purpose of this extra trailing null byte here?

**Comment by david-russo** [comment]
It was a test case I created for testing wave analyzers, and the report of it being truncated surprised me because I knew it was the opposite case, but your logic might be right.

I was thinking that if the wave's size as declared in the top-level RIFF chunk header was less than the file's actual size, say because another file had been concatenated onto the end, one might be able to detect it by comparing those two values. But if a wave file can have multiple top-level RIFF chunks, then you're right, and there's no way to tell.

**Comment by JeromeMartinez** [comment]
> the report of it being truncated surprised me because I knew it was the opposite case

Just to be clear: `truncated` here is not about e.g. word alignment padding, it is mainly for detecting incomplete transfers (so many missing bytes).

>  if the wave's size as declared in the top-level RIFF chunk header was less than the file's actual size, say because another file had been concatenated onto the end, one might be able to detect it by comparing those two values.

We currently don't test RIFF chunk size = file size, we consider that several chunks may be present. good or not, issue is the lack of specs.

> But if a wave file can have multiple top-level RIFF chunks, then you're right, and there's no way to tell.

I don't have WAV specs.
From [AVI specs](http://www.jmcgowan.com/odmlff2.pdf) (same kind of format):
`There is only one RIFF chunk per file.`
--> IMO that does not prevent non-RIFF chunks to be after (or before) the RIFF chunk. Not explicitly authorized, but not forbidden.
And actually, OpenDML uses a second RIFF chunk.

So for the moment, I am not in favor of limiting to 1 RIFF chunk, and I consider the extra byte as the (truncated) begin of another chunk.

If detecting extra null byte is interesting, we could show something about it, but for the moment I don't see need about it (we see that the file has a problem with `Truncated` field)

**Comment by david-russo** [comment]
The scenario this was meant to test for was any amount of data over the original, because I thought it would be good to know if there might be any hidden data attached to the end of a file. The test file just uses a single null byte for economy of space, and takes into account word-alignment padding, occurring afterward.

But, that's a sound decision, and fair enough. As you said, a lack of definitive guidance here means there's no clear answer, though from the aforementioned AVI spec. (which Microsoft also contributed to), it does go on to say "an AVI file can be extended beyond 1 GB by placing more than one RIFF chunk in the same file (which is legal)", which bolsters my confidence in it being possible for other less-specified RIFF-based formats, such as wave.

Thanks a lot for the clarification, and feel free to close this issue.
