### ISSUE TITLE
How MeidaInfo read and display `profile_idc` value?

### ISSUE THREAD

**Issue by anonymouss** [MediaArea/MediaInfoLib#665]
We have one HEVC/mp4 file, we have write correct `profile_idc `value like 1 in hvcc, and we can also read this value from other software like Elecard StreamEye.

But in MediaInfo, it isn't shown.

Is that mean MediaInfo don't get this value from hvcc?

**Comment by JeromeMartinez** [comment]
We read `profile_idc` from the SPS, either in the track header or the actual frame depending on where is the SPS.

> But in MediaInfo, it isn't shown.

It is with the file we have.
Please provide a sample file not supported by MediaInfo.

**Comment by JeromeMartinez** [comment]
Looks like linked to https://github.com/MediaArea/MediaInfoLib/issues/666
