### ISSUE TITLE
Matroska color range showing incorrect values

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaInfoLib#669]
Hi,

It seems that if a value < 2 is present in the Range element in a Matroska file the range is reported as Full.
I only just noticed this when making screenshots for my NTTW presentation..

Full range file -color_primaries jpeg
```
$ mediainfo --Details=1 jpeg.mkv |grep Range -A 4
01D5      Range - 2 (0x2) (4 bytes)
01D5       Header (3 bytes)
01D5        Name:                            5561 (0x15B9)
01D7        Size:                            1 (0x01)
01D8       Data:                             2 (0x02)
```
Broadcast range file -color_primaries mpeg
```
$ mediainfo --Details=1 mpeg.mkv |grep Range -A 4
01D5      Range - 1 (0x1) - Full (4 bytes)
01D5       Header (3 bytes)
01D5        Name:                            5561 (0x15B9)
01D7        Size:                            1 (0x01)
01D8       Data:                             1 (0x01)

```

Here's what the spec says:
`Clipping of the color ranges. (0: Unspecified, 1: Broadcast Range, 2: Full range (no clipping), 3: Defined by MatrixCoefficients/TransferCharacteristics)`

**Comment by JeromeMartinez** [comment]
Argh, I stupidly mapped the Matroska value to the AVC/HEVC one (boolean 0 = Limited, 1 = Full).
Thanks for the bug discovery, need to fix that.

**Comment by kieranjol** [comment]
Cool, I was going to try to fix it myself but it's well beyond my abilities.

**Comment by JeromeMartinez** [comment]
Not so difficult, check https://github.com/MediaArea/MediaInfoLib/pull/670.
Note: I currently don't do any difference between 0 and 3, as I don't understand yet how `MatrixCoefficients/TransferCharacteristics` has an impact on range.
