### ISSUE TITLE
crash File_Mk::Segment_Cluster_BlockGroup_Block_Lace

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#671]
https://drdump.com/DumpGroup.aspx?DumpGroupID=942647&login=guest

![default](https://user-images.githubusercontent.com/920705/32511571-3a234b90-c405-11e7-8e30-584f8033e787.png)

 TTH = VKQAQQSGZWNAPOVAIN2UVWG6QXJBLHECRYCYPXQ
 File size = 82705295

**Comment by pavel-pimenov** [comment]
TrackNumber == 2

Hot fix:
if (streamItem.Parser==NULL)
{
return;
}

https://github.com/MediaArea/MediaInfoLib/blob/04f61e58905c5269e984f8daf11df92199659909/Source/MediaInfo/Multiple/File_Mk.cpp#L3092
![default](https://user-images.githubusercontent.com/920705/32534365-4bbc9c24-c466-11e7-9ed0-1ae29243476d.png)

**Comment by JeromeMartinez** [comment]
I prefer changing:
if (streamItem.Searching_Payload)
to
if (streamItem.Searching_Payload && streamItem.Parser) 

I am curious to get the corresponding file as there is:
            if (!Temp->second.Parser)
                Temp->second.Searching_Payload=false;

a bit sooner in the code.

**Comment by pavel-pimenov** [comment]
file not found yet :-(
i will create pull request with "if (streamItem.Searching_Payload && streamItem.Parser)"

1. Stream.empty() 

void File_Mk::Segment_Cluster_BlockGroup_Block_Lace()
{
    stream& streamItem=Stream[TrackNumber];

2. call stream::stream
https://github.com/MediaArea/MediaInfoLib/blob/04f61e58905c5269e984f8daf11df92199659909/Source/MediaInfo/Multiple/File_Mk.h#L354

3. streamItem.Searching_Payload=true;

crash

**Comment by JeromeMartinez** [comment]
I guess this is a bug in the file with a stream not registered, right not the best method, I need to refactor that a bit.
