### ISSUE TITLE
7.1 channels not detected in E-AC-3 streams

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#681]
From the specification, E-AC-3 can support until 15 channels, but it seem that MediaInfo and FFmpeg limited the support to AC-3 maximum channels specification.
FFmpeg fail as well, it parse them as 6 channels only.

Samples:
[snip_7.1.eac3.txt](https://github.com/MediaArea/MediaInfoLib/files/1478962/snip_7.1.eac3.txt)
[7.1.eac3.txt](https://github.com/MediaArea/MediaInfoLib/files/1478963/7.1.eac3.txt)

**Comment by mkver** [comment]
1. FFmpeg recently got support for this; it can even extract the core of a E-AC-3 extension+AC-3 core package.
2. The situation is even worse than what @Sami32 says: Somehow it believes that the bitrate is 500b/s (yes, b, not kb). In a container that reports time accurately this will look like this:
```
General
Unique ID                                : 149143172534739465722254633783142519505 (0x7033EE217E1BAF37E31AE877CBAE12D1)
Complete name                            : I:\snip.7.1.mka
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 9.78 MiB
Duration                                 : 1 min 4 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 1 282 kb/s
Writing application                      : Lavf58.13.100
Writing library                          : Lavf58.13.100
ErrorDetectionType                       : Per level 1

Audio
ID                                       : 1
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Codec ID                                 : A_EAC3
Duration                                 : 1 min 4 s
Bit rate mode                            : Constant
Bit rate                                 : 500 b/s
Channel(s)                               : 8 channels
Channel(s)_Original                      : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 SPF)
Bit depth                                : 32 bits
Compression mode                         : Lossy
Stream size                              : 3.91 KiB (0%)
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No
```
In this example FFmpeg has correctly put 8 as the number of channels in the header, but mediainfo thinks that the real original value is six.
If one doesn't use a container that provides information about the duration, MediaInfo will instead report a much too long duration (probably as a consequence of the wrong bitrate detection).
3. Further samples are [here](https://forum.videohelp.com/attachments/45411-1524761965/00925.m2ts) and [here](https://forum.videohelp.com/attachments/43277-1506985180/The%20Great%20Wall.7z).

**Comment by JeromeMartinez** [comment]
Thanks for the samples.
There will be a huge work of refactoring about AC-3 / E-AC-3 next month.

**Comment by JeromeMartinez** [comment]
Supported now with https://github.com/MediaArea/MediaInfoLib/pull/896.
