### ISSUE TITLE
V571 Recurring check. This condition was already verified in line

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#711]
V571 Recurring check. This condition was already verified in line 9266. file_mxf.cpp 9268
V571 Recurring check. This condition was already verified in line 10293. file_mxf.cpp 10295

https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L9268
https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfo/Multiple/File_Mxf.cpp#L10295

![default](https://user-images.githubusercontent.com/920705/33519735-2ecb3ce0-d7be-11e7-94b3-5b511527abfd.png)

![default](https://user-images.githubusercontent.com/920705/33519737-3ac79264-d7be-11e7-8fdb-f3ce48d23ccd.png)

**Comment by JeromeMartinez** [comment]
Confirmed
