### ISSUE TITLE
Crash when open "incorrect" matroska.

### ISSUE THREAD

**Issue by Aleksoid1978** [MediaArea/MediaInfoLib#720]
Sample - https://yadi.sk/i/po7SrSNz3QKGBp
Quick fix - https://sourceforge.net/p/mpcbe/code/3161/

**Comment by pavel-pimenov** [comment]
Thanks for sample file https://github.com/MediaArea/MediaInfoLib/issues/671

**Comment by JeromeMartinez** [comment]
@Aleksoid1978 please confirm that this is fixed in master branch.

**Comment by Aleksoid1978** [comment]
Confirm.
