### ISSUE TITLE
SLS non-core codec ID

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#725]
Is that expected codec ID or or typo ?
Should have been `mp4a-40-37` codec ID ?
```
Audio #2
ID                                       : 2
Format                                   : SLS
Format/Info                              : MPEG-4 Scalable Lossless Coding
Format profile                           : non-core
Codec ID                                 : m4ae-40-37
```

**Comment by JeromeMartinez** [comment]
`m4ae` is a direct readout from the file, no idea about the difference with `mp4a`.
File?

**Comment by Sami32** [comment]
"non-core" sample related to my wondering:
[sls2100_aot02_192_24.mp4.txt](https://github.com/MediaArea/MediaInfoLib/files/1542578/sls2100_aot02_192_24.mp4.txt)

"core" sample for comparison:
[MPEG-4_SLS.mp4.txt](https://github.com/MediaArea/MediaInfoLib/files/1542596/MPEG-4_SLS.mp4.txt)

**Comment by JeromeMartinez** [comment]
IMO the `m4ae` thing may be something meaning that the 2nd track is not a main track, only an "extension" (lossless part compared to lossy 1st track), there is a `dpnd` atom ("dependancy") in the 2nd track.

**Comment by Sami32** [comment]
That make sens.
Thank you for your insight :+1:
