### ISSUE TITLE
typo in Matroska CRC-32 Element Name

### ISSUE THREAD

**Issue by dericed** [MediaArea/MediaInfoLib#78]
EBML and Matroska have an Element called `CRC-32`. MediaInfoLib calls this Element as `CRC32`. See https://github.com/MediaArea/MediaInfoLib/blob/efcb15d91d9a09fba8bf42d129fb4e87dbcf6aac/Source/MediaInfo/Multiple/File_Mk.cpp#L1309.

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/8371152d48fc13cc0be55a47616b68ba5557464d).
