### ISSUE TITLE
FFV1-SLICE-SliceContent fail

### ISSUE THREAD

**Issue by aeschweik** [MediaArea/MediaInfoLib#782]
Hi,

In running MediaConch on an FFV1 Matroska file I am getting a result I can't place. Running `mediaconch /Users/archivesx/Desktop/Annie/sample.mkv` gives the following results:

```
fail! /Users/archivesx/Desktop/Annie/sample.mkv
 -- FFV1-SLICE-SliceContent
 --    [fail:]
 --     [/Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[1]/SliceContent[1] at bytes offset of 745]
```

This does not happen with all FFV1 Matroska files I try, but I am not sure what would prompt this result.

Thanks!

**Comment by JeromeMartinez** [comment]
I think it is a problem in our decoder (and this is not good for a checker!), as FFmpeg has no decoding issues.
thanks for the report, I'll dig in it soon.

**Comment by privatezero** [comment]
@elderskatesman and the UW Libraries are reporting a similar issue with one FFV1/MKV out of a set they ran through mediaconch:

> FFV1-SLICE-sar_den Tests run: 4 | Results: ❌ Fail count: 4
Results: fail ❌ 
Name: sar_den
Offset: 1233
Value context: /Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[1]/SliceHeader[1]
Value: 1

**Comment by JeromeMartinez** [comment]
[latest snapshot](https://mediaarea.net/download/snapshots/binary/mediaconch-gui) contains the fix. Public release next week, please review before the release if possible.
You need to clear the database, " --force" for each file with CLI (or drop the database), "Database" then "Delete all results from database" in GUI.
