### ISSUE TITLE
Old XML output option?

### ISSUE THREAD

**Issue by kieranjol** [MediaArea/MediaInfoLib#785]
Hi, it looks like the XML Output has changed to the updated schema. Is there any way to get access to the older XML output that was used? I have some scripts and workflows that relied on the verbose output provided by `-f --Language=Raw --Output=XML`. I could totally work around it but I was just wondering if there was an option that I was missing.

I just noticed this issue in a different repo and it reminded me to check in on this. https://github.com/BAM-PFA/pymm/issues/1

**Comment by JeromeMartinez** [comment]
[`--Output=OldXML`](https://github.com/MediaArea/MediaInfoLib/blob/6a895f57e8318ac112a59cb092928ecbfc47986f/History_DLL.txt#L14)

**Comment by kieranjol** [comment]
Thank you!
