### ISSUE TITLE
vc++ 2010 'log' : ambiguous call to overloaded function

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#82]
1>q:\vc15\r5xx\mediainfolib\source\mediainfo\multiple\file_mxf.cpp(11087): error C2668: 'log' : ambiguous call to overloaded function
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\math.h(575): could be 'long double log(long double)'
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\math.h(527): or       'float log(float)'
1>          c:\program files (x86)\microsoft visual studio 10.0\vc\include\math.h(120): or       'double log(double)'

Fix:
        AcquisitionMetadata_Add(Code2, Ztring::ToZtring(0x100000*(1-(log(float(Value))-log(2.0))/8),

**Comment by JeromeMartinez** [comment]
[Fixed](https://github.com/MediaArea/MediaInfoLib/commit/94e8f048f6bbd7c312a147b3286786de571bf241).
