### ISSUE TITLE
Mediainfo does not handle AWS S3 url with special characters in S3 keys

### ISSUE THREAD

**Issue by swatifursule** [MediaArea/MediaInfoLib#823]
If I use filename(valid s3 key) with special characters, from AWS S3, it is not accepting it as valid input. I used below url where username, secret and bucketname are specific to my aws account. and 'testing/mini & bar.mp4' is the key.

https://username:secret@s3-ap-southeast-2.amazonaws.com/bucketname/testing/mini & bar.mp4

<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>testing/mini</Key><RequestId>157877D3B661D9A6</RequestId></Error>

If used it with single or double quotes, it shows signature mismatch error.

<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
When looked into MediaArea/MediaInfoLib code, it seems only space is handled and other special characters are not handled for aws key.

From Reader_libcurl.cpp

// URL encoding
MediaInfo_Config::urlencode ShouldUrlEncode=Config.URLEncode_Get();
if (ShouldUrlEncode==MediaInfo_Config::URLEncode_Guess)
{
    if (File_URL.Path.find(' '))
        ShouldUrlEncode=MediaInfo_Config::URLEncode_Yes;
}
if (ShouldUrlEncode==MediaInfo_Config::URLEncode_Yes)
    File_URL.Path=ZenLib::Format::Http::URL_Encoded_Encode(File_URL.Path);
When searched further for such issues, below issue talks about space in aws key, which seems to be resolved now. https://sourceforge.net/p/mediainfo/bugs/960/

Mediainfo should handle special characters in AWS keys. Also want to know whether --urlencode options is helpful, if so, how to use it,

**Comment by JeromeMartinez** [comment]
We definitely need to be more explicit about that, we'll prepare a dedicated FAQ for that. in the meanwhile:

The [license](https://mediaarea.net/en/MediaInfo/License) you currently have says "the software is provided as is", which means that it does not include any service level agreement.
The "NeedSponsor" flag indicates that no current sponsor is interested in the issue and that we (MediaArea company, the "MediaInfo team") handle the issue when we have free time, so there is no estimate of time arrival of the fix.
In practice, either someone else provides (it is open source) a patch (we'll accept it, if QA of the patch is OK) or we'll handle it at some point in the future (no idea about when, as it is not crrently an issue for us nor one of our customers having a support agreemenent).

If MediaInfo is critical for your project, having a tool without support is maybe not the best choice, we suggest that you become a [sponsor](https://mediaarea.net/SupportUs/Corporate) or get a [support package](https://mediaarea.net/Services). You would get a service level agreement and could be sure your issue would be handled when you need.

**Comment by swatifursule** [comment]
Thanks for the information, Jérôme.

I have found workaround for my problem, which is to use pre-signed url.

Following are the commands I have used:
1. aws s3 presign 's3://bucketname/testing/mini & bar™©.mp4' => "presignd url"
2. mediainfo 'presignd url'

Thanks for your support.

Regards,
Swati
