### ISSUE TITLE
empty output for some MPEG-TS from HDHomerun

### ISSUE THREAD

**Issue by SenorSmartyPants** [MediaArea/MediaInfoLib#826]
I'm using debian armhf and have tried with mediainfo-cli versions 0.7.91 and 17.12. I have not tested with 18.03 since that is in unstable debian and would want to install too many items from that branch when I first tried to update to it.

I recorded these video files using mythtv and my hdhomerun. Most files return empty results from the two mentioned versions.  A couple files generate results correctly.

**Comment by JeromeMartinez** [comment]
We need a sample file.

**Comment by SenorSmartyPants** [comment]
How much of the head of the file do you need? These full files are several GB.

**Comment by SenorSmartyPants** [comment]
Here's a truncated version of one of the files that didn't make output. But the weird thing is, the original creates no output, but the truncated file processes fine.

[iZ.trun.zip](https://github.com/MediaArea/MediaInfoLib/files/1853725/iZ.trun.zip)

**Comment by SenorSmartyPants** [comment]
Going back over all the mythtv recordings, it seems that files 2.0GB and under process correctly, but files 2.1GB or larger do not.

**Comment by SenorSmartyPants** [comment]
2140913920 bytes processed ok
2150769068 bytes did not

**Comment by hyperair** [comment]
I think the large file support bug was fixed in a later version. Please try the package from `testing`.

**Comment by SenorSmartyPants** [comment]
upgrading libzen to 0.4.37-1 fixed this.

Thanks.
