### ISSUE TITLE
Slice Junk Error

### ISSUE THREAD

**Issue by CSchloss385** [MediaArea/MediaInfoLib#838]
Hello, 
I got the following error on a couple of files recently:  
```
-- FFV1-SLICE-JUNK
 --    [fail:]
 --     [/Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[7] at bytes offset of 1666]
 --    [fail:]
 --     [/Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[8] at bytes offset of 1784]
 --    [fail:]
 --     [/Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[10] at bytes offset of 2029]
 --    [fail:]
 --     [/Segment[1]/Cluster[1]/SimpleBlock[1]/Data[1]/Frame[1]/Slice[14] at bytes offset of 2494]
```

I included a 1 second sample of the file. Any feedback would be appreciated. :) 

[slicejunk.mkv.zip](https://github.com/MediaArea/MediaInfoLib/files/1932360/slicejunk.mkv.zip)

**Comment by JeromeMartinez** [comment]
I think it is already fixed (I tested with 17.12 and file fails, then with 18.03 it passes).
Please test with 18.03 (using " --force" at the command line or clearing the database in GUI).

**Comment by JeromeMartinez** [comment]
Looks like it has the same origin than in https://github.com/MediaArea/MediaInfoLib/issues/782 (difference here is that the parsing was letting bytes in the bitstream, in other ticket it was needing more bytes)

**Comment by CSchloss385** [comment]
Yeah, I was using an old version. oops! I updated to the latest version and it works now. Thank you for your help!

**Comment by JeromeMartinez** [comment]
No problem, don't hesitate to report if you find another issue.
