### ISSUE TITLE
how to build mediainfolib with static libcurl?

### ISSUE THREAD

**Issue by jiamo** [MediaArea/MediaInfoLib#853]
Hi I want to use mediainfo in `aws lambda`. I already have handle the static lib zen and mediainfo
Here is what I have done:

```

apt-get install git automake autoconf libtool pkg-config make g++ zlib1g-dev libcurl4-gnutls-dev
git clone https://github.com/MediaArea/ZenLib.git
git checkout v0.4.37
cd ZenLib/Project/GNU/Library
./autogen.sh
./configure --enable-static
make -j4

git clone https://github.com/MediaArea/MediaInfoLib.git
 cd MediaInfoLib/Project/GNU/Library/
./autogen.sh
./configure --enable-static --with-libcurl    #   lambda machine don't have this libcurl
make -j4

git clone https://github.com/MediaArea/MediaInfo.git
git checkout v18.05
git clone 
cd MediaInfo/Project/GNU/CLI
./autogen.sh
./configure --enable-staticlibs
make -j4

# why we need this because make only build bash script not ELF
g++ -O2 -DUNICODE -DUNICODE -DSIZE_T_IS_LONG -o mediainfo CLI_Main.o CommandLine_Parser.o Help.o Core.o  ../../../../MediaInfoLib/Project/GNU/Library/.libs/libmediainfo.a -lz -L/home/ubuntu/ZenLib/Project/GNU/Library/.libs /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so ../../../../ZenLib/Project/GNU/Library/.libs/libzen.a -lpthread -lstdc++ -pthread -Wl,-rpath -Wl,/home/ubuntu/ZenLib/Project/GNU/Library/.libs

cp /usr/local/bin/mediainfo .
```
But in `aws lambda` It will have `./mediainfo: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: N`

This is my question. How can I change  `libcurl-gnutls.so.4`  to static file into the ELF?

**Comment by JeromeMartinez** [comment]
We don't use ourselves, nor our sponsors, this configuration (all static) and it is specific, so you are on you own.
Just some hints (we did not check ourselves the technical ones):
- I see " --enable-staticlibs" in the library related configure script, maybe using it also for lib build helps,
- [a blog post (not from us) about MediaInfo and AWS lambda](https://aws.amazon.com/blogs/compute/extracting-video-metadata-using-lambda-and-mediainfo/),
- you may be interested in [sponsoring MediaInfo](https://mediaarea.net/SupportUs/Corporate), for both supporting MediaInfo and having us look on specific cases like this one (e.g. we could officially provide a AWS lambda build in our releases).

**Comment by jiamo** [comment]
Thanks.
I create a https://gist.github.com/jiamo/1cb759fa9d3bceaa2146cae08e47ee52
For how to build success. 
(May be have some change. I modify and can't remember too small change)
