### ISSUE TITLE
ExternalMetaDataConfig_Get': is not a member of 'MediaInfoLib::MediaInfo_Config'

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#953]
error C2039: 'ExternalMetaDataConfig_Get': is not a member of 'MediaInfoLib::MediaInfo_Config'

![default](https://user-images.githubusercontent.com/920705/44186476-4c8bf200-a122-11e8-971f-f10dbf758fa7.png)

Fix:
    #if defined(MEDIAINFO_EBUCORE_YES) || defined(MEDIAINFO_NISO_YES)
?

**Comment by JeromeMartinez** [comment]
ExternalMetadata is now usable in some other cases.
So the opposite, is https://github.com/MediaArea/MediaInfoLib/pull/954 OK?
