### ISSUE TITLE
Questions about the configuration options

### ISSUE THREAD

**Issue by Sami32** [MediaArea/MediaInfoLib#956]
Sorry if that is obvious for anyone else but i'm wondering what is the difference between the options found into the _MediaInfo_Config.cpp_ file and the ones found into the _MediaInfo_Config_MediaInfo.cpp_ (Option_Lower).

Does it mean that the old configuration like `MI.Option("Language", "raw");` are not valid anymore and should be `MI.Option("Language_Raw", "1");` instead?
If yes, since which MediaInfo version it had changed?

Thank you in advance for any informations shared ;)

As a side note, _MediaInfo.h_ comments seem not be updated.

**Comment by JeromeMartinez** [comment]
> Sorry if that is obvious for anyone

It is not obvious for me, so I guess it is not for anyone :).

> what is the difference between the options found into the MediaInfo_Config.cpp file and the ones found into the MediaInfo_Config_MediaInfo.cpp 

15 years ago the idea was that options not starting with "File_" (in MediaInfo_Config_MediaInfo.cpp, you need to send the option to each instance) are per file, else it is global (in MediaInfo_Config.cpp, you send them once and each instance inherits from the global settings), and my goal was that all options are in both versions but currently it is not the case.

> Does it mean that the old configuration like MI.Option("Language", "raw"); are not valid anymore?

AFAIK there is not change on this side.

> As a side note, MediaInfo.h comments seem not be updated.

Definitely out of date but no short term plan to fix that (looks like that nobody is interested in sponsoring doc, so it stays as is).

**Comment by Sami32** [comment]
Ah...Ok, now it make sens to me ;)

Should `MI.Option("Language_Raw", "1");` be a better choice? because now i get suspicious that our very old code work as expected.

**Comment by JeromeMartinez** [comment]
> Should MI.Option("Language_Raw", "1"); be a better choice? 

does it works? (AFK)
I use `MI.Option("Language", "raw");`

**Comment by Sami32** [comment]
To be honest i didn't tried, but as you make me look at our code and that i read `Language_Raw=false` into the _MediaInfo_Config.cpp_ file i was wondering about.

Thank you for having shared your knowledge 😄

**Comment by Sami32** [comment]
2 more questions ;)

- In what case the `Demux=0` option should be used and what it does?
- Why there is 2 options for `Verbosity`?
`Verbosity=0;`
`Verbosity=(float32)0.5;`

**Comment by JeromeMartinez** [comment]
Demux option is for demuxing raw streams from a container.
Verbosity option double init is a typo.

**Comment by Sami32** [comment]
Oh, do you mean that MediaInfo could also produce demuxed stream(s) as output?
I was not aware of that.

**Comment by Sami32** [comment]
Hehe, that is nice to know about, perhaps we could make use of it ;)
I was naively thinking of MediaInfo only as a metadata peeking engine. 
Yes, i discovered with surprise too many hidden options that i will try to occult for now.
