### ISSUE TITLE
Pointer arithmetic overrun: 0x077DAE60+2316

### ISSUE THREAD

**Issue by pavel-pimenov** [MediaArea/MediaInfoLib#965]
[amorphis_2001_08.lqt.zip](https://github.com/MediaArea/MediaInfoLib/files/2318150/amorphis_2001_08.lqt.zip)

C++Builder + CodeGuard

![default](https://user-images.githubusercontent.com/920705/44582348-0978f100-a7aa-11e8-9766-b9f9d277bf88.png)

Error 00109. 0x130210 (Thread 0x1BD8):
Pointer arithmetic overrun: 0x077DAE60+2316, that is at offset 0+2316 in heap
 block 0x077DAE60 which is only 2272 bytes long.
Call Tree:
   0x0056E116(=PreRelease.exe:0x01:16D116) ..\..\..\Source\MediaInfo\File__Analyze_Buffer.cpp#100
   0x00B936BA(=PreRelease.exe:0x01:7926BA) ..\..\..\Source\MediaInfo\Video\File_Hevc.cpp#1838
   0x00B8EFD2(=PreRelease.exe:0x01:78DFD2) ..\..\..\Source\MediaInfo\Video\File_Hevc.cpp#1083
   0x0055C88F(=PreRelease.exe:0x01:15B88F) ..\..\..\Source\MediaInfo\File__Analyze.cpp#2359
   0x00557F50(=PreRelease.exe:0x01:156F50) ..\..\..\Source\MediaInfo\File__Analyze.cpp#1513
   0x00555A0E(=PreRelease.exe:0x01:154A0E) ..\..\..\Source\MediaInfo\File__Analyze.cpp#1080
   0x00551CFD(=PreRelease.exe:0x01:150CFD) ..\..\..\Source\MediaInfo\File__Analyze.cpp#693
   0x006F3DA0(=PreRelease.exe:0x01:2F2DA0) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1315
   0x00AC5264(=PreRelease.exe:0x01:6C4264) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#756
   0x00AC371E(=PreRelease.exe:0x01:6C271E) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#292
   0x006CA8A0(=PreRelease.exe:0x01:2C98A0) ..\..\..\Source\MediaInfo\MediaInfo_File.cpp#927
   0x00AC2DD9(=PreRelease.exe:0x01:6C1DD9) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#209
   0x006F232C(=PreRelease.exe:0x01:2F132C) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1061
   0x006ECE26(=PreRelease.exe:0x01:2EBE26) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#817
   0x00676899(=PreRelease.exe:0x01:275899) ..\..\..\Source\MediaInfo\MediaInfo.cpp#89

The object array (0x077DAE60) [size: 2272 bytes] was created with new[]
Call Tree:
   0x00B8ECCA(=PreRelease.exe:0x01:78DCCA) ..\..\..\Source\MediaInfo\Video\File_Hevc.cpp#1040
   0x0055C88F(=PreRelease.exe:0x01:15B88F) ..\..\..\Source\MediaInfo\File__Analyze.cpp#2359
   0x00557F50(=PreRelease.exe:0x01:156F50) ..\..\..\Source\MediaInfo\File__Analyze.cpp#1513
   0x00555A0E(=PreRelease.exe:0x01:154A0E) ..\..\..\Source\MediaInfo\File__Analyze.cpp#1080
   0x00551CFD(=PreRelease.exe:0x01:150CFD) ..\..\..\Source\MediaInfo\File__Analyze.cpp#693
   0x006F3DA0(=PreRelease.exe:0x01:2F2DA0) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1315
   0x00AC5264(=PreRelease.exe:0x01:6C4264) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#756
   0x00AC371E(=PreRelease.exe:0x01:6C271E) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#292
   0x006CA8A0(=PreRelease.exe:0x01:2C98A0) ..\..\..\Source\MediaInfo\MediaInfo_File.cpp#927
   0x00AC2DD9(=PreRelease.exe:0x01:6C1DD9) ..\..\..\Source\MediaInfo\Reader\Reader_File.cpp#209
   0x006F232C(=PreRelease.exe:0x01:2F132C) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#1061
   0x006ECE26(=PreRelease.exe:0x01:2EBE26) ..\..\..\Source\MediaInfo\MediaInfo_Internal.cpp#817
   0x00676899(=PreRelease.exe:0x01:275899) ..\..\..\Source\MediaInfo\MediaInfo.cpp#89
   0x00BECD1B(=PreRelease.exe:0x01:7EBD1B) ..\..\..\Source\PreRelease\VCL\PreRelease_.cpp#45
   0x00BECB87(=PreRelease.exe:0x01:7EBB87) ..\..\..\Source\PreRelease\VCL\PreRelease_.cpp#39

**Comment by JeromeMartinez** [comment]
It does not hurt because the buffer will never be read (BS_Size is 0) but I understand that this is not a good practice, will adapt a bit the code.
